### ISSUE TITLE
Uncaught TypeError: Cannot set property '0' of undefined

### ISSUE THREAD

**Issue by tonatiuh** [jeremyramin/terminal-plus#102]
[Enter steps to reproduce below:]

1. Given I have terminal-plus open in an external monitor (res of 1980x1024)
2. When I switch to another app
3. And I unplug my computer (display of 1280x1024)
4. And switch back to Atom
5. Then this error appears.

**Atom Version**: 1.2.1
**System**: Mac OS X 10.11.1
**Thrown From**: [terminal-plus](https://github.com/jeremyramin/terminal-plus) package, v0.14.3

### Stack Trace

Uncaught TypeError: Cannot set property '0' of undefined

```
At /Users/tonatiuh/.atom/packages/terminal-plus/node_modules/term.js/src/term.js:1917

TypeError: Cannot set property '0' of undefined
    at Terminal.write (/Users/tonatiuh/.atom/packages/terminal-plus/node_modules/term.js/src/term.js:1917:55)
    at /Users/tonatiuh/.atom/packages/terminal-plus/lib/view.coffee:124:17
    at /Applications/Atom.app/Contents/Resources/app.asar/src/task.js:126:25
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:86:11)
    at ChildProcess.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/task.js:78:34)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at handleMessage (internal/child_process.js:685:10)
    at Pipe.channel.onread (internal/child_process.js:440:11)
```

### Commands

```
     -0:04.7.0 window:toggle-full-screen (textarea.)
  9x -0:04.7.0 blur (textarea.)
```

### Config

```json
{
  "core": {
    "audioBeep": false,
    "packagesWithKeymapsDisabled": [
      "terminal-plus"
    ],
    "themes": [
      "atom-material-ui",
      "atom-material-syntax"
    ],
    "disabledPackages": [
      "symbols-view"
    ]
  },
  "terminal-plus": {
    "core": {
      "workingDirectory": "Home"
    },
    "style": {
      "animationSpeed": 1.5,
      "defaultPanelHeight": 800,
      "fontFamily": "Roboto Mono"
    },
    "ansiColors": {
      "normal": {
        "cyan": {
          "red": 139,
          "green": 233,
          "blue": 253,
          "alpha": 1
        },
        "green": {
          "red": 90,
          "green": 247,
          "blue": 142,
          "alpha": 1
        },
        "blue": {
          "red": 202,
          "green": 169,
          "blue": 250,
          "alpha": 1
        },
        "red": {
          "red": 255,
          "green": 110,
          "blue": 103,
          "alpha": 1
        },
        "yellow": {
          "red": 244,
          "green": 173,
          "blue": 0,
          "alpha": 1
        },
        "magenta": {
          "red": 255,
          "green": 146,
          "blue": 208,
          "alpha": 1
        },
        "white": {
          "red": 199,
          "green": 199,
          "blue": 199,
          "alpha": 1
        }
      },
      "zBright": {
        "brightBlue": {
          "red": 202,
          "green": 169,
          "blue": 250,
          "alpha": 1
        },
        "brightGreen": {
          "red": 90,
          "green": 247,
          "blue": 142,
          "alpha": 1
        },
        "brightYellow": {
          "red": 244,
          "green": 237,
          "blue": 0,
          "alpha": 1
        },
        "brightRed": {
          "red": 255,
          "green": 110,
          "blue": 103,
          "alpha": 1
        },
        "brightMagenta": {
          "red": 255,
          "green": 146,
          "blue": 208,
          "alpha": 1
        },
        "brightCyan": {
          "red": 154,
          "green": 237,
          "blue": 254,
          "alpha": 1
        },
        "brightBlack": {
          "red": 104,
          "green": 104,
          "blue": 104,
          "alpha": 1
        }
      }
    },
    "iconColors": {
      "blue": {
        "red": 0,
        "green": 92,
        "blue": 187,
        "alpha": 1
      }
    }
  }
}
```

### Installed Packages

```coffee
# User
advanced-open-file, v0.12.3
atom-material-syntax, v0.2.4
atom-material-ui, v0.8.0
cucumber, v0.5.0
file-type-icons, v0.7.4
language-haml, v0.23.6
linter, v1.11.2
linter-rubocop, v0.4.4
recent-finder, v0.4.4
relative-numbers, v0.2.4
remember-file-positions, v0.2.0
terminal-plus, v0.14.3
vim-mode, v0.63.0
vim-surround, v0.8.1

# Dev
No dev packages
```

**Comment by jeremyramin** [comment]
Thanks for the reproduction steps. I'll take a look and get back to you.

**Comment by tonatiuh** [comment]
I'm closing this issue given I tried to reproduce the bug again and I wasn't able to.

**Comment by tsolace** [comment]
Same exact issue happened when I was resizing a single terminal tab with a browser-plus window above it.

**Comment by greduan** [comment]
I can reproduce this by running a tmux session inside the terminal tab, scrolling in tmux `prefix pageUp`, and then making the terminal smaller.
