### ISSUE TITLE
Uncaught Error: ioctl(2) failed.

### ISSUE THREAD

**Issue by Grawl** [jeremyramin/terminal-plus#126]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.2.4
**System**: Mac OS X 10.11.2
**Thrown From**: [terminal-plus](https://github.com/jeremyramin/terminal-plus) package, v0.14.5

### Stack Trace

Uncaught Error: ioctl(2) failed.

```
At /Users/grawl/.atom/packages/terminal-plus/node_modules/pty.js/lib/pty.js:361

Error: ioctl(2) failed.
    at Error (native)
    at Terminal.resize (/Users/grawl/.atom/packages/terminal-plus/node_modules/pty.js/lib/pty.js:361:7)
    at TermView.resizeToPane (/Users/grawl/.atom/packages/term/lib/TermView.js:115:12)
    at delayed (/Users/grawl/.atom/packages/term/node_modules/debounce/index.js:19:14)
```

### Commands

```
  3x -4:19.2.0 pane:show-next-item (atom-text-editor.editor.is-focused)
  2x -2:48.9.0 terminal-plus:toggle (div.package-detail.panels-item)
     -2:45.2.0 pane:show-next-item (div.package-detail.panels-item)
     -2:44.6.0 terminal-plus:toggle (atom-text-editor.editor.is-focused)
     -2:42.8.0 pane:show-previous-item (atom-text-editor.editor.is-focused)
     -2:40.5.0 core:select-all (atom-text-editor#terminal-plus.core.shell.editor.mini.is-focused)
     -2:40.3.0 core:cut (atom-text-editor#terminal-plus.core.shell.editor.mini.is-focused)
  4x -2:36.5.0 core:backspace (atom-text-editor#terminal-plus.core.shell.editor.mini.is-focused)
     -2:33.2.0 pane:show-next-item (atom-text-editor#terminal-plus.core.shell.editor.mini.is-focused)
 13x -2:32.6.0 terminal-plus:toggle (atom-text-editor.editor.is-focused)
  2x -1:27.2.0 core:move-left (atom-text-editor#terminal-plus.style.animationSpeed.editor.mini.is-focused)
  2x -1:26.5.0 core:move-right (atom-text-editor#terminal-plus.style.animationSpeed.editor.mini.is-focused)
  3x -1:26.2.0 core:backspace (atom-text-editor#terminal-plus.style.animationSpeed.editor.mini.is-focused)
  2x -1:25.3.0 terminal-plus:toggle (atom-text-editor#terminal-plus.style.animationSpeed.editor.mini.is-focused)
     -1:12.3.0 core:confirm (atom-text-editor#terminal-plus.style.fontFamily.editor.mini.is-focused)
  6x -1:11.5.0 terminal-plus:toggle (atom-text-editor#terminal-plus.style.fontFamily.editor.mini.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "autocomplete",
      "command-palette",
      "wrap-guide",
      "terminal-status",
      "terminal",
      "term",
      "Termrk",
      "atom-terminal"
    ],
    "themes": [
      "native-ui",
      "one-light-syntax"
    ]
  },
  "terminal-plus": {
    "core": {
      "shell": "fish",
      "workingDirectory": "Active File"
    },
    "style": {
      "animationSpeed": 10,
      "fontFamily": "Fira Code",
      "theme": "inverse"
    },
    "toggles": {
      "autoClose": true
    }
  }
}
```

### Installed Packages

```coffee
# User
auto-detect-indentation, v0.4.2
autocomplete-clang, v0.8.8
autocomplete-paths, v1.0.2
autocomplete-sass, v0.1.0
language-jade, v0.6.2
minimap, v4.17.0
native-ui, v0.10.0
pigments, v0.19.1
project-manager, v2.6.5
soft-wrap-indicator, v0.7.0
terminal-plus, v0.14.5

# Dev
No dev packages
```

**Comment by Grawl** [comment]
sorry

**Comment by jeremyramin** [comment]
Were you able to fix your issue?

**Comment by Grawl** [comment]
It was because of I resized Atom window with open Terminal Plus pane. Cannot repeat this issue again. Sent this issue in the middle of a night, sorry again.

**Comment by cedricfrancoys** [comment]
Came across same issue : 
see https://github.com/chjj/pty.js/issues/187

quick check before resizing : 
if (!socket.term.readable || !socket.term.writable || socket.term.destroyed) return;
