### ISSUE TITLE
Git is a silent requirement, but not listed anywhere

### ISSUE THREAD

**Issue by timkrins** [jeremyramin/terminal-plus#127]
Discovered this while installing on a fresh Windows machine with Git not yet installed.
Installation fails silently except in the developer console.

I see in the todo's that there is an item that says, "Possibly merge dependencies into Terminal-Plus?" - I'm assuming this would fix the issue?

```
Installing package terminal-plus failed Error: Installing “terminal-plus@0.14.5” failed.
    at C:\Users\Socks\AppData\Local\atom\app-1.2.4\resources\app.asar\node_modules\settings-view\lib\package-manager.js:457:21
    at exit (C:\Users\Socks\AppData\Local\atom\app-1.2.4\resources\app.asar\node_modules\settings-view\lib\package-manager.js:73:16)
    at triggerExitCallback (C:\Users\Socks\AppData\Local\atom\app-1.2.4\resources\app.asar\src\buffered-process.js:213:47)
    at ChildProcess.<anonymous> (C:\Users\Socks\AppData\Local\atom\app-1.2.4\resources\app.asar\src\buffered-process.js:235:18)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12) Failed to install terminal-plus because Git was not found.

The terminal-plus package has module dependencies that cannot be installed without Git.

You need to install Git and add it to your path environment variable in order to install this package.```

Cheers, and thanks for un-dullifying the Windows terminal experience!

**Comment by jeremyramin** [comment]
Yes, the Terminal-Plus installation relies on the system having git installed for a git clone of the dependency repositories.

That item in the todo list is me considering bringing the dependencies into this repository to fix this issue. However, there are some unwanted side effects with that decision which prevent me from doing that. Either way thank you for pointing out that this silently fails without git. I'll have to think of some other way to fix this. You are welcome, thank you for using Terminal-Plus.
