### ISSUE TITLE
Uncaught Error: Cannot find module 'C:\Users\ScreenMagic\.atom\packages\terminal-plus\lib\process...

### ISSUE THREAD

**Issue by muditsaurabh** [jeremyramin/terminal-plus#140]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.3.2
**System**: Microsoft Windows 10 Home Single Language
**Thrown From**: [terminal-plus](https://github.com/jeremyramin/terminal-plus) package, v0.14.5

### Stack Trace

Uncaught Error: Cannot find module 'C:\Users\ScreenMagic\.atom\packages\terminal-plus\lib\process.coffee'

```
At module.js:338

Error: Cannot find module 'C:\Users\ScreenMagic\.atom\packages\terminal-plus\lib\process.coffee'
    at Module._resolveFilename (module.js:336:15)
    at Function.Module._resolveFilename (C:\Users\ScreenMagic\AppData\Local\atom\app-1.3.2\resources\app.asar\src\module-cache.js:383:52)
    at Function.require.resolve (C:\Users\ScreenMagic\AppData\Local\atom\app-1.3.2\resources\app.asar\src\native-compile-cache.js:53:23)
    at new Task (C:\Users\ScreenMagic\AppData\Local\atom\app-1.3.2\resources\app.asar\src\task.js:35:26)
    at Function.module.exports.Task.once (C:\Users\ScreenMagic\AppData\Local\atom\app-1.3.2\resources\app.asar\src\task.js:17:14)
    at TerminalPlusView.module.exports.TerminalPlusView.forkPtyProcess (C:\Users\ScreenMagic\.atom\packages\terminal-plus\lib\view.coffee:229:19)
    at TerminalPlusView.module.exports.TerminalPlusView.displayTerminal (C:\Users\ScreenMagic\.atom\packages\terminal-plus\lib\view.coffee:244:30)
    at C:\Users\ScreenMagic\.atom\packages\terminal-plus\lib\view.coffee:389:19
    at HTMLDivElement.<anonymous> (C:\Users\ScreenMagic\.atom\packages\terminal-plus\lib\view.coffee:705:11)
    at HTMLDivElement.fn (C:\Users\ScreenMagic\AppData\Local\atom\app-1.3.2\resources\app.asar\node_modules\jquery\dist\jquery.js:4855:19)
    at HTMLDivElement.jQuery.event.dispatch (C:\Users\ScreenMagic\AppData\Local\atom\app-1.3.2\resources\app.asar\node_modules\jquery\dist\jquery.js:4435:9)
    at HTMLDivElement.elemData.handle (C:\Users\ScreenMagic\AppData\Local\atom\app-1.3.2\resources\app.asar\node_modules\jquery\dist\jquery.js:4121:28)
```

### Commands

```
     -5:42.3.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -2:08.5.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -2:05.4.0 tree-view:add-file (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
```

### Config

```json
{
  "core": {},
  "terminal-plus": {
    "core": {},
    "style": {}
  }
}
```

### Installed Packages

```coffee
# User
terminal-plus, vundefined

# Dev
No dev packages
```

**Comment by jeremyramin** [comment]
I think you experienced an error during installation because that file should exist. Your installed version also seems to be undefined. Please try to uninstall and then reinstall Terminal-Plus.

**Comment by muditsaurabh** [comment]
I was facing this error on window but on my Mac it is working. I will try
it once more.
