### ISSUE TITLE
Installing “terminal-plus@0.14.5” failed.

### ISSUE THREAD

**Issue by ncostis** [jeremyramin/terminal-plus#166]
Hello

I am trying to install terminal-plus in my ubuntu and it fails.

I get 

> pty.js@0.3.0 install /tmp/apm-install-dir-116027-13246-17vapdo/node_modules/terminal-plus/node_modules/pty.js
> (node-gyp rebuild 2> builderror.log) || (exit 0)

> pty.js@0.3.0 postinstall /tmp/apm-install-dir-116027-13246-17vapdo/node_modules/terminal-plus/node_modules/pty.js
> node scripts/post-install.js

module.js:340
    throw err;
          ^
Error: Cannot find module '/tmp/apm-install-dir-116027-13246-17vapdo/node_modules/terminal-plus/node_modules/pty.js/scripts/post-install.js'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:935:3
npm ERR! Linux 4.2.0-25-generic
npm ERR! argv "/usr/share/atom/resources/app/apm/bin/node" "/usr/share/atom/resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/home/ncostis/.atom/.apm/.apmrc" "--userconfig" "/home/ncostis/.atom/.apmrc" "install" "/tmp/d-116027-13246-sn3oor/package.tgz" "--target=0.34.5" "--arch=x64"
npm ERR! node v0.10.40
npm ERR! npm  v2.13.3
npm ERR! code ELIFECYCLE

npm ERR! pty.js@0.3.0 postinstall: `node scripts/post-install.js`
npm ERR! Exit status 8
npm ERR! 
npm ERR! Failed at the pty.js@0.3.0 postinstall script 'node scripts/post-install.js'.
npm ERR! This is most likely a problem with the pty.js package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/post-install.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls pty.js
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /tmp/apm-install-dir-116027-13246-17vapdo/npm-debug.log

how can i do it?

**Comment by bimalgrg519** [comment]
same issue :(
