### ISSUE TITLE
Can't open terminal plus in Materail theme UI --  Uncaught TypeError: Cannot read property 'element' of undefined

### ISSUE THREAD

**Issue by songhuagao** [jeremyramin/terminal-plus#189]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.5.3
**System**: Ubuntu 15.10
**Thrown From**: [terminal-plus](https://github.com/jeremyramin/terminal-plus) package, v0.14.5

### Stack Trace

Uncaught TypeError: Cannot read property 'element' of undefined

```
At /home/justin/.atom/git/terminal-plus/lib/view.coffee:394

TypeError: Cannot read property 'element' of undefined
    at TerminalPlusView.module.exports.TerminalPlusView.adjustHeight (/home/justin/.atom/git/terminal-plus/lib/view.coffee:394:16)
    at TerminalPlusView.module.exports.TerminalPlusView.maximize (/home/justin/.atom/git/terminal-plus/lib/view.coffee:194:8)
    at HTMLButtonElement.<anonymous> (/home/justin/.atom/git/terminal-plus/node_modules/atom-space-pen-views/node_modules/space-pen/lib/space-pen.js:220:36)
    at HTMLButtonElement.jQuery.event.dispatch (/home/justin/.atom/git/terminal-plus/node_modules/atom-space-pen-views/node_modules/space-pen/node_modules/jquery/dist/jquery.js:4435:9)
    at HTMLButtonElement.elemData.handle (/home/justin/.atom/git/terminal-plus/node_modules/atom-space-pen-views/node_modules/space-pen/node_modules/jquery/dist/jquery.js:4121:28)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "autoHideMenuBar": true,
    "disabledPackages": [
      "language-clojure",
      "language-coffee-script",
      "language-csharp",
      "language-mustache",
      "open-on-github",
      "vim-mode",
      "metrics",
      "language-ruby-on-rails",
      "seti-icons",
      "pigments"
    ],
    "ignoredNames": [
      ".idea",
      "*.pyc",
      ".git"
    ],
    "projectHome": "/home/justin/Project",
    "themes": [
      "atom-material-ui",
      "atom-material-syntax"
    ]
  },
  "terminal-plus": {
    "ansiColors": {
      "normal": {
        "blue": {
          "red": 27,
          "green": 27,
          "blue": 168,
          "alpha": 1
        }
      },
      "zBright": {
        "brightBlue": {
          "red": 0,
          "green": 0,
          "blue": 250,
          "alpha": 1
        }
      }
    },
    "core": {},
    "style": {
      "theme": "ocean"
    }
  }
}
```

### Installed Packages

```coffee
# User
atom-jinja2, v0.5.0
atom-material-syntax, v0.3.3
atom-material-ui, v1.2.0
autocomplete-python, v1.7.0
file-icons, v1.6.14
linter, v1.11.3
linter-pep8, v1.2.1
minimap, v4.19.0
pretty-json, v0.4.1
project-manager, v2.7.6
terminal-plus, v0.14.5

# Dev
No dev packages
```

**Comment by idoo** [comment]
Its work for me now  Atom `1.9`
