### ISSUE TITLE
Terminal not working in Atom 1.7beta

### ISSUE THREAD

**Issue by ShMcK** [jeremyramin/terminal-plus#201]
Opening terminal-plus in Atom 1.7beta results in an empty terminal. Typing has no effect.
OS: Mac 10.11.13

<img width="382" alt="screen shot 2016-03-18 at 10 45 05 am" src="https://cloud.githubusercontent.com/assets/4660659/13886915/830dd34e-ecf6-11e5-85c3-ebdd243e51a4.png">

**Comment by atomi** [comment]
```
terminal-plus 0.14.5

pty.js@0.3.0 – Module version mismatch. Expected 47, got 46.
pty.js@0.3.0 – Module version mismatch. Expected 47, got 46.
pty.js@0.3.0 – Module version mismatch. Expected 47, got 46.
pty.js@0.3.0 – Module version mismatch. Expected 47, got 46.
pty.js@0.3.0 – Module version mismatch. Expected 47, got 46.
pty.js@0.3.0 – Module version mismatch. Expected 47, got 46.
pty.js@0.3.0 – Module version mismatch. Expected 47, got 46.
```

**Comment by ShMcK** [comment]
@atomi: Your issue seems to be related to the *Chrome* version wanted by *Electron*. 

You might be able to fix that in terminal by running:

    apm rebuild terminal-plus

If that doesn't work, try removing *terminal-plus* and re-installing.

**Comment by atomi** [comment]
@ShMcK Rebuilding did the trick. Thanks!

**Comment by tomByrer** [comment]
On OSX, removing & re-installing didn't work, & `apm` can't be found even after adding shell commands in Atom. (unless I have to reboot after?)

**Comment by dpavlic** [comment]
I'm afraid that: `apm-beta rebuild terminal-plus` does not fix this for me on Ubuntu 15.10 or Arch.

**Comment by raptor235** [comment]
Confirmed same here, no luck with the rebuild, I can't even uninstall terminal-plus... getting

Failed to delete terminal-plus: Does not exist
Community Packages1/22
0.14.566,176
terminal-plus A terminal package for Atom, complete with themes and more.
jeremyramin
SettingsUninstallDisable
Core Packages0/77
Development Packages0/0
Git Packages0/0

So can't use it and can't delete it atm

**Comment by opensourceportfolio** [comment]
I am experiencing the same issue.

to remove it I ran install again first. Then I was able to uninstall.

**Comment by elebumm** [comment]
I am getting the same issue. 
![screen shot 2016-04-02 at 1 57 59 am](https://cloud.githubusercontent.com/assets/6053155/14224776/5f547cba-f876-11e5-9071-ddfc6978b6f7.png)

I am using atom 1.7 beta on Mac OS X . I have rebuilt, uninstalled and reinstalled and all haven't worked.

**Comment by Hazerdous** [comment]
I am having the same issue. Rebuilding, reinstalling, and even reinstalling Atom have not worked.
I am using v1.7.0-beta4 on Windows 10 
Here is the output of the console when I attempt to open the terminal.

WARN: `Cannot find module '../build/Release/pty.node'`

ERRORS:

    Module version mismatch. Expected 47, got 46. Error: Module version mismatch. Expected 47, got 46.
        at Error (native)
        at process.module.(anonymous function) [as dlopen] (ATOM_SHELL_ASAR.js:159:20)
        at Object.Module._extensions..node (module.js:450:18)
        at Object.module.(anonymous function) [as .node] (ATOM_SHELL_ASAR.js:159:20)
        at Module.load (module.js:356:32)
        at Function.Module._load (module.js:313:12)
        at Module.require (module.js:366:17)
        at require (module.js:385:17)
        at Object.<anonymous> (C:\Users\daniel\.atom\packages\terminal-plus\node_modules\pty.js\lib\pty.js:17:9)
        at Module._compile (module.js:425:26)
        at Object.defineProperty.value [as .js] (C:\Users\daniel\AppData\Local\atom\app-1.7.0-beta4\resources\app.asar\src\compile-cache.js:208:21)
        at Module.load (module.js:356:32)
        at Function.Module._load (module.js:313:12)
        at Module.require (module.js:366:17)
        at require (module.js:385:17)
        at Object.<anonymous> (C:\Users\daniel\.atom\packages\terminal-plus\node_modules\pty.js\lib\pty_win.js:10:20)
        at Module._compile (module.js:425:26)
        at Object.defineProperty.value [as .js] (C:\Users\daniel\AppData\Local\atom\app-1.7.0-beta4\resources\app.asar\src\compile-cache.js:208:21)
        at Module.load (module.js:356:32)
        at Function.Module._load (module.js:313:12)
        at Module.require (module.js:366:17)
        at require (module.js:385:17)
        at Object.<anonymous> (C:\Users\daniel\.atom\packages\terminal-plus\node_modules\pty.js\index.js:2:18)
        at Module._compile (module.js:425:26)
        at Object.defineProperty.value [as .js] (C:\Users\daniel\AppData\Local\atom\app-1.7.0-beta4\resources\app.asar\src\compile-cache.js:208:21)
        at Module.load (module.js:356:32)
        at Function.Module._load (module.js:313:12)
        at Module.require (module.js:366:17)
        at require (module.js:385:17)
        at Object.<anonymous> (file:///C:/Users/daniel/.atom/packages/terminal-plus/lib/process.coffee:1:7)

    Cannot read property 'bind' of null TypeError: Cannot read property 'bind' of null
        at process.<anonymous> (C:\Users\daniel\AppData\Local\atom\app-1.7.0-beta4\resources\app.asar\src\task-bootstrap.js:82:23)
        at emitTwo (events.js:87:13)
        at process.emit (events.js:172:7)
        at handleMessage (internal/child_process.js:686:10)
        at Pipe.channel.onread (internal/child_process.js:440:11)

**Comment by voliva** [comment]
I managed to make it work. It looks like a pty.js dependency is outdated.
In my case, I went to terminal-plus folder (In my computer is `/Users/victor/.atom/packages/terminal-plus`), removed node-modules folder and did `npm install`. Now it works again.
However, I don't understand why... I tried rebuilding, uninstalling & installing the plugin again and it didn't work... Shouldn't this steps reset the node-modules folder?

**Comment by Nemesis9765** [comment]
Running into the same problem myself as reported in issue #209 .  Tried what @voliva mentioned, removed my node_modules from the terminal-plus package dir, ran npm install and apm-beta rebuild terminal-plus for safe measure but still won't work for me.

**Comment by voliva** [comment]
@Nemesis9765 Did you look at the console output? Maybe we have some hint in there.
In my case I had the same error as @Hazerdous, and I could trace the source of the problem from there.
To show the console, in Mac you use Cmd+Alt+i and then open a terminal for the error to show up... In other systems try the shortcut to open Chrome's dev console.

**Comment by Nemesis9765** [comment]
@voliva, i have the same issue as others about the expected version issue,

```
Module version mismatch. Expected 47, got 46. Error: Module version mismatch. Expected 47, got 46.
    at Error (native)
    at process.module.(anonymous function) [as dlopen] (ATOM_SHELL_ASAR.js:159:20)
    at Object.Module._extensions..node (module.js:450:18)
    at Object.module.(anonymous function) [as .node] (ATOM_SHELL_ASAR.js:159:20)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/Users/fedorr/.atom/packages/terminal-plus/node_modules/pty.js/lib/pty.js:17:9)
...
```

**Comment by paglias** [comment]
Same problem here

**Comment by elistone** [comment]
Version 1.7.0 has now been rolled out from BETA, now will be broken by everyone who updates to latest atom version.

**Comment by sgal** [comment]
I just installed fresh stable Atom 1.7.0 and it is broken. Tried `apm rebuild terminal-plus` and `npm install` in package folder - nothing works.

**Comment by 17100148** [comment]
having same problem here. Was really enjoying the package.

**Comment by 17100148** [comment]
it deleted the node_modules folder from terminal-plus folder and ran npm install. It says: MSBUILD : error MSB3428: Could not load the Visual C++ component "VCBuild.exe". To fix this, 1) install the .NET Framework 2.0 SDK, 2) install Microsoft Visual Studio
2005 or 3) add the location of the component to the system path if it is installed elsewhere.

**Comment by ivankravets** [comment]
Friends,

Please take a look at PlatformIO fork https://github.com/platformio/platformio-atom-ide-terminal

We forked this repo a few months ago and support it. Also, we have just released a new version which works with Atom 1.6/1.7.

**Comment by 17100148** [comment]
@ivankravets Thankyou very much.

**Comment by spryce** [comment]
Same problem here. After trying all of the above I managed to reinstall after deleting terminal-plus from the .apm directory, but still no good.

Going to try the PlatformIO fork from @ivankravets

**Comment by primAulia** [comment]
Updated my atom to version 1.7.1 tried to delete the node modules and npm i on the package folder. Not working.

Tried to run ```apm rebuild terminal-plus``` also not working. Is this atom version issue?

**Comment by 17100148** [comment]
@ivankravets could you please fix the following in your package?
1) Place the close all icon away from the opened windows
2) The terminal won't start until I open a folder in atom. Let it start even if not folder has been opened.
3) When I adjust the height of one terminal, all other opened instances should update their height

These things had been addressed in the original terminal-plus and I am missing them in your fork.

**Comment by ivankravets** [comment]
@17100148 please open an issue here https://github.com/platformio/platformio-atom-ide-terminal/issues

**Comment by 17100148** [comment]
Still not working with Atom 1.7.2.

**Comment by Nemesis9765** [comment]
So should this package be marked as abandoned and I move onto this other terminal package?  Been nearly a month and no movement on this.

**Comment by luizfox** [comment]
I gave up. Tried PlatformIO and it works like a charm. 
sorry terminal-plus. it was good while it lasted.

**Comment by yamazee** [comment]
Same problem here!

**Comment by xmniko** [comment]
Same problem in Atom 1.8.0. I also gave up.

**Comment by johnwaweru** [comment]
I faced this very issue and decided to try the other forks only to be disappointed. The only one that stood out and saved me from headaches was platformio-ide-terminal. I wish I'd known earlier because terminal-plus just stopped working and I tried almost everything I could find to fix it but I just doesn't work. Thank you so much @ivankravets

**Comment by atomi** [comment]
Switched to Ubuntu Xenial and this plugin stopped working. Exact same situation.

**Comment by farshidtz** [comment]
Same problem on Atom 1.8.0. Non of the suggested solutions worked. Switched to platformio-atom-ide-terminal.

**Comment by marcelombc** [comment]
Goodbye terminal-plus. Hello platformio-atom-ide-terminal.

**Comment by gamesun** [comment]
Same problem on Atom 1.9.2, Ubuntu 16.04 LTS 64bits.

**Comment by luhtonen** [comment]
I have same problem with terminal-plus on Atom 1.9.8, Mac OS X 10.11.6
Since this wasn't fixed for almost 5 months I'll uninstall this plugin and will try some other.

**Comment by schaden-freude** [comment]
Same problem on Atom 1.9.6, Ubuntu 16.04 64-bit.

**Comment by amalfra** [comment]
Me too facing same problem on Atom 1.9.8, Ubuntu 16.04 64-bit.

**Comment by Scimonster** [comment]
Atom 1.9.9, Ubuntu 16.04 64bit.
Tried rebuilding and the `npm install` trick but no luck

**Comment by rikapo** [comment]
Same problem on Atom 1.9.9, Nuclide 0.163.0, Ubuntu 16.04 64bit.
Rebuilding and reinstalling not worked too.

**Comment by JLCCI** [comment]
More and more packages break with updates and are no longer maintained.. Gonna look for alternatives.

**Comment by gamesun** [comment]
have a try at platformio-atom-ide-terminal, it works fine for me.

**Comment by laike9m** [comment]
Confirmed on version 1.10.0, OS X.

**Comment by mnlcandelaria** [comment]
fork of terminal-plus https://atom.io/packages/platformio-ide-terminal

**Comment by wiwiwa** [comment]
Confirmed on atom v1.10 on MacOS.

fixed with method of @voliva

**Comment by JLCCI** [comment]
Thanks for the suggestion to try Platformio but for me it does not work (exactly same issue as here) and I don't like that they moved stuff in the status bar.

Hopefully the original author will return or pass the repository to someone who can maintain it and incorporate the pull requests. This is by far the most popular terminal app in Atom.

**Comment by kasunvp** [comment]
Same problem persists on Linux Mint 18 (Sarah) and Atom 1.9.9
So going to try the alternative https://atom.io/packages/platformio-ide-terminal

**Comment by ihac** [comment]
Does not work on Mint 17.2 + Atom 1.10.2 neither.

**Comment by jackiewell** [comment]
same here

**Comment by shahmir811** [comment]
same problem in atom 1.10.2 on win7

**Comment by ybing** [comment]
goodbye terminal-plus

**Comment by ramz225** [comment]
whats up any fix?

**Comment by asha23** [comment]
Yep still broken on 1.10.2 

:(

Shame, as it was a great addition.

**Comment by siddharthbulia** [comment]
Going with platformio-atom-ide-terminal . Thanks @ivankravets

**Comment by nixawk** [comment]
platformio-atom-ide-terminal goes well. 

<img width="847" alt="platformio-atom-ide-terminal" src="https://cloud.githubusercontent.com/assets/7352479/18735102/d7a53f68-8040-11e6-9fff-533bf84b10ca.png">

**Comment by avatsaev** [comment]
shit isn working yo

**Comment by MarcusWasTaken** [comment]
The most likely fix was posted in another issue by user @codevinsky
https://github.com/jeremyramin/terminal-plus/issues/321#issuecomment-242193432

**Comment by shoedog** [comment]
I have tried apm rebuild, uninstalling and reinstalling on my mac running El Capitan. I will just use a different terminal option.

**Comment by pganeshGapps** [comment]
Bye-bye Terminal plus, use 
Same problem as just opens terminal, no commands are read on it,on Linux Ubuntu 16.04 and Atom -v:
Atom    : 1.9.9
Electron: 0.37.8
Chrome  : 49.0.2623.75
Node    : 5.10.0

**Comment by georgealton** [comment]
I have the same issue 

osx 10.12
atom 1.11.2
terminal-plus 0.14.5

![terminal-plus-terminal-not-working-issue](https://cloud.githubusercontent.com/assets/1202151/19724653/5c9031e4-9b79-11e6-92bd-d48582c52b3d.png)

**Comment by mythical-programmer** [comment]
platform io ide terminal is the way to go.

**Comment by Kutsan** [comment]
After months still have same issue. Shame on you guys.

**Comment by sclausen** [comment]
It would be so great if this gets fixed.

**Comment by Kutsan** [comment]
FIY https://atom.io/packages/tokamak-terminal works great.

**Comment by avatsaev** [comment]
> FIY https://atom.io/packages/tokamak-terminal works great.

not with the latest version of atom it doesn't

**Comment by Kutsan** [comment]
@avatsaev That's my bad luck. I created this issue, thumbs up: https://github.com/vertexclique/tokamak-terminal/issues/10

**Comment by avatsaev** [comment]
ok but it doesn't matter anymore, just installed platform-io-ide-terminal, seems to work fine

**Comment by ronthedrummer** [comment]
Same issue.  Guessing this package is no longer maintained.

**Comment by vasiliy0s** [comment]
The problem is with `pty.js` on bulding this module (_recipe for target ... failed_):

```
~/.atom/packages/terminal-plus$ npm i pty.js

> pty.js@0.3.0 install /home/vasiliy0s/.atom/packages/terminal-plus/node_modules/pty.js
> (node-gyp rebuild 2> builderror.log) || (exit 0)

make: вход в каталог «/home/vasiliy0s/.atom/packages/terminal-plus/node_modules/pty.js/build»
  CXX(target) Release/obj.target/pty/src/unix/pty.o
pty.target.mk:88: ошибка выполнения рецепта для цели «Release/obj.target/pty/src/unix/pty.o»
make: выход из каталога «/home/vasiliy0s/.atom/packages/terminal-plus/node_modules/pty.js/build»

> pty.js@0.3.0 postinstall /home/vasiliy0s/.atom/packages/terminal-plus/node_modules/pty.js
> node scripts/post-install.js
```

After it, the `lib/pty.js` cannot require _nothing_ .node file and fail on terminal opening.

**Comment by vasiliy0s** [comment]
This problem happend for me after upgrading to Atom 1.12. I find solution in https://github.com/vertexclique/tokamak-terminal/issues/10#issuecomment-259943572 and it works for `terminal-plus` too. It uses **pre-build** `pty.js` and it should work for anymore.

**Comment by ataraxus** [comment]
its also broken for me, ubunut 16.04 atom 1.12 
kudos @ivankravets your fork does the job

**Comment by ivankravets** [comment]
Dear Participants,

Next time when you have problems with Terminal, please do the next steps:
1. Install https://github.com/platformio/platformio-atom-ide-terminal
2. If step No.1 don't help, please go to step No.3
3. Install `gcc` (Unix) or MS VS Studio (Windows)
4. Go to Atom Settigs ( ⚙ ) > Packages and UNINSTALL `platformio-ide-terminal`. Close Atom.
5. Start Atom and install `platformio-ide-terminal` again.

We have pre-built PTY binaries for the most popular OSs. Howerver, if you use specific Linux distribution that depends on own Atom/node.js/nan, you need to have native PTY binary. 

---

Each time when you install `platformio-ide-terminal` from a scratch, installer does the next job:
1. Looks for compiler on the host machine.
2. Tries to build native PTY module using system compiler (should be visible in the `$PATH`/`%(Path)`)
3. Atom initializes `platformio-ide-terminal` which tries to load PTY module "on-the-fly" and `platformio-ide-terminal` looks for native binary (if it was successfully compiled, see step No.2 above), and only at the end it looks for pre-built binaries by @PlatformIO Team. 

The our latest binaries should work in 99%. The only one exclusion is specific Linux distributive. Current Linux binary is compiled for Ubuntu x86_64.

Regards, Ivan.

**Comment by bitclaw** [comment]
Installing platformio-ide-terminal and uninstalling terminal-plus worked for me :+1:

**Comment by AlessandroMinoccheri** [comment]
Uninstalled terminal-plus, installed platformio-ide-terminal and now works like a charm!
Thanks

**Comment by ryankazokas** [comment]
Same issue. 
platformio-ide-terminal worked for me as well

**Comment by RTJ** [comment]
Same issue.
**platformio-ide-terminal** is working for me.

**Comment by wsfuller** [comment]
Same issue with package being installed and empty prompt with inability to type anything on MacOS 10.12.3 Atom 1.13.1 x64.

uninstalled terminal-plus, **platformio-ide-terminal** installed and is working as expected

**Comment by PabloEzequiel** [comment]
I also uninstalled terminal-plus,
And I installed the other plugin platformio-ide-terminal and is working ... this is a fork of terminal plus and it works ok ...

**Comment by eni23** [comment]
Same issue on Archlinux with Atom 1.14 from the `Community`-Repo. It worked fine with `atom-git` from AUR, but this was always a pain to update.
I uninstalled `terminal-plus`, and `platformio-ide-terminal` seems to works fine

**Comment by vitt82** [comment]
platformio-ide-terminal is working for me.

**Comment by HauntedSmores** [comment]
Bump for same issue. Blank terminal

**Comment by SecondeJK** [comment]
I have switched to the platformio-ide-terminal fork of this which works. This package does not work (OSX 10.11). This problem is over a year old, I'd recommend either maintaining it or asking what they did on that fork and merge it in

**Comment by prudhvirajmudunuri** [comment]
platformio-ide-terminal works!!! I am using ubuntu 16.04

**Comment by besopmac** [comment]
Just install the **platformio-ide-terminal**, guys. It works.

**Comment by internalfx** [comment]
Switched to Termination... Works great.

https://github.com/Fred-Barclay/Termination

**Comment by abhishekK50** [comment]
Uninstalling and installing it again worked for me.
