### ISSUE TITLE
windows10 atom1.7 error

### ISSUE THREAD

**Issue by yalishizhude** [jeremyramin/terminal-plus#213]
Module version mismatch. Expected 47, got 46. Error: Module version mismatch. Expected 47, got 46.
    at Error (native)
    at process.module.(anonymous function) [as dlopen] (ATOM_SHELL_ASAR.js:159:20)
    at Object.Module._extensions..node (module.js:450:18)
    at Object.module.(anonymous function) [as .node] (ATOM_SHELL_ASAR.js:159:20)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (C:\Users\Administrator\.atom\packages\terminal-plus\node_modules\pty.js\lib\pty.js:17:9)
    at Module._compile (module.js:425:26)
    at Object.defineProperty.value [as .js] (C:\Users\Administrator\AppData\Local\atom\app-1.7.0\resources\app.asar\src\compile-cache.js:208:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (C:\Users\Administrator\.atom\packages\terminal-plus\node_modules\pty.js\lib\pty_win.js:10:20)
    at Module._compile (module.js:425:26)
    at Object.defineProperty.value [as .js] (C:\Users\Administrator\AppData\Local\atom\app-1.7.0\resources\app.asar\src\compile-cache.js:208:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (C:\Users\Administrator\.atom\packages\terminal-plus\node_modules\pty.js\index.js:2:18)
    at Module._compile (module.js:425:26)
    at Object.defineProperty.value [as .js] (C:\Users\Administrator\AppData\Local\atom\app-1.7.0\resources\app.asar\src\compile-cache.js:208:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (file:///C:/Users/Administrator/.atom/packages/terminal-plus/lib/process.coffee:1:7)(anonymous function) @ C:\Users\Administrator\AppData\Local\atom\app-1.7.0\resources\app.asar\src\task.js:52(anonymous function) @ C:\Users\Administrator\AppData\Local\atom\app-1.7.0\resources\app.asar\src\task.js:126module.exports.Emitter.simpleDispatch @ C:\Users\Administrator\AppData\Local\atom\app-1.7.0\resources\app.asar\node_modules\event-kit\lib\e…:25module.exports.Emitter.emit @ C:\Users\Administrator\AppData\Local\atom\app-1.7.0\resources\app.asar\node_modules\event-kit\lib\e…:125(anonymous function) @ C:\Users\Administrator\AppData\Local\atom\app-1.7.0\resources\app.asar\src\task.js:78emitTwo @ events.js:87emit @ events.js:172handleMessage @ internal/child_process.js:686channel.onread @ internal/child_process.js:440
2C:\Users\Administrator\AppData\Local\atom\app-1.7.0\resources\app.asar\src\task.js:52 Cannot read property 'bind' of null TypeError: Cannot read property 'bind' of null
    at process.<anonymous> (C:\Users\Administrator\AppData\Local\atom\app-1.7.0\resources\app.asar\src\task-bootstrap.js:82:23)
    at emitTwo (events.js:87:13)
    at process.emit (events.js:172:7)
    at handleMessage (internal/child_process.js:686:10)
    at Pipe.channel.onread (internal/child_process.js:440:11)

**Comment by ryedin** [comment]
+1 (Mac)

**Comment by ryedin** [comment]
I figured out how to fix it. 

1. In the lower-right corner of Atom, I had a red "issues" or "bugs" indicator, which I clicked to reveal a pane I had never seen before: "Incompatible Packages"
2. From there, I was able to click a button "Rebuild Packages"
3. Once complete, I had to close and re-start Atom

I'm sure this is just a workaround until the author can publish a new version, but I'm happy (hope this helps someone else)

**Comment by benwalks** [comment]
If your rebuild fails the first time on your mac, restart Atom and try again.  It should work afterwards.

**Comment by ivankravets** [comment]
Please take a look at PlatformIO fork https://github.com/platformio/platformio-atom-ide-terminal
