### ISSUE TITLE
Some installed packages could not be loaded because they contain native modules that were compiled for an earlier version of Atom.

### ISSUE THREAD

**Issue by xiaopengguo** [jeremyramin/terminal-plus#226]
gyp info it worked if it ends with ok
gyp info using node-gyp@2.0.2
gyp info using node@0.10.40 | darwin | x64
gyp http GET https://atom.io/download/atom-shell/v0.36.8/node-v0.36.8.tar.gz
gyp http 404 https://atom.io/download/atom-shell/v0.36.8/node-v0.36.8.tar.gz
gyp WARN install got an error, rolling back install
gyp ERR! install error 
gyp ERR! stack Error: 404 response downloading https://atom.io/download/atom-shell/v0.36.8/node-v0.36.8.tar.gz
gyp ERR! stack     at Request.<anonymous> (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/node-gyp/lib/install.js:251:14)
gyp ERR! stack     at Request.emit (events.js:117:20)
gyp ERR! stack     at Request.onRequestResponse (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/request/request.js:992:10)
gyp ERR! stack     at ClientRequest.emit (events.js:95:17)
gyp ERR! stack     at HTTPParser.parserOnIncomingClient (http.js:1689:21)
gyp ERR! stack     at HTTPParser.parserOnHeadersComplete [as onHeadersComplete] (http.js:122:23)
gyp ERR! stack     at Socket.socketOnData (http.js:1584:20)
gyp ERR! stack     at TCP.onread (net.js:528:27)
gyp ERR! System Darwin 15.3.0
gyp ERR! command "/Applications/Atom.app/Contents/Resources/app/apm/bin/node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "install" "--target=0.36.8" "--dist-url=https://atom.io/download/atom-shell" "--arch=x64" "--ensure"
gyp ERR! cwd /Users/Parry/.atom
gyp ERR! node -v v0.10.40
gyp ERR! node-gyp -v v2.0.2
gyp ERR! not ok

**Comment by freqn** [comment]
Same issue here
