### ISSUE TITLE
Sending EOF to terminal does not close it

### ISSUE THREAD

**Issue by tomzas** [jeremyramin/terminal-plus#228]
Sending EOF with Ctrl+D does not close the terminal and leaves it in unusable state. Manual close operation required.

Atom version: 1.7.1
terminal-plus version: 0.14.5

Steps to reproduce
- open terminal window/panel
- focus on terminal panel
- hit Ctrl+D on keyboard

Steps to recover:
- right click on terminal panel
- choose Close

**Comment by skull-squadron** [comment]
It's even worse now.

Uncloseable zombie terminals remain forever, and not just on Halloween.

```
Uncaught TypeError: Cannot read property 'terminate' of null
{{~}}/.atom/packages/terminal-plus/lib/shell.coffee:47
Hide Stack Trace
TypeError: Cannot read property 'terminate' of null
    at Shell.module.exports.Shell.terminate ({{~}}/.atom/packages/terminal-plus/lib/shell.coffee:47:10)
    at Shell.module.exports.Shell.destroy ({{~}}/.atom/packages/terminal-plus/lib/shell.coffee:25:6)
    at Terminal.module.exports.Terminal.destroy ({{~}}/.atom/packages/terminal-plus/lib/terminal.coffee:62:12)
    at PanelView.module.exports.TerminalView.destroy ({{~}}/.atom/packages/terminal-plus/lib/terminal-view.coffee:32:15)
    at PanelView.module.exports.PanelView.destroy ({{~}}/.atom/packages/terminal-plus/lib/panel-view.coffee:45:5)
    at PanelView.destroy ({{~}}/.atom/packages/terminal-plus/lib/panel-view.coffee:1:1)
    at HTMLDivElement.terminal-plus:context-close ({{~}}/.atom/packages/terminal-plus/lib/status-bar.coffee:63:49)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom-Beta.app/Contents/Resources/app.asar/src/command-registry.js:259:29)
    at CommandRegistry.handleCommandEvent (/Applications/Atom-Beta.app/Contents/Resources/app.asar/src/command-registry.js:3:59)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/Applications/Atom-Beta.app/Contents/Resources/app.asar/src/command-registry.js:160:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchContextMenuCommand (/Applications/Atom-Beta.app/Contents/Resources/app.asar/src/atom-environment.js:1132:28)
    at EventEmitter.outerCallback (/Applications/Atom-Beta.app/Contents/Resources/app.asar/src/application-delegate.js:332:25)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
```
