### ISSUE TITLE
Uncaught TypeError: path.dirname is not a function

### ISSUE THREAD

**Issue by daraz999** [jeremyramin/terminal-plus#23]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.19
**System**: Mac OS X 10.11
**Thrown From**: [terminal-plus](https://github.com/jeremyramin/terminal-plus) package, v0.6.1

### Stack Trace

Uncaught TypeError: path.dirname is not a function

```
At /Users/darius/.atom/packages/terminal-plus/lib/view.coffee:81

TypeError: path.dirname is not a function
  at TerminalPlusView.module.exports.TerminalPlusView.forkPtyProcess (/Users/darius/.atom/packages/terminal-plus/lib/view.coffee:81:23)
  at TerminalPlusView.module.exports.TerminalPlusView.displayTerminal (/Users/darius/.atom/packages/terminal-plus/lib/view.coffee:96:20)
  at /Users/darius/.atom/packages/terminal-plus/lib/view.coffee:185:10
  at HTMLDivElement.<anonymous> (/Users/darius/.atom/packages/terminal-plus/lib/view.coffee:376:7)
  at HTMLDivElement.fn (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4855:19)
  at HTMLDivElement.jQuery.event.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4435:9)
  at HTMLDivElement.elemData.handle (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4121:28)

```

### Commands

```
     -5:44.5.0 core:move-down (atom-text-editor.editor.is-focused)
     -5:44.1.0 snippets:next-tab-stop (atom-text-editor.editor.is-focused)
     -5:44.1.0 snippets:expand (atom-text-editor.editor.is-focused)
     -5:44.1.0 editor:indent (atom-text-editor.editor.is-focused)
     -5:43.9.0 core:move-down (atom-text-editor.editor.is-focused)
     -5:43.4.0 core:move-up (atom-text-editor.editor.is-focused)
     -5:43.2.0 core:move-down (atom-text-editor.editor.is-focused)
     -5:42.4.0 core:move-right (atom-text-editor.editor.is-focused)
     -5:41.9.0 core:move-left (atom-text-editor.editor.is-focused)
  2x -5:40.4.0 core:backspace (atom-text-editor.editor.is-focused)
  2x -5:39 core:save (atom-text-editor.editor.is-focused)
     -5:33.1.0 terminal-plus:new (atom-text-editor.editor.is-focused)
     -4:11 line-ending-selector:show (atom-text-editor.editor.is-focused)
     -4:09.5.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -4:09.5.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -0:02.8.0 terminal-plus:new (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "excludeVcsIgnoredPaths": false
  },
  "terminal-plus": {
    "core": {},
    "style": {},
    "toggles": {
      "autoClose": true,
      "cursorBlink": false
    }
  }
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.28.14
terminal-plus, v0.6.1

# Dev
No dev packages
```

**Comment by jeremyramin** [comment]
I just released an update (v0.6.2) for this issue. If it happens again, please let me know.

**Comment by jeremyramin** [comment]
Since no replies have been made for seven days, I think it is safe to assume that this has been fixed. Thank you for your report.

**Comment by abdulbahajaj** [comment]
Happened again ? 

    TypeError: path.dirname is not a function
    at TerminalPlusView.module.exports.TerminalPlusView.forkPtyProcess      (/Users/h/.atom/packages/terminal-plus/lib/view.coffee:16:3)
    at TerminalPlusView.module.exports.TerminalPlusView.displayTerminal    (/Users/h/.atom/packages/terminal-plus/lib/view.coffee:88:5)
    at /Users/h/.atom/packages/terminal-plus/lib/view.coffee:16:3
    at HTMLDivElement.<anonymous> (/Users/h/.atom/packages/terminal-plus/lib/view.coffee:16:3)
       at HTMLDivElement.fn (/Users/h/Downloads/Atom    2.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4855:19)
     at HTMLDivElement.jQuery.event.dispatch (/Users/h/Downloads/Atom 2.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4435:9)
     at HTMLDivElement.elemData.handle (/Users/h/Downloads/Atom 2.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4121:28)

**Comment by jeremyramin** [comment]
@abdulbahajaj Really? It is definitely a function. I'm using it right now and it works. Please tell me:
1. Your Atom version
2. Your Terminal-Plus version
3. Your operating system
4. Any other details you think might be relevant
I see this was happening when you first started launching Terminal-Plus.

**Comment by jeremyramin** [comment]
I guess it is not an issue anymore.
