### ISSUE TITLE
Failed to load the terminal-plus package

### ISSUE THREAD

**Issue by getaasciesh** [jeremyramin/terminal-plus#230]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.7.2
**System**: Microsoft Windows 7 Enterprise 
**Thrown From**: [terminal-plus](https://github.com/jeremyramin/terminal-plus) package, v0.14.5

### Stack Trace

Failed to load the terminal-plus package

```
At Path must be a string. Received undefined

TypeError: Path must be a string. Received undefined
    at assertPath (path.js:8:11)
    at Object.win32.resolve (path.js:130:5)
    at file:///C:/Users/bhattaraia/.atom/packages/terminal-plus/lib/terminal-plus.coffee:62:20
    at Object.<anonymous> (file:///C:/Users/bhattaraia/.atom/packages/terminal-plus/lib/terminal-plus.coffee:59:20)
    at Object.<anonymous> (file:///C:/Users/bhattaraia/.atom/packages/terminal-plus/lib/terminal-plus.coffee:1:1)
    at Module._compile (C:\Users\bhattaraia\AppData\Local\atom\app-1.7.2\resources\app.asar\src\native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (C:\Users\bhattaraia\AppData\Local\atom\app-1.7.2\resources\app.asar\src\compile-cache.js:208:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (C:\Users\bhattaraia\AppData\Local\atom\app-1.7.2\resources\app.asar\src\native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (C:\Users\bhattaraia\AppData\Local\atom\app-1.7.2\resources\app.asar\src\package.js:715:27)
    at C:\Users\bhattaraia\AppData\Local\atom\app-1.7.2\resources\app.asar\src\package.js:117:28
    at Package.module.exports.Package.measure (C:\Users\bhattaraia\AppData\Local\atom\app-1.7.2\resources\app.asar\src\package.js:92:15)
    at Package.module.exports.Package.load (C:\Users\bhattaraia\AppData\Local\atom\app-1.7.2\resources\app.asar\src\package.js:106:12)
    at PackageManager.module.exports.PackageManager.loadPackage (C:\Users\bhattaraia\AppData\Local\atom\app-1.7.2\resources\app.asar\src\package-manager.js:457:14)
    at C:\Users\bhattaraia\AppData\Local\atom\app-1.7.2\resources\app.asar\src\package-manager.js:402:19
    at Config.module.exports.Config.transact (C:\Users\bhattaraia\AppData\Local\atom\app-1.7.2\resources\app.asar\src\config.js:312:16)
    at PackageManager.module.exports.PackageManager.loadPackages (C:\Users\bhattaraia\AppData\Local\atom\app-1.7.2\resources\app.asar\src\package-manager.js:397:19)
    at C:\Users\bhattaraia\AppData\Local\atom\app-1.7.2\resources\app.asar\src\atom-environment.js:743:28
```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "solarized-dark-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
file-icons, v1.7.2
language-javascript-jsx, v0.3.7
terminal-plus, v0.14.5

# Dev
No dev packages
```

**Comment by dunkar** [comment]
I am not sure if this is the same cause that you have, but I was getting an error that Terminal-Plus was compiled for an earlier version of Atom with the suggestion of rebuilding the package. Rebuilding the package DOES appear to resolve the issue and has not developed any visible regressions as of this writing.

**Comment by getaasciesh** [comment]
After rebuilding the package I started getting this error.
But, now there is no error, magically.

**Comment by haasDev** [comment]
just installed package and getting same error.
