### ISSUE TITLE
can't use in current version atom on windows

### ISSUE THREAD

**Issue by ZhiruiLi** [jeremyramin/terminal-plus#231]
I recently update my atom, and the terminal-plus can't run, on the "incompatible packages" tab, I found these error message: 

> Some installed packages could not be loaded because they contain native modules that were compiled for an earlier version of Atom.
> 
> terminal-plus 0.14.5
> pty.js@0.3.0 – Module version mismatch. Expected 47, got 46.
> pty.js@0.3.0 – Module version mismatch. Expected 47, got 46.
> pty.js@0.3.0 – Module version mismatch. Expected 47, got 46.
> pty.js@0.3.0 – Module version mismatch. Expected 47, got 46.
> pty.js@0.3.0 – Module version mismatch. Expected 47, got 46.
> pty.js@0.3.0 – Module version mismatch. Expected 47, got 46.

After I click the "Rebuild Packages" button and restart atom, the plugin can run, but there is nothing except for one cursor blinking on the terminal panel. I had tried reinstall the plugin, but it still can't work

**Comment by MyZeD** [comment]
Same here by adding a new tab.
On Win7 / Atom 1.7.2

```
C:\Users\-\AppData\Local\atom\app-1.7.2\resources\app.asar\src\task.js:49 Cannot find module '../build/Release/pty.node'
C:\Users\-\AppData\Local\atom\app-1.7.2\resources\app.asar\src\task.js:52 Module version mismatch. Expected 47, got 46. Error: Module version mismatch. Expected 47, got 46.
    at Error (native)
    at process.module.(anonymous function) [as dlopen] (ATOM_SHELL_ASAR.js:159:20)
    at Object.Module._extensions..node (module.js:450:18)
    at Object.module.(anonymous function) [as .node] (ATOM_SHELL_ASAR.js:159:20)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (C:\Users\-\.atom\packages\terminal-plus\node_modules\pty.js\lib\pty.js:17:9)
    at Module._compile (module.js:425:26)
    at Object.defineProperty.value [as .js] (C:\Users\-\AppData\Local\atom\app-1.7.2\resources\app.asar\src\compile-cache.js:208:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (C:\Users\-\.atom\packages\terminal-plus\node_modules\pty.js\lib\pty_win.js:10:20)
    at Module._compile (module.js:425:26)
    at Object.defineProperty.value [as .js] (C:\Users\-\AppData\Local\atom\app-1.7.2\resources\app.asar\src\compile-cache.js:208:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (C:\Users\-\.atom\packages\terminal-plus\node_modules\pty.js\index.js:2:18)
    at Module._compile (module.js:425:26)
    at Object.defineProperty.value [as .js] (C:\Users\-\AppData\Local\atom\app-1.7.2\resources\app.asar\src\compile-cache.js:208:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (file:///C:/Users/-/.atom/packages/terminal-plus/lib/process.coffee:1:7)(anonymous function) @ C:\Users\-\AppData\Local\atom\app-1.7.2\resources\app.asar\src\task.js:52(anonymous function) @ C:\Users\-\AppData\Local\atom\app-1.7.2\resources\app.asar\src\task.js:126module.exports.Emitter.simpleDispatch @ C:\Users\-\AppData\Local\atom\app-1.7.2\resources\app.asar\node_modules\event-kit\lib\emitter.…:25module.exports.Emitter.emit @ C:\Users\-\AppData\Local\atom\app-1.7.2\resources\app.asar\node_modules\event-kit\lib\emitter.…:125(anonymous function) @ C:\Users\-\AppData\Local\atom\app-1.7.2\resources\app.asar\src\task.js:78emitTwo @ events.js:87emit @ events.js:172handleMessage @ internal/child_process.js:686channel.onread @ internal/child_process.js:440
4C:\Users\-\AppData\Local\atom\app-1.7.2\resources\app.asar\src\task.js:52 Cannot read property 'bind' of null TypeError: Cannot read property 'bind' of null
    at process.<anonymous> (C:\Users\-\AppData\Local\atom\app-1.7.2\resources\app.asar\src\task-bootstrap.js:82:23)
    at emitTwo (events.js:87:13)
    at process.emit (events.js:172:7)
    at handleMessage (internal/child_process.js:686:10)
    at Pipe.channel.onread (internal/child_process.js:440:11)
```

**Comment by codekraft-studio** [comment]
same here, Windows 7, Atom v1.7.2 the terminal starts empty, can't type and the cursor keep blinking at the start.

**Comment by Paden** [comment]
Does not work on Mac Atom v1.7.2 as well

**Comment by saenzramiro** [comment]
Same here!

**Comment by lexfm** [comment]
Same here please help.

**Comment by poochiethecat** [comment]
Had the same error. Just click on "rebuild package" next to the error message (after clicking on the little red bug in the lower right corner). After rebuilding the package and reloading atom, the package should run without a problem.

**Comment by Nemesis9765** [comment]
Please refer to #201

**Comment by codekraft-studio** [comment]
@poochiethecat can you explain how you did it? I see no error messages at all and If i manually do
```bash
apm rebuilt terminal-plus
```
still not works.. it's a shame because it was a very nice package..

**Comment by Nemesis9765** [comment]
@codekraft-studio it's been a mixed bag for people with the apm rebuild.  More times than not though apm rebuild doesn't do the trick.  You can see everything ppl tried in issue #201

**Comment by codekraft-studio** [comment]
@Nemesis9765 I gave up too and uninstalled the package.. but with great regret :(

**Comment by Paden** [comment]
I started using this alternative: https://atom.io/packages/platformio-ide-terminal

**Comment by kambing86** [comment]
fixed my issue, turns out in windows, need to run the atom ide as admin
then there is second issue where my norton detected it running malicious activity, need to exclude the file for it to run properly
and I used it in mac as well, no problem at all
Atom V1.7.3, terminal-plus 0.14.5
