### ISSUE TITLE
Can't install terminal-plus on Atom 1.7.3 on Windows 7.

### ISSUE THREAD

**Issue by ardit700** [jeremyramin/terminal-plus#250]
Hi, I keep getting an error when trying to install terminal-plus. I tried uninstalling Atom and installed the latest 1.7.3 version, but still the same error:

Installing “terminal-plus@0.14.5” failed.Hide output…

> pty.js@0.3.0 install C:\Users\MARIUS~1.GRE\AppData\Local\Temp\apm-install-dir-11643-5388-fd11l9\node_modules\terminal-plus\node_modules\pty.js
> (node-gyp rebuild 2> builderror.log) || (exit 0)

> pty.js@0.3.0 postinstall C:\Users\MARIUS~1.GRE\AppData\Local\Temp\apm-install-dir-11643-5388-fd11l9\node_modules\terminal-plus\node_modules\pty.js
> node scripts/post-install.js

Access is denied.

module.js:340
    throw err;
          ^
Error: Cannot find module 'C:\scripts\post-install.js'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:935:3
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Users\\Marius.Grete-PC\\AppData\\Local\\atom\\app-1.7.3\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\Marius.Grete-PC\\AppData\\Local\\atom\\app-1.7.3\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "C:\\Users\\Marius.Grete-PC\\.atom\\.apm\\.apmrc" "--userconfig" "C:\\Users\\Marius.Grete-PC\\.atom\\.apmrc" "install" "C:\\Users\\MARIUS~1.GRE\\AppData\\Local\\Temp\\d-11643-5388-j7cswm\\package.tgz" "--target=0.36.8" "--arch=ia32"
npm ERR! node v0.10.40
npm ERR! npm  v2.13.3
npm ERR! code ELIFECYCLE

npm ERR! pty.js@0.3.0 postinstall: `node scripts/post-install.js`
npm ERR! Exit status 8
npm ERR! 
npm ERR! Failed at the pty.js@0.3.0 postinstall script 'node scripts/post-install.js'.
npm ERR! This is most likely a problem with the pty.js package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/post-install.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls pty.js
npm ERR! There is likely additional logging output above.

Do you know any workaround to fix this?

**Comment by semet** [comment]
yups. it doesn't work after updating to latest version. any suggestion everyone?

**Comment by reduardo7** [comment]
I started using this alternative: https://atom.io/packages/platformio-ide-terminal
