### ISSUE TITLE
default shell not launching 

### ISSUE THREAD

**Issue by dileepponna** [jeremyramin/terminal-plus#278]
Thanks for the great package.

A blank screen appears instead of prompt. I could see a cursor blinking at the maximum. Please help.
![terminal plus status](https://cloud.githubusercontent.com/assets/16732495/15800569/c4eafdbc-2a74-11e6-90e1-126e88973f45.jpg)

**Comment by JonathanNasc** [comment]
Same with me

**Comment by savurself11** [comment]
Unable to start terminal process. Win32 error code: 267 Error: Unable to start terminal process. Win32 error code: 267
    at Error (native)
    at Server.<anonymous> (C:\Users\SDS\.atom\packages\platformio-ide-terminal\node_modules\pty.js\lib\pty_win.js:67:9)
    at emitOne (events.js:77:13)
    at Server.emit (events.js:169:7)
    at Pipe.onconnection (net.js:1430:8)

**Comment by repsac-by** [comment]
Upgrade nan to the latest version.
Solution: https://github.com/tensor5/arch-atom/issues/12#issuecomment-223909881
