### ISSUE TITLE
Terminal-plus don't work and i can't type

### ISSUE THREAD

**Issue by SaadLaggoune** [jeremyramin/terminal-plus#280]
-  Atom Latest version Done
- Visual C++ Build Tools Done
- Python 2.7 Done
- Node-gyp Done
- Terminal-plus installed
![terminal-plus](https://cloud.githubusercontent.com/assets/14249834/15873324/0bfe8d26-2cf6-11e6-876b-67596d209767.png)

**Comment by gdrmartins** [comment]
Same issue here!

**Comment by gowerc** [comment]
same here as well.

**Comment by RayFoss** [comment]
Same problem. Uninstalled Atom from mosquito and installed it from official repos. Then tried to uninstall while a terminal-plus terminal was open and got an error `Failed to delete terminal-plus: Does not exist`. So it won't uninstall and I still have the same problem.

**Comment by gowerc** [comment]
looking at the console when trying to run terminal plus I noticed the following error message for myself

`Cannot find module '../build/Release/pty.node'`

`Module version mismatch. Expected 47, got 46. Error: Module version mismatch. Expected 47, got 46.
    at Error (native)
    at process.module.(anonymous function) [as dlopen] (ATOM_SHELL_ASAR.js:159:20)
    at Object.Module._extensions..node (module.js:450:18)
    at Object.module.(anonymous function) [as .node] (ATOM_SHELL_ASAR.js:159:20)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)`

**Comment by gdrmartins** [comment]
Guys, this package has probably been abandoned by its creator and the community.

I suggest using "platformio-ide-terminal" instead. Its a nice fork from this one:
https://atom.io/packages/platformio-ide-terminal

**Comment by SaadLaggoune** [comment]
@gdrmartins  it doesn't work clearly

**Comment by gdrmartins** [comment]
The one I suggested didn't work for you? It did for me though...

**Comment by SaadLaggoune** [comment]
@gdrmartins i don't know why or how. work just for a moment and stop when i open new terminal, where is the problem ? can you help ?

**Comment by danielstern** [comment]
+1

**Comment by voidmarcus** [comment]
+1

**Comment by Oblik-Design** [comment]
+1

**Comment by ad2020** [comment]
+1

**Comment by olivrg** [comment]
Glad to see I'm not the only one experiencing this issue.

**Comment by audrummer15** [comment]
+1

**Comment by menjxo** [comment]
Try this one https://github.com/platformio/platformio-atom-ide-terminal

**Comment by michaelsoriano** [comment]
+1

**Comment by Saviio** [comment]
+1

**Comment by Borderliner** [comment]
Project seems to be dead. Latest commit was on 27th of November 2015. Confirming that `platformio-ide-terminal` works properly on Atom 1.10.2.

**Comment by bhargavshah11** [comment]
+1

**Comment by mattcdmob** [comment]
+1

**Comment by bumkaka** [comment]
+1

**Comment by koskaks** [comment]
+1

**Comment by Aramir10** [comment]
+1

**Comment by johnnypea** [comment]
+1

**Comment by kianfang** [comment]
+1

**Comment by luizcarlos1405** [comment]
+1

**Comment by radek024** [comment]
same here

**Comment by dukio** [comment]
+1

**Comment by mrfint** [comment]
+1

**Comment by gdlmsn** [comment]
+1

**Comment by spencore** [comment]
+1

**Comment by trufflesprouts** [comment]
+1

**Comment by Parnstermia** [comment]
doesn't work either

**Comment by baishusama** [comment]
+1

**Comment by Shanjiv** [comment]
+1

**Comment by benfixit** [comment]
platformio-ide-terminal works fine for me. Thanks @gdrmartins

**Comment by brandiqa** [comment]
+1

**Comment by brandiqa** [comment]
This fix worked for me: https://github.com/jeremyramin/terminal-plus/issues/402

**Comment by vbauer** [comment]
+1

**Comment by razhangwei** [comment]
+1

**Comment by chkzofrek** [comment]
platformio-ide-terminal worked fine for me. Thanks @gdrmartins.

**Comment by suleimana** [comment]
+1

**Comment by jishankai** [comment]
+1

**Comment by leizhang** [comment]
+1

**Comment by tanayuk** [comment]
+1

**Comment by ghost** [comment]
platformio-ide-terminal works great for me. I was getting so frustrated with terminal-plus not working. Thanks @gdrmartins

**Comment by lappalal** [comment]
+1

**Comment by xLI4n** [comment]
+1

**Comment by simondoescode** [comment]
+1

**Comment by cinrylei** [comment]
+1

**Comment by ghost** [comment]
+1

**Comment by ghost** [comment]
This will fix it: [https://github.com/jeremyramin/terminal-plus/issues/402](https://github.com/jeremyramin/terminal-plus/issues/402)

**Comment by utiq** [comment]
+1

**Comment by farhadbaghirov** [comment]
+1

**Comment by jameschetwood** [comment]
+1

**Comment by NicholasPeretti** [comment]
+1

**Comment by NicholasPeretti** [comment]
This works just fine for me: [402](https://github.com/jeremyramin/terminal-plus/issues/402)

**Comment by seemamishra33** [comment]
It works for me also.

**Comment by whiteoutmashups** [comment]
Yes the #402 fix worked perfectly, thanks! And only 4 super simple steps to get it done,

**Comment by sowrabhbs** [comment]
+1

**Comment by glendenning** [comment]
+1 thankyou

**Comment by glendenning** [comment]
+1

**Comment by lukdz** [comment]
+1

**Comment by NineDfish** [comment]
+1

**Comment by khdevel** [comment]
The fix [#402](https://github.com/jeremyramin/terminal-plus/issues/402) worked for me too

**Comment by amponce** [comment]
fix #402 worked

**Comment by hakobtorosyan** [comment]
ergirs ergir chi...

**Comment by ywang04** [comment]
Use platformio-ide-terminal instead, which fixed my issue.

**Comment by jgab3103** [comment]
+1

**Comment by alex94cp** [comment]
+1

**Comment by alexanderad** [comment]
+1

**Comment by vitalikryzhenkous** [comment]
+1

**Comment by yaser-alazm** [comment]
+1

**Comment by jharshman** [comment]
+1

**Comment by gcsuk** [comment]
+1

**Comment by pumpkin-codes** [comment]
+1

**Comment by olegstyle** [comment]
+1

**Comment by kitos9112** [comment]
+1 Totally right - There is a very strong need to move to platformio-ide-terminal. It is a fork of terminal-plus indeed

**Comment by iDevHank** [comment]
+1

**Comment by jrs112** [comment]
platformio-ide-terminal isn't working for me due to the error in this thread https://github.com/platformio/platformio-atom-ide-terminal/issues/350 that's not resolved for windows 10 64.  Does anyone having any other suggestions for an alternative?

**Comment by bbarney213** [comment]
#402 Fixed it for me.

**Comment by sandakith** [comment]
+1

**Comment by MalvikaSingh16** [comment]
+1

**Comment by jeffy-mathew** [comment]
+1

**Comment by guillecro** [comment]
+1

**Comment by kishorevbhosale** [comment]
+1

**Comment by sijia-chen** [comment]
+1
But ```platformio-atom-ide-terminal ``` works for me.

**Comment by aaronkw** [comment]
+1

**Comment by sot232** [comment]
+1

**Comment by ilhamsa1** [comment]
In atom `platformio-ide-terminal` i Have some error when I run "npm run dev" on my vue.js project   [platformio#452](https://github.com/platformio/platformio-atom-ide-terminal/issues/452) but when i use on git terminal or cmd its run normally ,  I didn't find solution for that . then i hope when i Use `terminal-plus` is running normally . but i got error like this .... -_-

**Comment by mitchellcarroll** [comment]
+1

**Comment by cashmisa** [comment]
+1

**Comment by abhijais2** [comment]
+1

**Comment by tesyant** [comment]
+1

**Comment by JiyongYang** [comment]
+1

**Comment by nlound** [comment]
+1

**Comment by Dinkymoo** [comment]
Just use a different terminal

**Comment by spaceguy01** [comment]
I just had the same problem. I updated it, restarted and it works now

**Comment by sherifkhattab13** [comment]
Just updated the terminal, if doesn't work: uninstall it then install again. and if needed restart Atom.
That should fix it.

**Comment by sterniak** [comment]
I checked the package version and it seems like there was a pending update. After the update everything works fine.

**Comment by shelddin** [comment]
+1

**Comment by spulit** [comment]
+1. 
I can't type either.
atom: 1.39.1
electron: 3.1.10
chrome: 66.0.3359.181
node: v10.2.0
platform-io-terminal: 2.9.3

**Comment by AyarWPM** [comment]
+1
[Platformio-ide-terminal 2.9.4](https://atom.io/packages/platformio-ide-terminal)
Atom 1.40.1

**Comment by wantguns** [comment]
+1
used platformio-ide-terminal                           
Atom    : 1.38.2
Electron: 2.0.18
Chrome  : 61.0.3163.100
Node    : 8.9.3

**Comment by seanfarmar** [comment]
+1
atom: 1.40.1

**Comment by NotTooTechy** [comment]
This one works fine:
https://atom.io/packages/terminal-tab-plus

**Comment by Eman152** [comment]
I was having the same issue and It just need to update..try to update it to the lastest version and it'll work fine

**Comment by Quickndry** [comment]
Same persists here. Terminal worked fine the last four times i opened it. Did not open atom for two days, now trying to run my code and see that terminal is exactly as you described: Blinking cursor can be seen, but nothing can be typed, neither does the console tell me the source folder from which it reads. Weird as hell..

**Comment by AWolf81** [comment]
Terminal plus 0.14.5 is working for me after removing the `.atom` folder in "C:\Users\Username\.atom" as described [here](https://discuss.atom.io/t/how-to-reset-atom-text-editor/32219). 
**!!Attention!!** Every setting / package installed will disapear from Atom. Maybe you need to copy the folder to a backup location or note your important packages.

Before the reset I had the same issue as described here - blank terminal panel. I think it was caused by `platformio-ide-terminal` or `platformio` that I have used before. 
I've stopped using platformio so I don't have the issue at the moment. Maybe I will test it again later.

My Atom version is 1.44.0 (x64) on Windows 10.

**Comment by AWolf81** [comment]
OK, weird, it's broken again. Not sure why but after a new start of Atom I have the same blank screen. The dev. console tells me "Module pty.js not found"
![grafik](https://user-images.githubusercontent.com/3046542/74531186-37b53800-4f2c-11ea-8e63-efde978b2b2e.png)

But I'm not sure how to fix this tried to install node-gyp globally and run npm i inside the package.
It's at that location - just not sure if `\\?\` before the path is causing an issue.

**Comment by weareatlaststardust** [comment]
You can try atom-ide-terminal 5.0.1, it is working for me when I encountered this problem recently.

**Comment by nusagates** [comment]
Same here... i am unable to type in terminal

**Comment by UziTech** [comment]
this package is abandoned try [terminus](https://atom.io/packages/terminus) or [x-terminal](https://atom.io/packages/x-terminal)

**Comment by MiniJimi** [comment]
+1 

platformio-ide-terminal 2.10.1
Atom 1.58.0

**Comment by BeniaminK** [comment]
Why keeping unused/broken/obsolete packages in a package repository? This issue dates back to 2015 and still in the `search packages` the obsolete package shows at the top...
