### ISSUE TITLE
I can not write anything in terminal

### ISSUE THREAD

**Issue by knnbayaz** [jeremyramin/terminal-plus#298]
* Click button to open terminal window
* Terminal window is opened
* Cursor is always first line
* I can not write anything

**Comment by swheatley** [comment]
I'm having the same issue.  
-  Uninstalled & installed ( again )
-  Attempted the apm install terminal-plus ( nothing )

All that shows up is the terminal with the blinking curosr.  Terminal isn't even connected

**Comment by ramonsantos** [comment]
I'm also with this problem.
* Atom version: 1.8
* OS: Fedora 24

![tp](https://cloud.githubusercontent.com/assets/5393032/16714319/8742a8a6-4695-11e6-924f-4a7ac14f1a2f.png)

**Comment by tonylnguyen** [comment]
I am also having the same issue

OS: El captain 10.11.5
Atom version: 1.8

**Comment by radix** [comment]
I opened up the console and it seems there's an error being triggered when I try to create a terminal - not sure why it's not popping up the bug reporter notification like atom usually does.

```
Module version mismatch. Expected 47, got 46. Error: Module version mismatch. Expected 47, got 46.

at Error (native)
    at process.module.(anonymous function) [as dlopen] (ATOM_SHELL_ASAR.js:159:20)
    at Object.Module._extensions..node (module.js:450:18)
    at Object.module.(anonymous function) [as .node] (ATOM_SHELL_ASAR.js:159:20)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/home/radix/.atom/packages/terminal-plus/node_modules/pty.js/lib/pty.js:17:9)
    at Module._compile (module.js:425:26)
    at Object.defineProperty.value [as .js] (/usr/share/atom/resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/home/radix/.atom/packages/terminal-plus/node_modules/pty.js/index.js:2:18)
    at Module._compile (module.js:425:26)
    at Object.defineProperty.value [as .js] (/usr/share/atom/resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/home/radix/.atom/packages/terminal-plus/lib/process.coffee:1:7)
    at Object.<anonymous> (/home/radix/.atom/packages/terminal-plus/lib/process.coffee:1:1)
    at Module._compile (module.js:425:26)
    at Object.defineProperty.value [as .coffee] (/usr/share/atom/resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
```

Additionally,

```
Cannot read property 'bind' of null TypeError: Cannot read property 'bind' of null
    at process.<anonymous> (/usr/share/atom/resources/app.asar/src/task-bootstrap.js:82:23)
    at emitTwo (events.js:87:13)
    at process.emit (events.js:172:7)
    at handleMessage (internal/child_process.js:686:10)
    at Pipe.channel.onread (internal/child_process.js:440:11)
```

**Comment by hally9k** [comment]
The same here too.

Cursor blinking, no prompt and typing doesn't echo in the terminal at all.

OSX Yosemite 10.10.5
Atom 1.8

**Comment by FoxelFox** [comment]
Same here

Windows 10 pro
Atom 1.8
terminal-plus 0.14.5

**Comment by rbtbar** [comment]
Same here
Windows 10 pro
Atom 1.8
terminal-plus 0.14.5

**Comment by jdtzmn** [comment]
I poked around and found another issue that said that the user couldn't type. 

Basically, terminal-plus is no longer working (as you all know), and so [here is a link](https://github.com/platformio/platformio-atom-ide-terminal) to a forked version that does work. (At least for me). 

Check out #241 for more details.

**Comment by ramonsantos** [comment]
The [platformio-atom-ide-terminal](https://github.com/platformio/platformio-atom-ide-terminal) is functioning on my computer. :)

**Comment by TheBrenny** [comment]
It would be nice to resolve this issue. I don't want to resort to a terminal that was built for a hacked-up atom... I'll compare where the two differ and see if I can PR some fixes maybe?

**Comment by handicraftsman** [comment]
Same issue
ArchLinux (manjaro)
Atom 1.10.0-beta1
Latest version (i'm lazy)

**Comment by ramonsantos** [comment]
@handicraftsman try https://github.com/platformio/platformio-atom-ide-terminal.

**Comment by handicraftsman** [comment]
@ramonsantos Lel - same glitch

**Comment by joseantonnio** [comment]
Same issue
Fedora release 21 (Twenty One)
Atom 1.10.2
terminal-plus 0.14.5
