### ISSUE TITLE
Installation in Windows 7 failed

### ISSUE THREAD

**Issue by lycis** [jeremyramin/terminal-plus#305]
I tried installing the package today and it failed with the following output:

```
> pty.js@0.3.0 install C:\Users\edd\AppData\Local\Temp\apm-install-dir-116622-1884-5fsk7p\node_modules\terminal-plus\node_modules\pty.js
> (node-gyp rebuild 2> builderror.log) || (exit 0)


C:\Users\edd\AppData\Local\Temp\apm-install-dir-116622-1884-5fsk7p\node_modules\terminal-plus\node_modules\pty.js>if not defined npm_config_node_gyp (node "C:\Users\edd\AppData\Local\atom\app-1.8.0\resources\app\apm\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node  rebuild ) 

> pty.js@0.3.0 postinstall C:\Users\edd\AppData\Local\Temp\apm-install-dir-116622-1884-5fsk7p\node_modules\terminal-plus\node_modules\pty.js
> node scripts/post-install.js


The system cannot find the path specified.
The system cannot find the path specified.
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Users\\edd\\AppData\\Local\\atom\\app-1.8.0\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\edd\\AppData\\Local\\atom\\app-1.8.0\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "C:\\Users\\edd\\.atom\\.apm\\.apmrc" "--userconfig" "C:\\Users\\edd\\.atom\\.apmrc" "install" "C:\\Users\\edd\\AppData\\Local\\Temp\\d-116622-1884-1bajplr\\package.tgz" "--target=0.36.8" "--arch=ia32" "--msvs_version=2013"
npm ERR! node v0.10.40
npm ERR! npm  v2.13.3
npm ERR! code ELIFECYCLE

npm ERR! pty.js@0.3.0 postinstall: `node scripts/post-install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the pty.js@0.3.0 postinstall script 'node scripts/post-install.js'.
npm ERR! This is most likely a problem with the pty.js package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/post-install.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls pty.js
npm ERR! There is likely additional logging output above.
```

**Comment by hntd187** [comment]
I recieve the same error when attempting to install on Ubuntu Mate 16.04

```
> pty.js@0.3.0 install /tmp/apm-install-dir-116829-8870-v5wlur/node_modules/terminal-plus/node_modules/pty.js
> (node-gyp rebuild 2> builderror.log) || (exit 0)


> pty.js@0.3.0 postinstall /tmp/apm-install-dir-116829-8870-v5wlur/node_modules/terminal-plus/node_modules/pty.js
> node scripts/post-install.js

/tmp/apm-install-dir-116829-8870-v5wlur
└── (empty)


module.js:327
    throw err;
    ^

Error: Cannot find module '/tmp/apm-install-dir-116829-8870-v5wlur/node_modules/terminal-plus/node_modules/pty.js/scripts/post-install.js'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:968:3
npm WARN enoent ENOENT: no such file or directory, open '/tmp/apm-install-dir-116829-8870-v5wlur/package.json'
npm WARN apm-install-dir-116829-8870-v5wlur No description
npm WARN apm-install-dir-116829-8870-v5wlur No repository field.
npm WARN apm-install-dir-116829-8870-v5wlur No README data
npm WARN apm-install-dir-116829-8870-v5wlur No license field.
npm ERR! Linux 4.4.0-38-generic
npm ERR! argv "/usr/share/atom/resources/app/apm/bin/node" "/usr/share/atom/resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/home/scarman/.atom/.apm/.apmrc" "--userconfig" "/home/scarman/.atom/.apmrc" "install" "/tmp/d-116829-8870-11q6d2l/package.tgz" "--runtime=electron" "--target=0.37.8" "--arch=x64" "--global-style"
npm ERR! node v4.4.5
npm ERR! npm  v3.10.5
npm ERR! code ELIFECYCLE

npm ERR! pty.js@0.3.0 postinstall: `node scripts/post-install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the pty.js@0.3.0 postinstall script 'node scripts/post-install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the pty.js package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/post-install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs pty.js
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls pty.js
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /tmp/apm-install-dir-116829-8870-v5wlur/npm-debug.log
npm ERR! code 1
```
