### ISSUE TITLE
Blank screen

### ISSUE THREAD

**Issue by handicraftsman** [jeremyramin/terminal-plus#315]
I installed this addon and see... just blank console?
OS: ArchLinux (manjaro)
Atom version: 1.10.0-beta1
Electron version (as always): 0.37.8

**Comment by Fly-Style** [comment]
Same history on my MacBook with last version of Atom.
I see only blank console and I can`t insert anything.

**Comment by rjcoupe** [comment]
Same here.

OS: OSX 10.11.5
Atom:
```
$ atom -v                                                                                                                                                                                                           
Atom    : 1.9.6
Electron: 0.37.8
Chrome  : 49.0.2623.75
Node    : 5.10.0
```

**Comment by handicraftsman** [comment]
Okaaaay. New info

**Comment by bastibense** [comment]
Mac OS X 10.11.6 (15G31)

Got some more here from the developer console when opening a new Terminal tab:

```
Cannot find module '../build/Release/pty.node'
/Applications/Atom.app/Contents/Resources/app.asar/src/task.js:52 Module version mismatch. Expected 47, got 46. Error: Module version mismatch. Expected 47, got 46.
    at Error (native)
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:158:20)
    at Object.Module._extensions..node (module.js:440:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:158:20)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/Users/bbense/.atom/packages/terminal-plus/node_modules/pty.js/lib/pty.js:17:9)
    at Module._compile (module.js:413:34)
    at Object.defineProperty.value [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/Users/bbense/.atom/packages/terminal-plus/node_modules/pty.js/index.js:2:18)
    at Module._compile (module.js:413:34)
    at Object.defineProperty.value [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/Users/bbense/.atom/packages/terminal-plus/lib/process.coffee:1:7)
    at Object.<anonymous> (/Users/bbense/.atom/packages/terminal-plus/lib/process.coffee:1:1)
    at Module._compile (module.js:413:34)
    at Object.defineProperty.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)(anonymous function) @ /Applications/Atom.app/Contents/Resources/app.asar/src/task.js:52(anonymous function) @ /Applications/Atom.app/Contents/Resources/app.asar/src/task.js:126module.exports.Emitter.simpleDispatch @ /Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25module.exports.Emitter.emit @ /Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125(anonymous function) @ /Applications/Atom.app/Contents/Resources/app.asar/src/task.js:78emitTwo @ events.js:100emit @ events.js:185handleMessage @ internal/child_process.js:718channel.onread @ internal/child_process.js:444
7/Applications/Atom.app/Contents/Resources/app.asar/src/task.js:52 Cannot read property 'bind' of null TypeError: Cannot read property 'bind' of null
    at process.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/task-bootstrap.js:82:23)
    at emitTwo (events.js:100:13)
    at process.emit (events.js:185:7)
    at handleMessage (internal/child_process.js:718:10)
    at Pipe.channel.onread (internal/child_process.js:444:11)
```

**Comment by bastibense** [comment]
And some information that I found in the build errors.log of the pty.js package:

I have a feeling that this leads to no error internally, the package is installed as normal and during runtime the pty.js module is not found because it never built in the first place.

```
In file included from ../src/unix/pty.cc:20:
../../nan/nan.h:592:20: error: no type named 'GCEpilogueCallback' in 'v8::Isolate'
      v8::Isolate::GCEpilogueCallback callback
      ~~~~~~~~~~~~~^
../../nan/nan.h:598:20: error: no type named 'GCEpilogueCallback' in 'v8::Isolate'
      v8::Isolate::GCEpilogueCallback callback) {
      ~~~~~~~~~~~~~^
../../nan/nan.h:603:20: error: no type named 'GCPrologueCallback' in 'v8::Isolate'
      v8::Isolate::GCPrologueCallback callback
      ~~~~~~~~~~~~~^
../../nan/nan.h:609:20: error: no type named 'GCPrologueCallback' in 'v8::Isolate'
      v8::Isolate::GCPrologueCallback callback) {
      ~~~~~~~~~~~~~^
4 errors generated.
make: *** [Release/obj.target/pty/src/unix/pty.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
gyp ERR! System Darwin 15.6.0
gyp ERR! command "/usr/local/Cellar/node/6.3.1/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/bbense/.atom/packages/terminal-plus/node_modules/pty.js
gyp ERR! node -v v6.3.1
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok 
```

**Comment by bastibense** [comment]
Might be linked to:
https://github.com/bnoordhuis/node-iconv/issues/153

Apparently pty.js depends on an older version of nan. Might be fixable by changing the upstream dependency to something like 2.2.1. Could not verify yet.

**Comment by justinnoah** [comment]
changed the pty.js dependency from https://github.com/jeremyramin/pty.js#28f2667 to https://github.com/chjj/pty.js - changing from the pinned pty.js fork to upstream pty.js and terminal-plus works once again.

Atom v1.9.9
node v6.4.0

**Comment by davegallant** [comment]
+1

**Comment by rwngallego** [comment]
Is there a fix for this? I'm still having that blank screen :(
