### ISSUE TITLE
Terminal Will Not Open

### ISSUE THREAD

**Issue by jacksonSingleton** [jeremyramin/terminal-plus#317]
Toggle  and New Terminal  don't open up anything. No errors are shown, not a sign of anything I have all dependencies installed.  I've tried re-installing. There is literally no response or sign of anything. I just click the menu item and nothing happens, and nothing shows up in the Command Palette. 
![image](https://cloud.githubusercontent.com/assets/17009633/17610711/5eaa3244-6006-11e6-9bd0-ede634a94092.png) This is a problem on my work computer and home computer so I feel as if this may be on me. However, it works perfectly fine on my MacBook Pro (OSX El Capitan)

*UPDATE: I previously stated that this was working on my Mac (this was just a couple of weeks ago), since I updated Atom to the most recent version, Terminal Plus no longer works, on Mac, Windows, or Linux from my experience. This was THE BEST plugin for Atom for me, so if anyone knows of a fix please post it here.

*UPDATE 2: If you have the option to rebuild terminal plus for compatibility with Atom 1.9 this should fix the issue. (At least for me)

**Comment by MiroHibler** [comment]
Hey @jacksonSingleton, have you tried View -> Developer -> Toggle Developer Tools menu?

Here's what I'm getting:

```sh
Module version mismatch. Expected 47, got 46. Error: Module version mismatch. Expected 47, got 46.
    at Error (native)
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:158:20)
    at Object.Module._extensions..node (module.js:440:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:158:20)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/Users/miro/.atom/packages/terminal-plus/node_modules/pty.js/lib/pty.js:17:9)
    at Module._compile (module.js:413:34)
    at Object.defineProperty.value [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/Users/miro/.atom/packages/terminal-plus/node_modules/pty.js/index.js:2:18)
    at Module._compile (module.js:413:34)
    at Object.defineProperty.value [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/Users/miro/.atom/packages/terminal-plus/lib/process.coffee:1:7)
    at Object.<anonymous> (/Users/miro/.atom/packages/terminal-plus/lib/process.coffee:1:1)
    at Module._compile (module.js:413:34)
    at Object.defineProperty.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
Cannot read property 'bind' of null TypeError: Cannot read property 'bind' of null
    at process.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/task-bootstrap.js:82:23)
    at emitTwo (events.js:100:13)
    at process.emit (events.js:185:7)
    at handleMessage (internal/child_process.js:718:10)
    at Pipe.channel.onread (internal/child_process.js:444:11)
```

**Comment by cars10** [comment]
Getting the same error. 
Terminal Plus 0.14.15
Atom 1.9.8

**Comment by nvaken** [comment]
Same problem here, also in Atom 1.9.8

**Comment by welitonfreitas** [comment]
+1
same error.

**Comment by unnhao** [comment]
terminal is empty

**Comment by lope** [comment]
Same here. It was working on atom 1.5.3 then I upgraded to 1.9.8 and I've got the same error. `Module version mismatch. Expected 47, got 46. Error: Module version mismatch. Expected 47, got 46.`

**Comment by jacksonSingleton** [comment]
@Iope Just found a RIDICULOUSLY simple fix I didn't even think of this. Go to your Incompatible Packages menu and then rebuild Terminal Plus. This fixed it for me and I'm not even sure why I didn't try this first. Let me know if this works for you!

**Comment by nvaken** [comment]
Just tried rebuilding it with `apm reinstall terminal-plus`, but this does not seem to work? 

Not sure if this issue needs to be closed yet though, an broken upgrade path should probably be fixed.

**Comment by jacksonSingleton** [comment]
FINAL UPDATE: I suggest using [platformIO-ide-terminal](https://atom.io/packages/platformio-ide-terminal) it's a fork of Terminal-plus however it seems to be more actively developed, and it actually works. With the amount of issues that TP is having with any user that has Atom 1.9. This package should basically be considered deprecated if not updated soon!

**Comment by nvaken** [comment]
I just noticed the `Rebuild` button button in the red `Some installed packages could not be loaded because they contain native modules that were compiled for an earlier version of Atom.`. Using that button does indeed resolve the problem. I think you were talking about this rebuild function. Puzzles me what is different from running `apm rebuild` versus this button. Weird...

**Comment by lope** [comment]
@nvaken @jacksonSingleton
At first I noticed Atom showed a little bug icon with a number 1 at the bottom right. I clicked it and it popped up the incompatible packages tab. it offered me to rebuild the package for the new version of atom, which I did, and restart but it did not help.

I tried searching ~/.atom/packages/terminal-plus/ for the number 46 to see if I could hax it to 47 and see if that would work. But the number 46 did not exist anywhere.
Then I looked inside ~/.atom/packages/terminal-plus/node_modules/pty.js project for the number 46 and it wasn't there either.
pty.js is a npm package. I tried `npm update` inside that dir but the versions did not go higher. As a hack, i tried updating the devDependencies and dependencies to the latest version, which made npm show 'invalid' afterwards. But after restarting atom etc there was no change.

@jacksonSingleton thanks for the recommendation, will check out platformIO-ide-terminal.

**Comment by jacksonSingleton** [comment]
@nvaken My apologies I should've mentioned that I had already gone searching for that to prevent anyone else for going on a wild goose chase.

**Comment by nvaken** [comment]
@jacksonSingleton No problem. 

Although the problems seemed to be resolved by using the (workaround?) solution of rebuilding, I did check out the fork you mentioned afterwards. It does indeed seem to be way more active, so I installed that one, just for sanity sake. Seems to work just fine. 

The above still does not _fix_ the original problem for this repo, so it seems only logical to me to keep this issue open untill is has been fixed.

**Comment by lope** [comment]
@nvaken yeah seems right to keep the issue open. But personally I'm unsubscribing. Too many github emails! hehe.

I tried `apm deinstall terminal-plus` `apm install terminal-plus`  It did nothing special vs using the GUI.

I didn't try the `apm rebuild`.

**Comment by gregt590** [comment]
Having the same problem on Mac OS El Capitan 10.11.6 with freshly installed Atom 1.9.8 and terminal-plus 0.14.5.  Ran into the same symptoms described above including the pty.js version mismatch and re-built terminal-plus.  Still doesn't work.  Hitting "+" to open a terminal window just gives the blinking box curser with no prompt or accepting of any input.
