### ISSUE TITLE
i want to write something but its not possible

### ISSUE THREAD

**Issue by mkmuduli** [jeremyramin/terminal-plus#319]

**Comment by mylastore** [comment]
same here using an iMac with el Capitan

**Comment by 1zaak** [comment]
Same here, cursor not even appearing (Atom 1.9.8), errors in console:
```
/Applications/Atom.app/Contents/Resources/app.asar/src/task.js:52 Module version mismatch. Expected 47, got 46. Error: Module version mismatch. Expected 47, got 46.
    at Error (native)
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:158:20)
    at Object.Module._extensions..node (module.js:440:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:158:20)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/Users/Izaak/.atom/packages/terminal-plus/node_modules/pty.js/lib/pty.js:17:9)
    at Module._compile (module.js:413:34)
    at Object.defineProperty.value [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/Users/Izaak/.atom/packages/terminal-plus/node_modules/pty.js/index.js:2:18)
    at Module._compile (module.js:413:34)
    at Object.defineProperty.value [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/Users/Izaak/.atom/packages/terminal-plus/lib/process.coffee:1:7)
    at Object.<anonymous> (/Users/Izaak/.atom/packages/terminal-plus/lib/process.coffee:1:1)
    at Module._compile (module.js:413:34)
    at Object.defineProperty.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
/Applications/Atom.app/Contents/Resources/app.asar/src/task.js:52 Cannot read property 'bind' of null TypeError: Cannot read property 'bind' of null
    at process.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/task-bootstrap.js:82:23)
    at emitTwo (events.js:100:13)
    at process.emit (events.js:185:7)
    at handleMessage (internal/child_process.js:718:10)
    at Pipe.channel.onread (internal/child_process.js:444:11)
```

**Comment by genediazjr** [comment]
same here. mbp. el capitan. atom 1.9.8

**Comment by jeffscottward** [comment]
I see a cursor blinking but can't do anything.  Same specs as the guy right above me
El Capitan - v10.11.6
Atom - v1.9.8
NodeJS - v6.3.1 on system

**Comment by 1zaak** [comment]
I just use this [package](https://github.com/platformio/platformio-atom-ide-terminal), a fork of terminal plus

**Comment by jonathanazulay** [comment]
Same here

Mac OS 10.11.5
Atom v1.9.8

![screen shot 2016-08-16 at 13 32 58](https://cloud.githubusercontent.com/assets/593305/17697589/08cd4006-63b6-11e6-9887-61715adb41d3.png)

**Comment by douglasjunior** [comment]
Same here @jonathanazulay.

Mac OS 10.11.6
Atom 1.9.8

**Comment by ktosiek** [comment]
Looks like it's the same bug as #326
