### ISSUE TITLE
Just single symbol of cursor and I can't type anything.

### ISSUE THREAD

**Issue by piaoyidage** [jeremyramin/terminal-plus#321]
![ecbbbc34-62bc-11e6-8ea0-33f0a1c526af](https://cloud.githubusercontent.com/assets/5135405/17701596/00657306-63fd-11e6-9b82-b6c67bb19f52.jpg)

**Comment by larryranches** [comment]
I'm also getting the same thing as well.

**Comment by Smicl11** [comment]
I'm having the same issue on my MacBook Air but not on my MacBook Pro. Both have the latest MacOS updates.

**Comment by jxiaox** [comment]
+1

**Comment by Roland0** [comment]
Issue confirmed, also on OSX.

**Comment by Klayderpus** [comment]
+1, OS X Yosemite, Atom 1.9.9. Have tried `apm rebuild`, deleting the `node_modules` folder inside the package directory and re-running `npm install`, and re-installing the package as a whole. No dice.

**Comment by twingligh** [comment]
Same here.  Linux Mint 18 Cinnamon.  Atom 1.9.9

**Comment by daveismyname** [comment]
same just installed it.

**Comment by jsguy** [comment]
Ditto

**Comment by daveismyname** [comment]
Until this is fixed for anyone stuck on this, this package works https://github.com/platformio/platformio-atom-ide-terminal

**Comment by codevinsky** [comment]
The issue goes -all- the way down to a dependency on `nan  v2.0.5` a few packages deep. I ran into this exact same thing some time back when attempting to use electron and the IPC channel to do something very specific that I can't remember what now.


Anyhow, to fix it (on macOS at least)

```bash
$ cd ~/.atom/packages/terminal-plus/pty.js
$ rm -rf node_modules
$ atom package.json
```

Edit the `package.json` file and change the nan version from `2.0.5` to `>2.0.5`

Close atom and jump back to your terminal

```bash
$ export npm_config_target=0.37.8
$ export npm_config_arch=x64
$ export npm_config_disturl=https://atom.io/download/atom-shell
$ export npm_config_runtime=electron
$ export npm_config_build_from_source=true
$ HOME=~/.atom-gyp npm install
```

There... you fixed it...

probably.

**Comment by pmbenjamin** [comment]
For what it's worth, the Chrome Dev-Tools console window throws the following console error:
```
/Applications/Atom.app/Contents/Resources/app.asar/src/task.js:52 Module version mismatch. Expected 47, got 46. Error: Module version mismatch. Expected 47, got 46.
    at Error (native)
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:158:20)
    at Object.Module._extensions..node (module.js:440:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:158:20)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/Users/pbenjamin/.atom/packages/terminal-plus/node_modules/pty.js/lib/pty.js:17:9)
    at Module._compile (module.js:413:34)
    at Object.defineProperty.value [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/Users/pbenjamin/.atom/packages/terminal-plus/node_modules/pty.js/index.js:2:18)
    at Module._compile (module.js:413:34)
    at Object.defineProperty.value [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/Users/pbenjamin/.atom/packages/terminal-plus/lib/process.coffee:1:7)
    at Object.<anonymous> (/Users/pbenjamin/.atom/packages/terminal-plus/lib/process.coffee:1:1)
    at Module._compile (module.js:413:34)
    at Object.defineProperty.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
```

It appears that the Windows and Mac binaries for your [pty package](https://github.com/jeremyramin/pty.js/tree/prebuilt) needs updating again.

**Comment by vihangpatil** [comment]
Fix by @codevinsky works for me on Mac.
Small correction. First step is:
$ cd ~/.atom/packages/terminal-plus/node_modules/pty.js
... instead of
$ cd ~/.atom/packages/terminal-plus/pty.js

**Comment by swapnilchincholkar** [comment]
@codevinsky Thanks a ton!!!!!
@vihangpatil Thanks for correction !!

**Comment by deimon777** [comment]
Terminal-fusion
Work for my
https://atom.io/packages/terminal-fusion

**Comment by geligelu** [comment]
@codevinsky - thanks! Can confirm this worked for me too.

**Comment by sevensilvers** [comment]
@codevinsky - Thanks! Works on Ubuntu 16.04.

**Comment by vuhung3990** [comment]
platformio work perfect,  fork of terminal-plus
