### ISSUE TITLE
Uncaught Error: Cannot send message to terminated process

### ISSUE THREAD

**Issue by rasensio** [jeremyramin/terminal-plus#33]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.19
**System**: Mac OS X 10.11
**Thrown From**: [terminal-plus](https://github.com/jeremyramin/terminal-plus) package, v0.7.0

### Stack Trace

Uncaught Error: Cannot send message to terminated process

```
At /Applications/Atom.app/Contents/Resources/app.asar/src/task.js:120

Error: Cannot send message to terminated process
  at Task.module.exports.Task.send (/Applications/Atom.app/Contents/Resources/app.asar/src/task.js:120:15)
  at TerminalPlusView.module.exports.TerminalPlusView.resize (/Users/asensio/.atom/packages/terminal-plus/lib/view.coffee:226:17)
  at TerminalPlusView.module.exports.TerminalPlusView.resizeTerminalToView (/Users/asensio/.atom/packages/terminal-plus/lib/view.coffee:357:6)
  at TerminalPlusView.module.exports.TerminalPlusView.focus (/Users/asensio/.atom/packages/terminal-plus/lib/view.coffee:341:6)
  at HTMLDivElement.<anonymous> (/Users/asensio/.atom/packages/terminal-plus/lib/view.coffee:1:1)
  at HTMLDivElement.jQuery.event.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4435:9)
  at HTMLDivElement.elemData.handle (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4121:28)

```

### Commands

```
     -1:57.7.0 fuzzy-finder:toggle-file-finder (atom-text-editor.editor.is-focused)
  4x -1:51.1.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -1:50 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -1:50 core:cancel (atom-text-editor.editor.mini.is-focused)
     -1:44.1.0 project-manager:list-projects (atom-text-editor.editor.is-focused)
     -1:42.7.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -1:42.4.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -1:27.3.0 terminal-plus:toggle (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -0:38.6.0 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-atom-dark-ui)
  2x -0:38.3.0 tree-view:reveal-active-file (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-atom-dark-ui)
```

### Config

```json
{
  "core": {
    "projectHome": "/Users/asensio/projects",
    "themes": [
      "atom-dark-ui",
      "one-dark-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
angularjs, v0.3.2
autoclose-html, v0.19.0
background-tips, v0.26.0
color-picker, v2.0.13
language-ansible, v0.1.3
language-java, v0.16.0
language-javascript, v0.96.0
language-php, v0.30.0
language-sql, v0.17.0
language-todo, v0.27.0
project-manager, v2.6.1
synced-sidebar, v0.4.2
terminal-plus, v0.7.0

# Dev
No dev packages
```

**Comment by jeremyramin** [comment]
Fixed this in v0.7.1

**Comment by jibreel** [comment]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.19
**System**: Mac OS X 10.11
**Thrown From**: [terminal-plus](https://github.com/jeremyramin/terminal-plus) package, v0.8.2


### Stack Trace

Uncaught Error: Cannot send message to terminated process

```
At /Applications/Atom.app/Contents/Resources/app.asar/src/task.js:120

Error: Cannot send message to terminated process
  at Task.module.exports.Task.send (/Applications/Atom.app/Contents/Resources/app.asar/src/task.js:120:15)
  at TerminalPlusView.module.exports.TerminalPlusView.resize (/Users/jibreel/.atom/packages/terminal-plus/lib/view.coffee:223:6)
  at TerminalPlusView.module.exports.TerminalPlusView.resizeTerminalToView (/Users/jibreel/.atom/packages/terminal-plus/lib/view.coffee:350:5)
  at TerminalPlusView.module.exports.TerminalPlusView.focus (/Users/jibreel/.atom/packages/terminal-plus/lib/view.coffee:329:20)
  at HTMLDivElement.<anonymous> (/Users/jibreel/.atom/packages/terminal-plus/lib/view.coffee:1:1)
  at HTMLDivElement.jQuery.event.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4435:9)
  at HTMLDivElement.elemData.handle (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4121:28)

```

### Commands

```
 10x -2:36.1.0 core:backspace (atom-text-editor.editor.is-focused)
     -2:32.5.0 autocomplete-plus:confirm (atom-text-editor.editor.is-focused.autocomplete-active)
     -2:26.6.0 core:save (atom-text-editor.editor.is-focused)
     -2:07.0 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
color-picker, v2.0.13
file-icons, v1.6.10
latex, v0.26.0
tabs-to-spaces, v0.11.1
terminal-plus, v0.8.2

# Dev
No dev packages
```

**Comment by jeremyramin** [comment]
@jibreel Thank you for reporting this and letting me know that this is still an issue. I will take a look at it soon and let you know when I release a version that has this issue fixed.

**Comment by jeremyramin** [comment]
v0.9.0 includes a different method of making sure that this error does not show up anymore. Hopefully I did it right this time.
