### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by marwanAmeen** [jeremyramin/terminal-plus#333]
i can not type any thing,. .. it looks like frizzing 
![issue](https://cloud.githubusercontent.com/assets/3380207/18259694/65b7f400-7419-11e6-8c6f-2e47c6f75bbf.png)

**Comment by NirLevanon** [comment]
+1

**Comment by Mlvtrglvn** [comment]
This is the error on the console:
`Module version mismatch. Expected 47, got 46. Error: Module version mismatch. Expected 47, got 46.
    at Error (native)
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:158:20)
    at Object.Module._extensions..node (module.js:440:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:158:20)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/home/brtdra/.atom/packages/terminal-plus/node_modules/pty.js/lib/pty.js:17:9)
    at Module._compile (module.js:413:34)
    at Object.defineProperty.value [as .js] (/usr/share/atom/resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/home/brtdra/.atom/packages/terminal-plus/node_modules/pty.js/index.js:2:18)
    at Module._compile (module.js:413:34)
    at Object.defineProperty.value [as .js] (/usr/share/atom/resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/home/brtdra/.atom/packages/terminal-plus/lib/process.coffee:1:7)
    at Object.<anonymous> (/home/brtdra/.atom/packages/terminal-plus/lib/process.coffee:1:1)
    at Module._compile (module.js:413:34)
    at Object.defineProperty.value [as .coffee] (/usr/share/atom/resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)`

**Comment by Mlvtrglvn** [comment]
Just noticed it has been already reported several times. This duplicate should be closed.
