### ISSUE TITLE
Not working, black screen is coming, not able to write anything

### ISSUE THREAD

**Issue by shahmir811** [jeremyramin/terminal-plus#335]
![image](https://cloud.githubusercontent.com/assets/19389145/18424384/7fc920cc-78c8-11e6-9869-b99a1a65fffc.png)

**Comment by bondarewicz** [comment]
Same issue here, I got following on each keystroke:
```
/Applications/Atom.app/Contents/Resources/app.asar/src/task.js:52 Cannot read property 'bind' of null TypeError: Cannot read property 'bind' of null
    at process.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/task-bootstrap.js:82:23)
    at emitTwo (events.js:100:13)
    at process.emit (events.js:185:7)
    at handleMessage (internal/child_process.js:718:10)
    at Pipe.channel.onread (internal/child_process.js:444:11)
```

**Comment by sandybemonkey** [comment]
same thing here ..anay idea on how to solve this??

**Comment by bondarewicz** [comment]
This issue is a duplicate, please see #331 for details.
Quickest workaround seems to be to use a fork mentioned [here](https://github.com/jeremyramin/terminal-plus/issues/331#issuecomment-245299168)
