### ISSUE TITLE
Terminal not starting up

### ISSUE THREAD

**Issue by andela-ekahindi** [jeremyramin/terminal-plus#353]
I've tried to install terminal plus on me Atom, but it's not starting up. It just shows the cursor, nothing else is happening. Any idea why?

<img width="1117" alt="screen shot 2016-10-05 at 12 31 11 pm" src="https://cloud.githubusercontent.com/assets/19430138/19108032/a2c8f188-8af7-11e6-86d9-c17e82e945ae.png">

**Comment by jnmoal** [comment]
I'm facing the exact same same issue.
terminal-plus v0.14.5, atom v1.10.2.

here are the logs in the console when I open up a terminal:

> 
/usr/share/atom/resources/app.asar/src/task.js:49 Cannot find module '../build/Release/pty.node'
/usr/share/atom/resources/app.asar/src/task.js:52 Module version mismatch. Expected 47, got 46. Error: Module version mismatch. Expected 47, got 46.
    at Error (native)
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:158:20)
    at Object.Module._extensions..node (module.js:440:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:158:20)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/home/jnmoal/.atom/packages/terminal-plus/node_modules/pty.js/lib/pty.js:17:9)
    at Module._compile (module.js:413:34)
    at Object.defineProperty.value [as .js] (/usr/share/atom/resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/home/jnmoal/.atom/packages/terminal-plus/node_modules/pty.js/index.js:2:18)
    at Module._compile (module.js:413:34)
    at Object.defineProperty.value [as .js] (/usr/share/atom/resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/home/jnmoal/.atom/packages/terminal-plus/lib/process.coffee:1:7)
    at Object.<anonymous> (/home/jnmoal/.atom/packages/terminal-plus/lib/process.coffee:1:1)
    at Module._compile (module.js:413:34)
    at Object.defineProperty.value [as .coffee] (/usr/share/atom/resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)(anonymous function) @ /usr/share/atom/resources/app.asar/src/task.js:52(anonymous function) @ /usr/share/atom/resources/app.asar/src/task.js:126module.exports.Emitter.simpleDispatch @ /usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:25module.exports.Emitter.emit @ /usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:125(anonymous function) @ /usr/share/atom/resources/app.asar/src/task.js:78emitTwo @ events.js:100emit @ events.js:185handleMessage @ internal/child_process.js:718channel.onread @ internal/child_process.js:444
/usr/share/atom/resources/app.asar/src/task.js:52 Cannot read property 'bind' of null TypeError: Cannot read property 'bind' of null
    at process.<anonymous> (/usr/share/atom/resources/app.asar/src/task-bootstrap.js:82:23)
    at emitTwo (events.js:100:13)
    at process.emit (events.js:185:7)
    at handleMessage (internal/child_process.js:718:10)
    at Pipe.channel.onread (internal/child_process.js:444:11)(anonymous function) @ /usr/share/atom/resources/app.asar/src/task.js:52(anonymous function) @ /usr/share/atom/resources/app.asar/src/task.js:126module.exports.Emitter.simpleDispatch @ /usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:25module.exports.Emitter.emit @ /usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:125(anonymous function) @ /usr/share/atom/resources/app.asar/src/task.js:78emitTwo @ events.js:100emit @ events.js:185handleMessage @ internal/child_process.js:718channel.onread @ internal/child_process.js:444
/usr/share/atom/resources/app.asar/src/task.js:49 Cannot find module '../build/Release/pty.node'

**Comment by milooy** [comment]
I also having an same issue 😢

**Comment by cmoud94** [comment]
Same issue here.

OS: Linux Mint 18 Cinnamon (fully updated)
Atom: 1.10.2
terminal-plus: 0.14.5

Here is error log from console when I try to open terminal-plus:
```
Cannot find module '../build/Release/pty.node'
/opt/atom/resources/app.asar/src/task.js:52 Module version mismatch. Expected 47, got 46. Error: Module version mismatch. Expected 47, got 46.
    at Error (native)
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:158:20)
    at Object.Module._extensions..node (module.js:440:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:158:20)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/home/cmoud94/.atom/packages/terminal-plus/node_modules/pty.js/lib/pty.js:17:9)
    at Module._compile (module.js:413:34)
    at Object.defineProperty.value [as .js] (/opt/atom/resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/home/cmoud94/.atom/packages/terminal-plus/node_modules/pty.js/index.js:2:18)
    at Module._compile (module.js:413:34)
    at Object.defineProperty.value [as .js] (/opt/atom/resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/home/cmoud94/.atom/packages/terminal-plus/lib/process.coffee:1:7)
    at Object.<anonymous> (/home/cmoud94/.atom/packages/terminal-plus/lib/process.coffee:1:1)
    at Module._compile (module.js:413:34)
    at Object.defineProperty.value [as .coffee] (/opt/atom/resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)(anonymous function) @ /opt/atom/resources/app.asar/src/task.js:52(anonymous function) @ /opt/atom/resources/app.asar/src/task.js:126module.exports.Emitter.simpleDispatch @ /opt/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:25module.exports.Emitter.emit @ /opt/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:125(anonymous function) @ /opt/atom/resources/app.asar/src/task.js:78emitTwo @ events.js:100emit @ events.js:185handleMessage @ internal/child_process.js:718channel.onread @ internal/child_process.js:444
/opt/atom/resources/app.asar/src/task.js:52 Cannot read property 'bind' of null TypeError: Cannot read property 'bind' of null
    at process.<anonymous> (/opt/atom/resources/app.asar/src/task-bootstrap.js:82:23)
    at emitTwo (events.js:100:13)
    at process.emit (events.js:185:7)
    at handleMessage (internal/child_process.js:718:10)
    at Pipe.channel.onread (internal/child_process.js:444:11)(anonymous function) @ /opt/atom/resources/app.asar/src/task.js:52(anonymous function) @ /opt/atom/resources/app.asar/src/task.js:126module.exports.Emitter.simpleDispatch @ /opt/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:25module.exports.Emitter.emit @ /opt/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:125(anonymous function) @ /opt/atom/resources/app.asar/src/task.js:78emitTwo @ events.js:100emit @ events.js:185handleMessage @ internal/child_process.js:718channel.onread @ internal/child_process.js:444
```

**Comment by montogeek** [comment]
I am getting this same error

**Comment by tineyi** [comment]
Same issue here.

**Comment by meanbunny** [comment]
Same here

**Comment by icecity96** [comment]
The same error

**Comment by b1nary** [comment]
same issue here too.

**Comment by Jahhein** [comment]
Also the same, ATOM 1.10.2, Mac 10.11.6, terminal-plus 0.14.5

**Comment by ozluy** [comment]
+1 for ATOM 1.10.2, Mac 10.11.6, terminal-plus 0.14.5

**Comment by jaxn** [comment]
Also ATOM 1.10.2, Mac 10.11.6, terminal-plus 0.14.5

There is a fork from @platformio that works: [platformio-atom-ide-terminal](https://github.com/platformio/platformio-atom-ide-terminal)

**Comment by wochap** [comment]
This works for me https://github.com/jeremyramin/terminal-plus/issues/321#issuecomment-242193432

**Comment by neycodes** [comment]
I started using [terminal-fusion](https://atom.io/packages/terminal-fusion)

Works perfectly.

**Comment by jdkcn** [comment]
+1 for ATOM 1.10.2, Linux Deepin, terminal-plus 0.14.5

**Comment by BattleToads** [comment]
This package looks like it isn't being maintained anymore.

**Comment by mattgabor** [comment]
Same error

**Comment by LarsKumbier** [comment]
Could you please check my fix here? https://github.com/jeremyramin/terminal-plus/issues/362#issuecomment-255520028
