### ISSUE TITLE
Terminal Cursor blink but i cannot write anything 

### ISSUE THREAD

**Issue by itguest** [jeremyramin/terminal-plus#357]
Terminal Cursor blink but i cannot write anything

**Comment by derwentx** [comment]
Same here, TP 0.14.5, Atom 1.10.2, macOS Sierra 10.12

**Comment by UnEpicFail** [comment]
+1, Atom 1.10.2, Ubuntu 16.04.1 x64

**Comment by lynasity** [comment]
same here

**Comment by inssitu** [comment]
Same. macOs 10.12

**Comment by FallingSnow** [comment]
Same, Atom 1.11.1, Windows x64

**Comment by metalwood** [comment]
Same, Atom 1.11.1, Mac OS 10.11

**Comment by michaelkoelewijn** [comment]
Same on Atom 1.11.1 Windows 7 x64

**Comment by Proteo** [comment]
Same over here, Atom 1.11.1 Mac OS 10.11.6

**Comment by GilbertSun** [comment]
same on Atom 1.10.2 Mac OS 10.12

**Comment by hjmeteor** [comment]
same here Atom 1.11.1 Mac OS 10.11.6

**Comment by replaystory** [comment]
same Atom 1.11 MacSierra 10.12 (16A323)

**Comment by shivansal** [comment]
Yeah what is going on?

**Comment by replaystory** [comment]
in ATM packages : /terminal-plus/node_modules/pty.js/build/Release/ is empty. 
Terminal-plus try to access to bin, no ?

**Comment by snowinferno** [comment]
After opening dev tools through Atom I see two error messages when I try to open a terminal (I cleared the console before trying to open the terminal so I know it can only be from clicking the `+` to open a terminal). `Atom 1.11.1`, `OSX 10.11.6`, `terminal-plus 0.14.5`:

```
task.coffee:86 Module version mismatch. Expected 47, got 46. Error: Module version mismatch. Expected 47, got 46.
    at Error (native)
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:158:20)
    at Object.Module._extensions..node (module.js:440:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:158:20)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/Users/snowinferno/.atom/packages/terminal-plus/node_modules/pty.js/lib/pty.js:17:9)
    at Module._compile (module.js:413:34)
    at Object.defineProperty.value [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/Users/snowinferno/.atom/packages/terminal-plus/node_modules/pty.js/index.js:2:18)
    at Module._compile (module.js:413:34)
    at Object.defineProperty.value [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/Users/snowinferno/.atom/packages/terminal-plus/lib/process.coffee:1:7)
    at Object.<anonymous> (/Users/snowinferno/.atom/packages/terminal-plus/lib/process.coffee:1:1)
    at Module._compile (module.js:413:34)
    at Object.defineProperty.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)(anonymous function) @ task.coffee:86(anonymous function) @ task.coffee:146module.exports.Emitter.simpleDispatch @ /Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25module.exports.Emitter.emit @ /Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:129(anonymous function) @ task.coffee:98emitTwo @ events.js:100emit @ events.js:185handleMessage @ internal/child_process.js:718channel.onread @ internal/child_process.js:444
task.coffee:86 Cannot read property 'bind' of null TypeError: Cannot read property 'bind' of null
    at process.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/task-bootstrap.js:82:23)
    at emitTwo (events.js:100:13)
    at process.emit (events.js:185:7)
    at handleMessage (internal/child_process.js:718:10)
    at Pipe.channel.onread (internal/child_process.js:444:11)
```

**Comment by erwstout** [comment]
Same, TP 0.14.5 - macOS Sierra 10.12 - Atom 1.11.1

**Comment by FottyM** [comment]
same here OSX 10.12

**Comment by erwstout** [comment]
For those looking for an alternative, https://atom.io/packages/platformio-ide-terminal is a fork and seems to work great.

**Comment by austindenny** [comment]
@erwstout thanks! works great

**Comment by lxgyChen** [comment]
same here, windows 10 education,Atom 1.11.1

**Comment by sjmb** [comment]
same here, Ubuntu 16.04 64-bit, Atom 1.11.2, terminal-plus 0.14.5

**Comment by hugovila** [comment]
Terminal Cursor blink but i cannot write anything
Ubuntu 16.04 64-bit, Atom 1.11.2, terminal-plus 0.14.5
Node v4.6.0 & v6.7.0

**Comment by ghost** [comment]
look @ https://github.com/jeremyramin/terminal-plus/pull/364
