### ISSUE TITLE
Terminal Plus not working on

### ISSUE THREAD

**Issue by stefan-matcovici** [jeremyramin/terminal-plus#366]
I am running atom on ubuntu 16.04.1. I updated atom and reinstalled terminal plus.
![screenshot from 2016-10-26 23-04-33](https://cloud.githubusercontent.com/assets/21690052/19743119/ad4c843c-9bd0-11e6-8ea4-4e14a7e3e50c.png)

**Comment by ghost** [comment]
Same here on OSX 10.12 and Atom 1.11.2

**Comment by andreygolik** [comment]
I have the same issue.
macOS Sierra 10.12.1
Atom 1.11.2

**Comment by thoov** [comment]
Seems like a dup of #361

**Comment by encodi** [comment]
+1
macOS Sierra 10.12.1
Atom 1.11.2

**Comment by salim-dev** [comment]
I have the same issue.
windows 10
Atom 1.11.2

**Comment by pixeleate** [comment]
Hello everyone, this issue can be fixed with the following procedure.

You must to have `node-gyp` installed before run these steps, run `npm i -g node-gyp` just to make sure:
- `cd ~/.atom/packages/terminal-plus`
- `rm -rf ./node_modules`
- `npm i`
- try open a new `terminal-plus`
- enjoy

it's working for me:

macOS Sierra 10.12.1
atom 1.11.2

<img width="1237" alt="captura de pantalla 2016-10-29 a las 1 25 00 a m" src="https://cloud.githubusercontent.com/assets/1545853/19827624/91d9da7c-9d76-11e6-92d7-dba6bd14d1f6.png">

The same for https://github.com/jeremyramin/terminal-plus/issues/365 https://github.com/jeremyramin/terminal-plus/issues/361 https://github.com/jeremyramin/terminal-plus/issues/359 https://github.com/jeremyramin/terminal-plus/issues/357

**Comment by newelement** [comment]
@pixeleate Tried that with no luck.

**Comment by bobmacneal** [comment]
I have the same issue.
macOS Sierra 10.12.1
Atom 1.11.2

Tried @pixeleate suggestion, but didn't work for me.

**Comment by duard** [comment]
Same insue here, Ubuntu

**Comment by pixeleate** [comment]
I can help you to make it work, just paste a screenshot of the log or error, usually is a problem with `node-gyp`, that needs `python 2.7.x`, `Xcode with Command Line Tools` and accept the terms and conditions of `Xcode`.

**Comment by skull-squadron** [comment]
### What works
1. Remove atom stable 1.11.x
2. Install latest atom beta 1.12
3. Rename `Atom Beta` (`.exe` or `.app`) to not contain spaces (`Atom-Beta`)
4. `apm-beta install jeremyramin/terminal-plus` (installs from github)
5. Works

**Comment by stefan-matcovici** [comment]
![screenshot from 2016-11-01 12-36-07](https://cloud.githubusercontent.com/assets/21690052/19887226/efabc352-a02f-11e6-8cdd-e182a2162354.png)
i tried all the solutions above
when i try to 'npm i' i get an error too about npy.js

**Comment by ziong** [comment]
try this #362

**Comment by Fred-Barclay** [comment]
If you don't want to move to Atom Beta, these seem to be working:
https://github.com/jeremyramin/terminal-plus/issues/370#issuecomment-258247328

**Comment by Randagio13** [comment]
Hi, I have the same problem with Atom v1.12.0

```
task.coffee:86 Module version mismatch. Expected 49, got 46. Error: Module version mismatch. Expected 49, got 46.
    at Error (native)
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:168:20)
    at Object.Module._extensions..node (module.js:568:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:168:20)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/alessandrocasazza13/.atom/packages/terminal-plus/node_modules/pty.js/lib/pty.js:17:9)
    at Module._compile (module.js:541:32)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:201:21)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/alessandrocasazza13/.atom/packages/terminal-plus/node_modules/pty.js/index.js:2:18)
    at Module._compile (module.js:541:32)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:201:21)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/alessandrocasazza13/.atom/packages/terminal-plus/lib/process.coffee:1:7)
    at Object.<anonymous> (/Users/alessandrocasazza13/.atom/packages/terminal-plus/lib/process.coffee:1:1)
    at Module._compile (module.js:541:32)
    at Object.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:201:21)
    at Module.load (module.js:458:32)
```
