### ISSUE TITLE
Could not be loaded because it contains native modules that were compiled for an earlier version of Atom

### ISSUE THREAD

**Issue by sfgarza** [jeremyramin/terminal-plus#378]
![incompatible_packages_ ___projects_gotahoe_wp-content_plugins_impress-pro](https://cloud.githubusercontent.com/assets/8662253/20159689/3a4e7072-a697-11e6-949e-935477dfba0c.png)

**Comment by udyux** [comment]
Same issue?

After updating Atom to `1.12.0`, terminal window doesn't load, just has the blinking cursor with no prompt.

Tried rebuilding the package through Atom's UI and tried reinstalling terminal-plus.
No change in behaviour.

Atom `1.12.0`
terminal-plus `0.14.5`
macOS Sierra `10.12.1`

Full error from the console:

```
 /Applications/Atom.app/Contents/Resources/app.asar/src/task.js:52 Module version mismatch. Expected 49, got 46. Error: Module version mismatch. Expected 49, got 46.
    at Error (native)
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:168:20)
    at Object.Module._extensions..node (module.js:568:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:168:20)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/udyux/.atom/packages/terminal-plus/node_modules/pty.js/lib/pty.js:17:9)
    at Module._compile (module.js:541:32)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:201:21)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/udyux/.atom/packages/terminal-plus/node_modules/pty.js/index.js:2:18)
    at Module._compile (module.js:541:32)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:201:21)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/udyux/.atom/packages/terminal-plus/lib/process.coffee:1:7)
    at Object.<anonymous> (/Users/udyux/.atom/packages/terminal-plus/lib/process.coffee:1:1)
    at Module._compile (module.js:541:32)
    at Object.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:201:21)
    at Module.load (module.js:458:32)
```

**Comment by Fred-Barclay** [comment]
This is affecting a lot of us... #367 #366 #365 #362 #361 #359 #357 #353 #352 #351 

Until the developers get this fixed, there are some alternatives:
termination (shameless self-promotion) :wink:
tokamak-terminal
platformio-ide-terminal

**Comment by vantrav** [comment]
[After Atom Update 1.12.0, Just a blinking caret , does not show command prompt / directory location #383](https://github.com/jeremyramin/terminal-plus/issues/383)
1. Uninstall terminal-plus
2. `apm install LarsKumbier/terminal-plus`
3. Terminal's background-color  fix setting `background-color: transparent;` in standard.less (on Mac it's usually in ~/.atom/packages/terminal-plus/styles/themes/)
No idea if this works for Windows.
