### ISSUE TITLE
Unable to Install due to some error in pty.js

### ISSUE THREAD

**Issue by prijindal** [jeremyramin/terminal-plus#379]
This is my error output
```
> pty.js@0.3.0 install /tmp/apm-install-dir-1161010-15739-fwjact/node_modules/terminal-plus/node_modules/pty.js
> (node-gyp rebuild 2> builderror.log) || (exit 0)


> pty.js@0.3.0 postinstall /tmp/apm-install-dir-1161010-15739-fwjact/node_modules/terminal-plus/node_modules/pty.js
> node scripts/post-install.js

/tmp/apm-install-dir-1161010-15739-fwjact
`-- (empty)


module.js:327
    throw err;
    ^

Error: Cannot find module '/tmp/apm-install-dir-1161010-15739-fwjact/node_modules/terminal-plus/node_modules/pty.js/scripts/post-install.js'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:968:3
npm WARN enoent ENOENT: no such file or directory, open '/tmp/apm-install-dir-1161010-15739-fwjact/package.json'
npm WARN apm-install-dir-1161010-15739-fwjact No description
npm WARN apm-install-dir-1161010-15739-fwjact No repository field.
npm WARN apm-install-dir-1161010-15739-fwjact No README data
npm WARN apm-install-dir-1161010-15739-fwjact No license field.
npm ERR! Linux 4.8.0-27-generic
npm ERR! argv "/usr/share/atom/resources/app/apm/bin/node" "/usr/share/atom/resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/home/prijindal/.atom/.apm/.apmrc" "--userconfig" "/home/prijindal/.atom/.apmrc" "install" "/tmp/d-1161010-15739-19psee1/package.tgz" "--runtime=electron" "--target=0.37.8" "--arch=x64" "--global-style"
npm ERR! node v4.4.5
npm ERR! npm  v3.10.5
npm ERR! code ELIFECYCLE

npm ERR! pty.js@0.3.0 postinstall: `node scripts/post-install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the pty.js@0.3.0 postinstall script 'node scripts/post-install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the pty.js package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/post-install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs pty.js
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls pty.js
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /tmp/apm-install-dir-1161010-15739-fwjact/npm-debug.log
npm ERR! code 1
```

**Comment by vantrav** [comment]
[After Atom Update 1.12.0, Just a blinking caret , does not show command prompt / directory location #383](https://github.com/jeremyramin/terminal-plus/issues/383)
1. Uninstall terminal-plus
2. `apm install LarsKumbier/terminal-plus`
3. Terminal's background-color  fix setting `background-color: transparent;` in standard.less (on Mac it's usually in ~/.atom/packages/terminal-plus/styles/themes/)
No idea if this works for Windows.

**Comment by marchank0** [comment]
>No idea if this works for Windows.

It's not. Win 10 x64

mostly the same error
https://github.com/jeremyramin/terminal-plus/issues/399

**Comment by wotsyula** [comment]
You know there is a fork of this project [platform-atom-ide-terminal](https://github.com/platformio/platformio-atom-ide-terminal)

It uses pre-built libraries so no need to install / configure / deal-with node-gyp. I think a lot of problems with this plug-in would be solved if author did the same. It sucks that every time there is a bug in `pty.js` or `term.js` every user of this plug-in has to suffer. I think most of the issue will be sorted out in the newer versions of these repos though in the future.

**Comment by snaqviApps** [comment]
_same error on ubuntu 17.10_
---------------------------------------------
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/post-install.js
........................

**apm -v**
apm  1.18.12
**npm  3.10.10**
node 6.9.5 x64
atom 1.24.1
python 2.7.14
git 2.16.2
****
-----------------
**npm -v**
5.6.0
-----------------
**nvm --version**
0.33.8
****
---------------------------
note: python has been aliased to python3 as below:
python --version P
ython 3.6.3

**Comment by azumia-azu** [comment]
@wotsyula same issue with platform-ide-terminal
