### ISSUE TITLE
Break on Atom 1.12.0 update

### ISSUE THREAD

**Issue by datafunk** [jeremyramin/terminal-plus#381]
I was happily working away inside Atom with terminal-plus open, got the prompt to update Atom and on restart I got a native extension (??) error msg (sorry, cannot find it now, not sure how to trigger it again in Atom either bc Atom prompted to rebuild the package and apparently it did with no issues).

Interestingly, my global node-gyp vanished too, but reinstalling it did not fix the problem for terminal-plus, which loads the pane and a blinking cursor shows, but no input etc. 

Here's the console output from devtools:

```
Cannot find module '../build/Release/pty.node'
task.coffee:86 Module version mismatch. Expected 49, got 46. Error: Module version mismatch. Expected 49, got 46.
    at Error (native)
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:168:20)
    at Object.Module._extensions..node (module.js:568:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:168:20)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/pborbely/.atom/packages/terminal-plus/node_modules/pty.js/lib/pty.js:17:9)
    at Module._compile (module.js:541:32)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:201:21)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/pborbely/.atom/packages/terminal-plus/node_modules/pty.js/index.js:2:18)
    at Module._compile (module.js:541:32)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:201:21)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/pborbely/.atom/packages/terminal-plus/lib/process.coffee:1:7)
    at Object.<anonymous> (/Users/pborbely/.atom/packages/terminal-plus/lib/process.coffee:1:1)
    at Module._compile (module.js:541:32)
    at Object.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:201:21)
    at Module.load (module.js:458:32)(anonymous function) @ task.coffee:86(anonymous function) @ task.coffee:146module.exports.Emitter.simpleDispatch @ emitter.js:25module.exports.Emitter.emit @ emitter.js:129(anonymous function) @ task.coffee:98emitTwo @ events.js:106emit @ events.js:191process.nextTick @ internal/child_process.js:719_combinedTickCallback @ internal/process/next_tick.js:67_tickCallback @ internal/process/next_tick.js:98
task.coffee:86 Cannot read property 'bind' of null TypeError: Cannot read property 'bind' of null
    at process.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/task-bootstrap.js:82:23)
    at emitTwo (events.js:106:13)
    at process.emit (events.js:191:7)
    at process.nextTick (internal/child_process.js:719:12)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)(anonymous function) @ task.coffee:86(anonymous function) @ task.coffee:146module.exports.Emitter.simpleDispatch @ emitter.js:25module.exports.Emitter.emit @ emitter.js:129(anonymous function) @ task.coffee:98emitTwo @ events.js:106emit @ events.js:191process.nextTick @ internal/child_process.js:719_combinedTickCallback @ internal/process/next_tick.js:67_tickCallback @ internal/process/next_tick.js:98
```

Also, I am on:

-  npm 3.10.3
- node 6.4.0 (system via nvm)

I hope this helps and great work btw - loving the plugin

**Comment by datafunk** [comment]
Sorry, it must have just happened to a bunch of peeps w/ 1.12.0, feel free to mark duplicate and close...
