### ISSUE TITLE
Update to Atom 1.12.0 seems to have broken terminal-plus

### ISSUE THREAD

**Issue by dbetebenner** [jeremyramin/terminal-plus#382]
Hello,

Just updated to latest version of Atom and terminal-plus no longer works:

1. Can open a new terminal-plus window in Atom but it's unresponsive regarding any keyboard input.

**Comment by robertrossmann** [comment]
Here's console output from Atom 1.12. Please note that I have made sure to rebuild native dependencies in Atom after the upgrade - Atom said all is well now. I have also tried reinstalling the package, but the problem persists.

I also tried going to `~/.atom/packages/terminal-plus` and doing `apm rebuild`, to no avail.

I wonder if `apm` has some cache that it uses when it reinstalls packages?

```
Cannot find module '../build/Release/pty.node'
Module version mismatch. Expected 49, got 46. Error: Module version mismatch. Expected 49, got 46.
    at Error (native)
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:168:20)
    at Object.Module._extensions..node (module.js:568:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:168:20)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/BeBe/.atom/packages/terminal-plus/node_modules/pty.js/lib/pty.js:17:9)
    at Module._compile (module.js:541:32)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:201:21)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/BeBe/.atom/packages/terminal-plus/node_modules/pty.js/index.js:2:18)
    at Module._compile (module.js:541:32)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:201:21)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/BeBe/.atom/packages/terminal-plus/lib/process.coffee:1:7)
    at Object.<anonymous> (/Users/BeBe/.atom/packages/terminal-plus/lib/process.coffee:1:1)
    at Module._compile (module.js:541:32)
    at Object.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:201:21)
    at Module.load (module.js:458:32)
Cannot read property 'bind' of null TypeError: Cannot read property 'bind' of null
    at process.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/task-bootstrap.js:82:23)
    at emitTwo (events.js:106:13)
    at process.emit (events.js:191:7)
    at process.nextTick (internal/child_process.js:719:12)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

**Comment by Fred-Barclay** [comment]
This is affecting a lot of us... #367 #366 #365 #362 #361 #359 #357 #353 #352 #351 

Until the developers get this fixed, there are some alternatives:
termination (shameless self-promotion) :wink:
tokamak-terminal
platformio-ide-terminal

**Comment by vantrav** [comment]
[After Atom Update 1.12.0, Just a blinking caret , does not show command prompt / directory location #383](https://github.com/jeremyramin/terminal-plus/issues/383)
1. Uninstall terminal-plus
2. `apm install LarsKumbier/terminal-plus`
3. Terminal's background-color  fix setting `background-color: transparent;` in standard.less (on Mac it's usually in ~/.atom/packages/terminal-plus/styles/themes/)
No idea if this works for Windows.

**Comment by brucezlata** [comment]
terminal-plus is broken after upgrading atom to 1.12.7

**Comment by yoavg-at-comigo** [comment]
[vantrav's workaround](https://github.com/jeremyramin/terminal-plus/issues/382#issuecomment-260108535) works for me on Atom 1.12.7 on Ubuntu
