### ISSUE TITLE
After Atom Update 1.12.0, Just a blinking caret , does not show directory location

### ISSUE THREAD

**Issue by anandvip** [jeremyramin/terminal-plus#383]
keyboard input does not show in terminal
@udyux Suggested (It worked for me).
> Uninstall terminal-plus
apm install LarsKumbier/terminal-plus
My terminal's background-color used to match Atom's theme but with this patch the background is black on standard profile. If you're as picky as I am, you can fix this by setting background-color: transparent; in standard.less (on Mac it's usually in ~/.atom/packages/terminal-plus/styles/themes/)
No idea if this works for Windows.

**Comment by mikebelanger** [comment]
Same here -- happened after I upgraded Atom to the latest version (1.12.0), and I followed its recommendation to rebuild this package -- pretty sure it had something to do with the upgrade.

**Comment by miquelbrazil** [comment]
Same issue for me too. :-(

**Comment by stefano-HH** [comment]
Same for me - as @mikebelanger discribed

**Comment by timdrichards** [comment]
I also encountered this problem. I tried to uninstall and reinstall and still does not show the terminal.

**Comment by nallie** [comment]
Same here

**Comment by izaera** [comment]
This is a duplicate of #382

**Comment by dr-data-dude** [comment]
same here

**Comment by Fred-Barclay** [comment]
This is affecting a lot of us... #367 #366 #365 #362 #361 #359 #357 #353 #352 #351 

Until the developers get this fixed, there are some alternatives:
termination (shameless self-promotion) :wink:
tokamak-terminal
platformio-ide-terminal

**Comment by raffi-minassian** [comment]
I'm seeing this too now. Same as described. After Atom updates, you get a message about rebuilding the package. After that, you get what everyone is describing. 

I tried uninstalling and reinstalling the package as well. That doesn't solve the problem. I'm happy to try anything else that would be helpful for solving the issue. In the meantime, I'll go back to using an external terminal window.

Thanks!

**Comment by udyux** [comment]
This solution worked for me (thanks @LarsKumbier), from #362:

macOS Sierra `10.12.1`
Atom `1.12.0`

Uninstall terminal-plus
`apm install LarsKumbier/terminal-plus`

My terminal's background-color used to match Atom's theme but with this patch the background is black on standard profile. If you're as picky as I am, you can fix this by setting `background-color: transparent;` in `standard.less` (on Mac it's usually in `~/.atom/packages/terminal-plus/styles/themes/`)

No idea if this works for Windows.

**Comment by promar93** [comment]
Thanks @udyux the completing the apm install again worked for my install, I used the material theme, so I didn't have to apply the style change to the less. I prefer it to stand out.

**Comment by madranet** [comment]
Another "me too".

Re-installing via `apm install LarsKumbier/terminal-plus` seems to have fixed it for me too, but Terminal-Plus is no longer showing up in Atom's "Installed Packages" pane. Is that normal behaviour? [I've only ever installed packages through the GUI before]

**Comment by LarsKumbier** [comment]
@madranet did you remove the old terminal-plus? If not, remove, install and rebuild via `apm`

**Comment by madranet** [comment]
Yes. I removed the old version first [via the GUI] then installed the new one via `apm`

**Comment by udyux** [comment]
@madranet it should be under "~~community installed packages~~ Git Packages" at the very bottom of the packages section.

**Comment by everhopingandwaiting** [comment]
![image](https://cloud.githubusercontent.com/assets/6021724/20219966/a98ef044-a866-11e6-87fa-8678f7c703cd.png)
task.coffee:86 Module version mismatch. Expected 49, got 46. Error: Module version mismatch. Expected 49, got 46.
    at Error (native)
    at process.module.(anonymous function) [as dlopen](ELECTRON_ASAR.js:168:20)
    at Object.Module._extensions..node (module.js:568:18)
    at Object.module.(anonymous function) [as .node](ELECTRON_ASAR.js:168:20)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/john/.atom/packages/terminal-plus/node_modules/pty.js/lib/pty.js:17:9)
    at Module._compile (module.js:541:32)
    at Object.value [as .js](/usr/share/atom-beta/resources/app.asar/src/compile-cache.js:201:21)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/john/.atom/packages/terminal-plus/node_modules/pty.js/index.js:2:18)
    at Module._compile (module.js:541:32)
    at Object.value [as .js](/usr/share/atom-beta/resources/app.asar/src/compile-cache.js:201:21)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/john/.atom/packages/terminal-plus/lib/process.coffee:1:7)
    at Object.<anonymous> (/home/john/.atom/packages/terminal-plus/lib/process.coffee:1:1)
    at Module._compile (module.js:541:32)
    at Object.value [as .coffee](/usr/share/atom-beta/resources/app.asar/src/compile-cache.js:201:21)
    at Module.load (module.js:458:32)(anonymous function) @ task.coffee:86(anonymous function) @ task.coffee:146module.exports.Emitter.simpleDispatch @ emitter.js:25module.exports.Emitter.emit @ emitter.js:129(anonymous function) @ task.coffee:98emitTwo @ events.js:106emit @ events.js:191process.nextTick @ internal/child_process.js:719_combinedTickCallback @ internal/process/next_tick.js:67_tickCallback @ internal/process/next_tick.js:98
task.coffee:86 Cannot read property 'bind' of null TypeError: Cannot read property 'bind' of null
    at process.<anonymous> (/usr/share/atom-beta/resources/app.asar/src/task-bootstrap.js:82:23)
    at emitTwo (events.js:106:13)
    at process.emit (events.js:191:7)
    at process.nextTick (internal/child_process.js:719:12)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)(anonymous function) @ task.coffee:86(anonymous function) @ task.coffee:146module.exports.Emitter.simpleDispatch @ emitter.js:25module.exports.Emitter.emit @ emitter.js:129(anonymous function) @ task.coffee:98emitTwo @ events.js:106emit @ events.js:191process.nextTick @ internal/child_process.js:719_combinedTickCallback @ internal/process/next_tick.js:67_tickCallback @ internal/process/next_tick.js:98

**Comment by anandvip** [comment]
@udyux Thanks

**Comment by madranet** [comment]
> @madranet did you remove the old terminal-plus? If not, remove, install and rebuild via apm

Nope. Not showing up, when installed via `apm`

![2016-11-11_17-13-24](https://cloud.githubusercontent.com/assets/669658/20223577/321cf986-a832-11e6-9fc5-0ac0c5f2b19f.png)

No biggie. Just makes it a bit difficult to know when an update's available.

**Comment by bethdehart** [comment]
@madranet if you search in the gui for "termini" you will see the installed page under git. 

Hope this helps.

![image](https://cloud.githubusercontent.com/assets/6137749/20233561/ad051b7c-a825-11e6-867c-aa6c7aa5a820.png)

**Comment by jameswilliamknight** [comment]
problem solved installing via apm. 

`apm install LarsKumbier/terminal-plus`

not sure how necessary the `LarsKumbier/` portion was.
