### ISSUE TITLE
atom 1.12.2

### ISSUE THREAD

**Issue by tmsincomb** [jeremyramin/terminal-plus#386]
I use the terminal you made everyday and I greatly appreciate it. It seems to have crashed for the new atom update however.

**Comment by jercle** [comment]
I initially had to recompile for the new version, but now just getting a blank terminal box
<img width="636" alt="screenshot of atom 12-11-16 6 40 55 pm" src="https://cloud.githubusercontent.com/assets/10472533/20236383/9cb66edc-a907-11e6-8e4b-678525def9d4.png">

**Comment by vantrav** [comment]
[After Atom Update 1.12.0, Just a blinking caret , does not show command prompt / directory location #383](https://github.com/jeremyramin/terminal-plus/issues/383)
1. Uninstall terminal-plus
2. `apm install LarsKumbier/terminal-plus`
3. Terminal's background-color  fix setting `background-color: transparent;` in standard.less (on Mac it's usually in ~/.atom/packages/terminal-plus/styles/themes/)
No idea if this works for Windows.

**Comment by h0r0m4n** [comment]
I’m having same issue of @jERCle

**Comment by sayaamirul** [comment]
Im using platformio ide terminal while waiting this fixed hehe

**Comment by Fred-Barclay** [comment]
I'm using [termination](https://atom.io/packages/termination) while waiting (shameless self plug) and I know that platformio ide terminal works as well.

**Comment by peterschmidler** [comment]
same here, atom console says:

``` shell
Cannot find module '../build/Release/pty.node'
task.coffee:86 Module version mismatch. Expected 49, got 46. Error: Module version mismatch. Expected 49, got 46.
    at Error (native)
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:168:20)
    at Object.Module._extensions..node (module.js:568:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:168:20)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/admin/.atom/packages/terminal-plus/node_modules/pty.js/lib/pty.js:17:9)
    at Module._compile (module.js:541:32)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:201:21)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/admin/.atom/packages/terminal-plus/node_modules/pty.js/index.js:2:18)
    at Module._compile (module.js:541:32)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:201:21)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/admin/.atom/packages/terminal-plus/lib/process.coffee:1:7)
    at Object.<anonymous> (/Users/admin/.atom/packages/terminal-plus/lib/process.coffee:1:1)
    at Module._compile (module.js:541:32)
    at Object.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:201:21)
    at Module.load (module.js:458:32)(anonymous function) @ task.coffee:86(anonymous function) @ task.coffee:146module.exports.Emitter.simpleDispatch @ emitter.js:25module.exports.Emitter.emit @ emitter.js:129(anonymous function) @ task.coffee:98emitTwo @ events.js:106emit @ events.js:191process.nextTick @ internal/child_process.js:719_combinedTickCallback @ internal/process/next_tick.js:67_tickCallback @ internal/process/next_tick.js:98
task.coffee:86 Cannot read property 'bind' of null TypeError: Cannot read property 'bind' of null
    at process.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/task-bootstrap.js:82:23)
    at emitTwo (events.js:106:13)
    at process.emit (events.js:191:7)
    at process.nextTick (internal/child_process.js:719:12)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)(anonymous function) @ task.coffee:86(anonymous function) @ task.coffee:146module.exports.Emitter.simpleDispatch @ emitter.js:25module.exports.Emitter.emit @ emitter.js:129(anonymous function) @ task.coffee:98emitTwo @ events.js:106emit @ events.js:191process.nextTick @ internal/child_process.js:719_combinedTickCallback @ internal/process/next_tick.js:67_tickCallback @ internal/process/next_tick.js:98
package.coffee:395 Error serializing package 'pp' TypeError: Cannot read property 'length' of undefined
    at Object.serialize (/Users/admin/.atom/packages/pp/lib/pp.coffee:489:5)
    at Package.module.exports.Package.serialize (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:643:97)
    at PackageManager.module.exports.PackageManager.serializePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:606:63)
    at PackageManager.module.exports.PackageManager.serialize (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:599:14)
    at AtomEnvironment.module.exports.AtomEnvironment.serialize (/Applications/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:810:38)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:1015:27
    at AtomEnvironment.module.exports.AtomEnvironment.saveState (/Applications/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:1011:14)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:316:28
```

**Comment by bsodmike** [comment]
Same here, thanks.
