### ISSUE TITLE
Terminal-lus stop work after atom updates

### ISSUE THREAD

**Issue by AtNovember** [jeremyramin/terminal-plus#394]
![Terminal stop working after atom updates =( ](https://cloud.githubusercontent.com/assets/14091538/20421309/774c3630-ad7c-11e6-8ec4-1e913f0becb2.png)

**Comment by Louis-Tian** [comment]
Same here. Atom@1.12.4 and terminal-plus@0.14.5

**Comment by Louis-Tian** [comment]
duplicate #392

**Comment by Fred-Barclay** [comment]
It is a problem that's been cropping up a lot. :slightly_frowning_face: 
Hopefully the developer will get it fixed soon, but in the meantime I'm using [termination](https://atom.io/packages/termination) while waiting (shameless self plug) and I know that platformio ide terminal works as well.

**Comment by sonnyg** [comment]
Here is the trace output from Atom:

task.coffee:86 Module version mismatch. Expected 49, got 46. Error: Module version mismatch. Expected 49, got 46.
    at Error (native)
    at process.module.(anonymous function) [as dlopen](ELECTRON_ASAR.js:168:20)
    at Object.Module._extensions..node (module.js:583:18)
    at Object.module.(anonymous function) [as .node](ELECTRON_ASAR.js:168:20)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/songeorge/.atom/packages/terminal-plus/node_modules/pty.js/lib/pty.js:17:9)
    at Module._compile (module.js:556:32)
    at Object.value [as .js](/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:201:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/songeorge/.atom/packages/terminal-plus/node_modules/pty.js/index.js:2:18)
    at Module._compile (module.js:556:32)
    at Object.value [as .js](/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:201:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/songeorge/.atom/packages/terminal-plus/lib/process.coffee:1:7)
    at Object.<anonymous> (/Users/songeorge/.atom/packages/terminal-plus/lib/process.coffee:1:1)
    at Module._compile (module.js:556:32)
    at Object.value [as .coffee](/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:201:21)
    at Module.load (module.js:473:32)(anonymous function) @ task.coffee:86(anonymous function) @ task.coffee:146module.exports.Emitter.simpleDispatch @ emitter.js:25module.exports.Emitter.emit @ emitter.js:129(anonymous function) @ task.coffee:98emitTwo @ events.js:106emit @ events.js:191process.nextTick @ internal/child_process.js:744_combinedTickCallback @ internal/process/next_tick.js:67_tickCallback @ internal/process/next_tick.js:98
task.coffee:86 Cannot read property 'bind' of null TypeError: Cannot read property 'bind' of null
    at process.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/task-bootstrap.js:82:23)
    at emitTwo (events.js:106:13)
    at process.emit (events.js:191:7)
    at process.nextTick (internal/child_process.js:744:12)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)

**Comment by yyhappynice** [comment]
stop work after atom updates

**Comment by alpha090** [comment]
Not really sure but one of the following solved this problem for me...
Uninstall, then reinstall it -> did not help 
Run directly C:\Users\{Your user name}\AppData\Local\atom\app-1.12.4\atom.exe
Then, I could see some loading errors of terminal-plus, open to see the errors, then just pused rebuilding this package and after it finished restart atom -> the problem seems to be fixed...

**Comment by willin** [comment]
+1

**Comment by zhimeihetx** [comment]
as the same too

**Comment by maddinq** [comment]
same for me

**Comment by prallin** [comment]
+1

**Comment by omjrt88** [comment]
Same here...

**Comment by xldrkp** [comment]
Same for me.

**Comment by smtl** [comment]
Same here

**Comment by Jackeriss** [comment]
+10086

**Comment by calumpeak** [comment]
+1

**Comment by Jackeriss** [comment]
But I found [platformio-ide-terminal](https://atom.io/packages/platformio-ide-terminal) still works!

**Comment by dsturm** [comment]
+1

**Comment by svikhristyuk** [comment]
+1

**Comment by nicholasbutlin** [comment]
+1

**Comment by Faezehyas** [comment]
same for me
