### ISSUE TITLE
Module version mismatch. Expected 49, got 46

### ISSUE THREAD

**Issue by hzuosit** [jeremyramin/terminal-plus#395]

**Comment by JonMontgo** [comment]
I'm having this same issue. Has anyone had this issue that doesn't have mac osx?

**Comment by ghost** [comment]
Having same issue on Mac OS 10.12.1 and Atom 1.12.5

**Comment by marcomontalbano** [comment]
I'm having the same issue on Mac OSX 10.11.6 and Atom 1.12.3

**Comment by scaccogatto** [comment]
Me too:
Arch Linux x64 - Atom: 1.12.5

```
Cannot find module '../build/Release/pty.node'
task.coffee:86 Module version mismatch. Expected 49, got 46. Error: Module version mismatch. Expected 49, got 46.
    at Error (native)
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:168:20)
    at Object.Module._extensions..node (module.js:583:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:168:20)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/gatto/.atom/packages/terminal-plus/node_modules/pty.js/lib/pty.js:17:9)
    at Module._compile (module.js:556:32)
    at Object.value [as .js] (/usr/share/atom/resources/app.asar/src/compile-cache.js:201:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/gatto/.atom/packages/terminal-plus/node_modules/pty.js/index.js:2:18)
    at Module._compile (module.js:556:32)
    at Object.value [as .js] (/usr/share/atom/resources/app.asar/src/compile-cache.js:201:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/gatto/.atom/packages/terminal-plus/lib/process.coffee:1:7)
    at Object.<anonymous> (/home/gatto/.atom/packages/terminal-plus/lib/process.coffee:1:1)
    at Module._compile (module.js:556:32)
    at Object.value [as .coffee] (/usr/share/atom/resources/app.asar/src/compile-cache.js:201:21)
    at Module.load (module.js:473:32)(anonymous function) @ task.coffee:86(anonymous function) @ task.coffee:146module.exports.Emitter.simpleDispatch @ emitter.js:25module.exports.Emitter.emit @ emitter.js:129(anonymous function) @ task.coffee:98emitTwo @ events.js:106emit @ events.js:191process.nextTick @ internal/child_process.js:744_combinedTickCallback @ internal/process/next_tick.js:67_tickCallback @ internal/process/next_tick.js:98
task.coffee:86 Cannot read property 'bind' of null TypeError: Cannot read property 'bind' of null
    at process.<anonymous> (/usr/share/atom/resources/app.asar/src/task-bootstrap.js:82:23)
    at emitTwo (events.js:106:13)
    at process.emit (events.js:191:7)
    at process.nextTick (internal/child_process.js:744:12)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

**Comment by sebszocinski** [comment]
+1 here

**Comment by pauljamescleary** [comment]
having the same issue

**Comment by lixinliang** [comment]
+1
atom 1.12.3
apm  1.12.9
npm  3.10.5
node 4.4.5
python 2.7.10
git 2.8.4

It's not work any more from long long ago.
Terminal-plus is useful and powerful.
Hopes to keep on maintenance release.

**Comment by sunziping2016** [comment]
+1

**Comment by Quanjiang** [comment]
+1

**Comment by elvijs** [comment]
+1

**Comment by savatia** [comment]
+1

**Comment by unrevised6419** [comment]
Hit rebuild button in notification, and restart atom. And it worked.

**Comment by d3v-null** [comment]
Same issue here
apm  1.18.1
npm  3.10.10
node 6.9.5 x64
python 2.7.13
git 2.11.0

**Comment by longshaoye180** [comment]
+1

**Comment by pjehan** [comment]
Same on Ubuntu 16.04
atom 1.18.0
apm  1.18.1
npm  3.10.10
node 6.9.5 x64
python 2.7.11
git 2.7.4
