### ISSUE TITLE
in atom terminal plus isn't showing up 

### ISSUE THREAD

**Issue by vamc05** [jeremyramin/terminal-plus#397]
atom
<img width="1440" alt="screen shot 2016-11-21 at 1 23 18 pm" src="https://cloud.githubusercontent.com/assets/13224555/20495113/c1ef23b4-afed-11e6-9069-9fbf594cdf9a.png">
 terminal plus isn't showing up, i have uninstall and same all well it doesn't show up

**Comment by gandhiShepard** [comment]
Yeah, I'm getting this same issue too. If you click on the pink bug icon in the bottom right of your screen shot, you can click to "rebuild" the package. This made TerminalPlus show again. But I can't type in the window. No text input appears. 

I do see some error when I open up the inspector. I assume that there were some breaking changes with the latest version of Atom.

BTW, this is an excellent Atom plugin!

**Comment by lankford** [comment]
I think it is happening to me as well... I can open a terminal window, but no prompt... just a flashing cursor block... cannot type into it.

**Comment by smtl** [comment]
@lankford I am having the same issue. Just installed on version 1.12.5

**Comment by gandhiShepard** [comment]
So this is the error I see in the Inspector: 

/Applications/Atom.app/Contents/Resources/app.asar/src/task.js:52 
Module version mismatch. 
Expected 49, got 46. Error: Module version mismatch. Expected 49, got 46.

I'm guessing that this is a core issue? I tried following the path and I didn't find a app.asar directory anywhere

**Comment by micage** [comment]
The file "~/.atom/packages/terminal-plus/node_modules/pty.js/build/Release/pty.node" is missing. Probably because of node-gyp can not build it. There is also a build error log with a lot of deprecation warnings. Copying pty.node from an older version didn't help either. May installing an older version will work until the issue has been fixed.

**Comment by micage** [comment]
Solution (that worked for me):

In `~/.atom/packages/terminal-plus/package.json` in the dependencies section 
remove the commit id (#......) at the end of the `pty.js` entry:

`"pty.js": "git+https://github.com/jeremyramin/pty.js.git#28f2667"` becomes
`"pty.js": "git+https://github.com/jeremyramin/pty.js.git"`

`cd ~/.atom/packages/terminal-plus/`
`npm install`
`apm rebuild`

Restart Atom, should be it ;)

**Comment by sfauvart** [comment]
Hello,

I have the same issue on atom v1.12.5 and terminal-plus v0.14.5.

The solution of @micage (thanks! :+1: ) work for me :

edit **l.47** of **.atom/packages/terminal-plus/package.json**

"pty.js": "git+https://github.com/jeremyramin/pty.js.git#28f2667", becomes
"pty.js": "git+https://github.com/jeremyramin/pty.js.git",

run **npm install && apm rebuild** on **.atom/packages/terminal-plus/** directory

restart atom ide, it's ok.

**Comment by gandhiShepard** [comment]
That worked! @micage @sfauvart Thanks dewds!

![200](https://cloud.githubusercontent.com/assets/8546059/20524710/50a7bac4-b081-11e6-9bde-c9d2cb121c2c.gif)

**Comment by DrewEdwards** [comment]
@sfauvart Worked for me as well! Thanks for the help!

**Comment by Vrakfall** [comment]
WOW!

I just installed the package a few days ago and it never worked until I tried this. I thought my python was causing all this because of `python3` not being supported by `node-gyp` and that my `python2` wasn't really used. (I'm on Archlinux.) Looks like I was wrong.

Thank you again!

**Comment by kupoback** [comment]
Fo me, I followed @sfauvart 's advice however, I can't npm install, whether using sudo or not. This is my error when I sudo.

    npm ERR! unpack Could not read data for terminal-plus@0.14.5
    npm ERR! Darwin 16.3.0
    npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
    npm ERR! node v6.2.1
    npm ERR! npm  v3.9.3
    npm ERR! code E404

    npm ERR! 404 Registry returned 404 for GET on https://registry.npmjs.org/terminal-plus
    npm ERR! 404 
    npm ERR! 404  'terminal-plus' is not in the npm registry.
    npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
    npm ERR! 404 
    npm ERR! 404 Note that you can also install from a
    npm ERR! 404 tarball, folder, http url, or git url.

    npm ERR! Please include the following file with any support request:
    npm ERR!     /Users/Bug/.atom/packages/terminal-plus/npm-debug.log

Is there something I am misunderstanding? Should  I just download the .zip file and install that way?

**Comment by Vrakfall** [comment]
What command are you calling where?
It looks like you're trying to do a `npm install terminal-plus` inside `~.atom/packages/terminal-plus/` which is, of course, redundant. You might also have `terminal-plus` in a `package.json`, somewhere, as a dependency. Check on that.

What you should simply do is:

1. Close `atom`
2. Change the said line
3. Do the following commands

```bash
cd ~/.atom/packages/terminal-plus/
npm install
apm rebuild
```

4. Restart `atom`

`npm install` will go read the required dependencies in the `package.json` file and install them. This is the normal behaviour when you pass no argument to it.

If you're a yarn user, you might also prefer using `yarn install --prod` instead of `npm install`.

**Edit:** On a side note: you shouldn't use `sudo` when installing packages locally (in a project directory tree).

**Comment by kupoback** [comment]
That's exactly what I initially did.

**Comment by kupoback** [comment]
@Vrakfall That is exactly what I did last time. Whether I used sudo to npm install or not, the outcome was the same. With that, I am familiar with node.js and using it. I'm just asking if there was something I am missing for the install. I noticed the author asked up to install a separate entity prior to using his plugin, which I also did to try and resolve the issue. None the less, I just returned to using the terminal. Below are my errors though

    Last login: Tue Nov 22 16:15:17 on ttys000
    Nicks-MacBook-Pro:~ Bug$ cd ~/.atom/packages/terminal-plus/
    Nicks-MacBook-Pro:terminal-plus Bug$ sudo npm install
    Password:
    npm ERR! unpack Could not read data for terminal-plus@0.14.5
    npm ERR! Darwin 16.3.0
    npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
    npm ERR! node v6.2.1
    npm ERR! npm  v3.9.3
    npm ERR! code E404

    npm ERR! 404 Registry returned 404 for GET on https://registry.npmjs.org/terminal-plus
    npm ERR! 404 
    npm ERR! 404  'terminal-plus' is not in the npm registry.
    npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
    npm ERR! 404 
    npm ERR! 404 Note that you can also install from a
    npm ERR! 404 tarball, folder, http url, or git url.

    npm ERR! Please include the following file with any support request:
    npm ERR!     /Users/Bug/.atom/packages/terminal-plus/npm-debug.log
    Nicks-MacBook-Pro:terminal-plus Bug$ 


    Nicks-MacBook-Pro:terminal-plus Bug$ npm install
    npm ERR! unpack Could not read data for terminal-plus@0.14.5
    npm ERR! Darwin 16.3.0
    npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
    npm ERR! node v6.2.1
    npm ERR! npm  v3.9.3
    npm ERR! code E404

    npm ERR! 404 Registry returned 404 for GET on https://registry.npmjs.org/terminal-plus
    npm ERR! 404 
    npm ERR! 404  'terminal-plus' is not in the npm registry.
    npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
    npm ERR! 404 
    npm ERR! 404 Note that you can also install from a
    npm ERR! 404 tarball, folder, http url, or git url.

    npm ERR! Please include the following file with any support request:
    npm ERR!     /Users/Bug/.atom/packages/terminal-plus/npm-debug.log
    Nicks-MacBook-Pro:terminal-plus Bug$

**Comment by Vrakfall** [comment]
@kupoback Sorry, I was only able to assume what happened based on the few information I had and the way I was able to reproduce it.

What is in your `package.json` tho? It looks very weird that npm still tries to download `terminal-plus` by just using `npm install`.

**Comment by sfauvart** [comment]
@kupoback Can you try to uninstall the terminal-plus plugin via the control panel of atom.
After that, reinstall them and retry the trick.
Like @Vrakfall said, it's looks very weird that npm still tries to download terminal-plus.
Note: It's not safe/good practice to run npm as sudo.

**Comment by a7madgamal** [comment]
thanks everyone for the solutions, but what about fixing it? :D
It's making the package useless!

**Comment by kupoback** [comment]
@Vrakfall : This is my JSON package. https://codeshare.io/ORDfT

@sfauvart : I tried that also, to no avail. I am going to try and download the repo and drop the folder in there to see if that'll do

EDIT: Here is an update after I unzipped the repo. I was still unable to install and rebuild the package. This is the new JSON package. https://codeshare.io/5RyVo2

**Comment by gibffe** [comment]
Any update on this ? This plugin does not work out of the box with latest Atom.

**Comment by Vrakfall** [comment]
@kupoback Weirder and weirder. Is it possible that any of your `npm` projects/modules contains your `.atom` folder in some way? I mean, mostly being on top of if or by directory linkings, even some `$PATH` or environment variables can come into play.

There's definitely something trying to force you install `terminal-plus` into your `terminal-plus` folder, which is quite paradoxal. :stuck_out_tongue_closed_eyes: 

Would you mind trying to move your directory somewhere else, somewhere freer of interferences, and try to `npm install` there? Then move it back in and do a `apm rebuild` inside the same directory.

@gibffe I think it's just a matter of time before the contributors finally notice this issue. ;D

**Comment by kupoback** [comment]
@Vrakfall It is. I mean, I can run npm install on any repo that I started, that has a package.json file in it. But not this one.

Tried it in two spots, the .atom root and my Downloads folder to no avail. :\

    Nicks-MacBook-Pro:~ Bug$ cd ~/.atom/__terminal-plus/
    Nicks-MacBook-Pro:__terminal-plus Bug$ npm install
    npm ERR! unpack Could not read data for terminal-plus@0.14.5
    npm ERR! Darwin 16.3.0
    npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
    npm ERR! node v6.2.1
    npm ERR! npm  v3.9.3
    npm ERR! code E404

    npm ERR! 404 Registry returned 404 for GET on https://registry.npmjs.org/terminal-plus
    npm ERR! 404 
    npm ERR! 404  'terminal-plus' is not in the npm registry.
    npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
    npm ERR! 404 
    npm ERR! 404 Note that you can also install from a
    npm ERR! 404 tarball, folder, http url, or git url.

    npm ERR! Please include the following file with any support request:
    npm ERR!     /Users/Bug/.atom/__terminal-plus/npm-debug.log
    Nicks-MacBook-Pro:__terminal-plus Bug$ cd ~/Downloads/__terminal-plus/
    Nicks-MacBook-Pro:__terminal-plus Bug$ npm install
    npm ERR! unpack Could not read data for terminal-plus@0.14.5
    npm ERR! Darwin 16.3.0
    npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
    npm ERR! node v6.2.1
    npm ERR! npm  v3.9.3
    npm ERR! code E404
    
    npm ERR! 404 Registry returned 404 for GET on https://registry.npmjs.org/terminal-plus
    npm ERR! 404 
    npm ERR! 404  'terminal-plus' is not in the npm registry.
    npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
    npm ERR! 404 
    npm ERR! 404 Note that you can also install from a
    npm ERR! 404 tarball, folder, http url, or git url.

    npm ERR! Please include the following file with any support request:
    npm ERR!     /Users/Bug/Downloads/__terminal-plus/npm-debug.log

**Comment by Vrakfall** [comment]
@kupoback Let's see if your `npm-debug.log`s can tell us more about it.

**Comment by kupoback** [comment]
@Vrakfall: https://codeshare.io/aVOJPG

**Comment by Vrakfall** [comment]
What if you do `node-gyp -v`?
You mentioned the package's dependencies, are sure you skipped nothing [in here](https://www.npmjs.com/package/node-gyp)?

We can also try by using [yarn](https://yarnpkg.com/en/docs/install) and see what happens when you `yarn install` instead of `npm install`?

**Comment by kupoback** [comment]
I'll try yarn, but I did do node-gyp -v. Running V 3.9.3 I'll report back with an edit

EDIT: Back in business. yarn install worked just fine. Wonder now if there is something wrong with my npm...

**Comment by Vrakfall** [comment]
@kupoback That version doesn't even exist. Last one seems to be `3.4.0`.
[https://github.com/nodejs/node-gyp/releases](https://github.com/nodejs/node-gyp/releases)

Try to reinstall it.

Glad to hear it worked. ^^ This is probably because of the way yarn works, it is deterministic.

On a side note for later, if you plan on keeping yarn, here's a time-saver reminder: don't try to install packages globally with it, yet, because of this: [#1060](https://github.com/yarnpkg/yarn/issues/1060).

**Comment by kupoback** [comment]
Weird that it said that version when I installed it last night. Glad it's working though. Should reinstall npm just in case, or maybe just leave it to yarn.


Thank you for the tidbit on #1060!

**Comment by Vrakfall** [comment]
@kupoback You're welcome. ^^

I was thinking about reinstalling `node-gyp` but a `npm` reinstallation may also be useful. ^^

Enjoy! :sunglasses:

**Comment by diruuu** [comment]
Got same problem like @kupoback. I solved it by removed all unnecessary params on `package.json`. So it looks like this:
```
{
  "author": {
    "name": "Jeremy Ebneyamin"
  },
  "bugs": {
    "url": "https://github.com/jeremyramin/terminal-plus/issues"
  },
  "dependencies": {
    "atom-space-pen-views": "^2.1.0",
    "pty.js": "git+https://github.com/jeremyramin/pty.js.git",
    "term.js": "git+https://github.com/jeremyramin/term.js.git",
    "underscore": "^1.8.3"
  },
  "description": "A terminal package for Atom, complete with themes and more.",
  "devDependencies": {},
  "engines": {
    "atom": ">=1.2.0"
  },
  "homepage": "https://atom.io/packages/terminal-plus",
  "keywords": [
    "terminal-plus",
    "terminal",
    "plus",
    "panel",
    "tty"
  ],
  "license": "MIT",
  "main": "./lib/terminal-plus",
  "name": "terminal-plus",
  "optionalDependencies": {},
  "repository": {
    "type": "git",
    "url": "git+https://github.com/jeremyramin/terminal-plus.git"
  }
}
```

then ran `npm install && apm rebuild` on .atom/packages/terminal-plus/ directory

restart atom ide, and the terminal-plus got back to the business

**Comment by MacKentoch** [comment]
Thanks so much @micage and @sfauvart!!!

**Comment by dxiaogang** [comment]
The solution of @micage (thanks! 👍 ) work for me too,thanks !

**Comment by UncleVic** [comment]
Sorry, maybe I'm stupid, but I can't do it.

macOS 10.12.1, Atom 1.12.6, node-gyp 3.4.0, node v7.2.0, npm  v3.10.9

I've done that

1. Close atom
2. Change the said line
3. Do the following commands
```
cd ~/.atom/packages/terminal-plus/
npm install
apm rebuild
```
4. Restart atom

But I see black screen and blincking cursor ;(
What am I doing wrong? 

platformio-ide-terminal dosen't work too.

**Comment by ashishwadekar** [comment]
@diruuu Thanks for the solution. Worked like a charm. Cheers 👍

**Comment by mylastore** [comment]
on ARCH LINUX 

I did the above and still have the same error and plus all terminal packages I install on Atom do not work I am new to Atom and can't understand why the most important package is not build in just like all the other IDE's well is free so can't complained about not been perfect. 


```gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:210:5)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Linux 5.3.8-arch1-1
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/oquinteros/.atom/packages/terminal-plus/node_modules/pty.js
gyp ERR! node -v v12.13.0
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! pty.js@0.3.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the pty.js@0.3.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
```

**Comment by sagarujjwal** [comment]
Thankyou very much. I have spend almost 1 hour to find the solution but didn't get much.
you have solved my problem :)
