### ISSUE TITLE
Blinking caret

### ISSUE THREAD

**Issue by marchank0** [jeremyramin/terminal-plus#399]
Win 10 x64
Atom 1.12.5

***/pty.js/builderror.log**
```
gyp ERR! build error 
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\aleks\AppData\Local\atom\app-1.12.5\resources\app\apm\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Windows_NT 10.0.14393
gyp ERR! command "C:\\Users\\aleks\\AppData\\Local\\atom\\app-1.12.5\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\aleks\\AppData\\Local\\atom\\app-1.12.5\\resources\\app\\apm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\aleks\AppData\Local\Temp\apm-install-dir-1161023-8928-s18ko8\node_modules\terminal-plus\node_modules\pty.js
gyp ERR! node -v v4.4.5
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok  
```

**Comment by iamchathu** [comment]
Same here after update it required to rebuild after that it only shows blinking caret

**Comment by keepcosmos** [comment]
same here!

**Comment by migaber** [comment]
#402 follow solution here
