### ISSUE TITLE
Crash on load after updating to latest version

### ISSUE THREAD

**Issue by JestonBlu** [jeremyramin/terminal-plus#41]
Cannot read property 'scripts' of null in C:\Users\blubaj\.atom\packages\terminal-plus\package.json
Hide Stack Trace
TypeError: Cannot read property 'scripts' of null
  at normalize (C:\Users\blubaj\AppData\Local\atom\app-1.0.19\resources\app.asar\node_modules\normalize-package-data\lib\normalize.js:25:11)
  at Function.module.exports.Package.normalizeMetadata (C:\Users\blubaj\AppData\Local\atom\app-1.0.19\resources\app.asar\src\package.js:50:9)
  at Function.module.exports.Package.loadMetadata (C:\Users\blubaj\AppData\Local\atom\app-1.0.19\resources\app.asar\src\package.js:70:18)
  at PackageManager.module.exports.PackageManager.loadPackage (C:\Users\blubaj\AppData\Local\atom\app-1.0.19\resources\app.asar\src\package-manager.js:388:39)
  at PackageManager.module.exports.PackageManager.loadPackages (C:\Users\blubaj\AppData\Local\atom\app-1.0.19\resources\app.asar\src\package-manager.js:369:14)
  at Atom.module.exports.Atom.startEditorWindow (C:\Users\blubaj\AppData\Local\atom\app-1.0.19\resources\app.asar\src\atom.js:667:21)
  at Object.<anonymous> (C:\Users\blubaj\AppData\Local\atom\app-1.0.19\resources\app.asar\src\window-bootstrap.js:12:8)
  at Object.<anonymous> (C:\Users\blubaj\AppData\Local\atom\app-1.0.19\resources\app.asar\src\window-bootstrap.js:23:4)
  at Module._compile (module.js:428:26)
  at Object.defineProperty.value [as .js] (C:\Users\blubaj\AppData\Local\atom\app-1.0.19\resources\app.asar\src\compile-cache.js:169:21)
  at Module.load (module.js:353:32)
  at Function.Module._load (module.js:308:12)
  at Module.require (module.js:363:17)
  at require (module.js:382:17)
  at setupWindow (file:///C:/Users/blubaj/AppData/Local/atom/app-1.0.19/resources/app.asar/static/index.js:82:25)
  at window.onload (file:///C:/Users/blubaj/AppData/Local/atom/app-1.0.19/resources/app.asar/static/index.js:35:9)
  at C:\Users\blubaj\.atom\packages\terminal-plus\package.json:1:1

**Comment by JestonBlu** [comment]
Did not have the correct dependencies installed.
