### ISSUE TITLE
isn't running on debian

### ISSUE THREAD

**Issue by otgo** [jeremyramin/terminal-plus#414]

**Comment by gnrlbzik** [comment]
should really consider adding details, this ticket is not helpful...

**Comment by otgo** [comment]
I open the terminal and just show the color black XDD nothing

**Comment by weirdan** [comment]
Same problem observed, here's the stack trace:
```
task.coffee:86 Module version mismatch. Expected 49, got 46. Error: Module version mismatch. Expected 49, got 46.
    at Error (native)
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:168:20)
    at Object.Module._extensions..node (module.js:583:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:168:20)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/weirdan/.atom/packages/terminal-plus/node_modules/pty.js/lib/pty.js:17:9)
    at Module._compile (module.js:556:32)
    at Object.value [as .js] (/usr/share/atom/resources/app.asar/src/compile-cache.js:201:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/weirdan/.atom/packages/terminal-plus/node_modules/pty.js/index.js:2:18)
    at Module._compile (module.js:556:32)
    at Object.value [as .js] (/usr/share/atom/resources/app.asar/src/compile-cache.js:201:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/weirdan/.atom/packages/terminal-plus/lib/process.coffee:1:7)
    at Object.<anonymous> (/home/weirdan/.atom/packages/terminal-plus/lib/process.coffee:1:1)
    at Module._compile (module.js:556:32)
    at Object.value [as .coffee] (/usr/share/atom/resources/app.asar/src/compile-cache.js:201:21)
```

**Comment by raha1923** [comment]
i'm on ubuntu 15.04 and i have this problem too

**Comment by weirdan** [comment]
@mohammadRaHa  see #201
rm node_modules + npm install + apm rebuild worked for me. There's also suggestions about alternative fork, which seems to work for some people, but I haven't tried that.
