### ISSUE TITLE
Failed to activate the terminal-plus package

### ISSUE THREAD

**Issue by kn9ts** [jeremyramin/terminal-plus#43]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.19
**System**: Mac OS X 10.11
**Thrown From**: [terminal-plus](https://github.com/jeremyramin/terminal-plus) package, v0.11.1

### Stack Trace

Failed to activate the terminal-plus package

```
At Cannot find module 'space-pen'

Error: Cannot find module 'space-pen'
    at Module._resolveFilename (module.js:334:15)
    at Function.Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:284:25)
    at Module.require (module.js:363:17)
    at require (module.js:382:17)
    at Object.<anonymous> (/Users/jheneknights/.atom/packages/terminal-plus/node_modules/atom-space-pen-views/lib/main.js:4:10)
    at Object.<anonymous> (/Users/jheneknights/.atom/packages/terminal-plus/node_modules/atom-space-pen-views/lib/main.js:22:4)
    at Module._compile (module.js:428:26)
    at Object.defineProperty.value [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:169:21)
    at Module.load (module.js:353:32)
    at Function.Module._load (module.js:308:12)
    at Module.require (module.js:363:17)
    at require (module.js:382:17)
    at Object.<anonymous> (/Users/jheneknights/.atom/packages/terminal-plus/lib/status-bar.coffee:2:13)
    at Object.<anonymous> (/Users/jheneknights/.atom/packages/terminal-plus/lib/status-bar.coffee:1:1)
    at Module._compile (module.js:428:26)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "atom-terminal-panel",
      "wrap-guide",
      "markdown-format"
    ],
    "themes": [
      "one-dark-ui",
      "sepia-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-beautify, vundefined
atom-jade, v0.3.0
autocomplete-php, v0.3.7
color-picker, v2.0.13
editorconfig, v1.2.0
file-icons, v1.6.10
file-type-icons, v0.7.3
go-plus, v3.5.1
go-runtime, v0.2.0
jsformat, v0.9.0
jshint, v1.8.1
language-docker, v1.1.3
language-mongodb, v0.2.0
language-protobuf, v0.5.0
linter, v1.8.1
linter-golinter, v1.0.0
linter-php, v1.0.5
minimap, v4.13.4
pigments, v0.18.0
pretty-json, v0.4.1
sepia-syntax, v1.0.5
terminal-panel, v1.14.1
terminal-plus, v0.11.1
travis-ci-status, v0.18.0
wakatime, v5.0.0

# Dev
No dev packages
```

**Comment by jeremyramin** [comment]
@kn9ts You might want to reinstall Terminal-Plus. It seems like you did not get all of the dependencies installed properly.

**Comment by kn9ts** [comment]
Ok. Let me do that and try see if the same errors spawn again

**Comment by jeremyramin** [comment]
Did that work for you?

**Comment by kn9ts** [comment]
Yeah it did work for me, it re-installed flawlessly.

| Eugene Mutai [Software Engineer | Andela] <http://andela.com/>
| Twitter/Github: @kn9ts <http://www.twitter.com/kn9ts>
| About me: http://kn9ts.github.io/community-resume/ <http://kn9ts.github.io/community-resume/>

**Comment by jeremyramin** [comment]
That is good to hear. Thank you for using Terminal-Plus. I will now close this issue.

**Comment by kn9ts** [comment]
Ok! Cool. Thanks for the follow up.

| Eugene Mutai [Software Engineer | Andela] <http://andela.com/>
| Twitter/Github: @kn9ts <http://www.twitter.com/kn9ts>
| About me: http://kn9ts.github.io/community-resume/ <http://kn9ts.github.io/community-resume/>

**Comment by rofrol** [comment]
I got this error when starting atom in git bash on Windows:

`atom .`

Then I got error:

```
TypeError: Path must be a string. Received undefined
    at assertPath (path.js:8:11)
    at Object.win32.resolve (path.js:130:5)
```

**Comment by rofrol** [comment]
https://github.com/jeremyramin/terminal-plus/issues/255

**Comment by lxylance** [comment]
Officials have abandoned the use of the plug-in, using platformio-ide-terminal instead
