### ISSUE TITLE
Bash prompt has disappeared and no input is accepted.

### ISSUE THREAD

**Issue by ghost** [jeremyramin/terminal-plus#433]
I add/open the console w/ Terminal Plus, as per usual, and it no longer drops to the command line.  I'm faced with a terminal that simply sits there with a blinking cursor, as if it's reading Facebook and ignoring it's purpose in life.

**Comment by jlmoody** [comment]
Running the latest version of Atom, just installed terminal-plus and I am experiencing the same issue:
Atom = 1.12.6
macOS = 10.12.2
oh_my_zsh = latest commit

Hope this helps.

**Comment by ghost** [comment]
I've got following messages inside the Developer Tools console:
```
task.coffee:86
Module version mismatch. Expected 49, got 46. Error: Module version mismatch. Expected 49, got 46.

task.coffee:86
Cannot read property 'bind' of null TypeError: Cannot read property 'bind' of null
    at process.<anonymous>
```

**Comment by incyi** [comment]
Same problem here. Also on : 
macOS 10.12.2
Atom 1.13.0

**Comment by ghost** [comment]
To be even more specific, I'm on...

macOS 10.12.2
Atom 1.13.0 x64

...as well.

**Comment by marabesi** [comment]
Hello guys, same here I've got a black terminal and I can't type anything inside it : (

<img width="1065" alt="screen shot 2017-01-19 at 21 05 40" src="https://cloud.githubusercontent.com/assets/2129872/22129070/10157fa4-de8b-11e6-92f7-aa562397b67e.png">

**Comment by ThroughLee** [comment]
same here

**Comment by jsliz0422** [comment]
same here

**Comment by adhisimon** [comment]
Same here on fedora 25

**Comment by kaikun213** [comment]
Same here on Ubuntu 16.04.
Atom: 1.13.0
Same error message as @dkfiresky .

**Comment by ghost** [comment]
https://github.com/jeremyramin/terminal-plus/pull/235 Just will leave it here

**Comment by stevenventimiglia** [comment]
Now, in Windows 10, I get the following error:

> Installing “terminal-plus@0.14.5” failed.Hide output…
> Failed to install terminal-plus because Git was not found.
> The terminal-plus package has module dependencies that cannot be installed without Git.
> You need to install Git and add it to your path environment variable in order to install this package.
>
> You can install Git by downloading, installing, and launching GitHub for Windows: https://windows.github.com
> 
> Run apm -v after installing Git to see what version has been detected.

The only problem is that I do have Git installed.  Had to go with a fork of this repo, called "platformio-ide-terminal" (https://github.com/platformio/platformio-atom-ide-terminal). Unfortunately, I may be switching permanently since it's minus 150+ issues, with less pull requests lingering.
  
In Windows 10, when you have Git for Windows installed, simply adding...

`C:\Program Files\Git\bin\bash.exe`

...to the Shell Override option (which would normally be "C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe") solved the issue lickety split.

With over 235 downloads, I wish Jeremy good luck for introducing me to the best terminal package I ever used in an editor.

**Comment by seeekr** [comment]
Got same error on fresh install on macOS. The platformio fork works for me.

**Comment by Stefanbracke** [comment]
Totally unusable. No solution yet?

**Comment by stevenventimiglia** [comment]
As @dkfiresky mentioned above, [#235](https://github.com/jeremyramin/terminal-plus/pull/235).  As recommended, go with https://github.com/platformio/platformio-atom-ide-terminal.

**Comment by Stefanbracke** [comment]
Same issue with platformio-atom-ide-terminal...

Wow, nothing works. Why did I even bother moving to Atom.io?
Sorry, enough of the negative mood: i guess it is normal and i should just wait for an update...

**Comment by stevenventimiglia** [comment]
@Stefanbracke - I've tested it on Linux, Windows, OSX and MacOS Sierra.  Works fine.  You should verify that you've updated to the most recent version of Atom, as well as disabling then uninstalling Terminal-Plus then restarting Atom to make sure the changes have been applied correctly.

Otherwise, the control bar of Terminal-Plus will continue to sit above the Platformio terminal.  Happened to me, so this feedback is based on personal experience.

> Instead of waiting for most updates to happen mysteriously by a company that's sold it to you, we're all responsible for the packages to receive feedback, be tested and updated (possibly with a pull request or two.)  And they're free. Terminal-Plus has not had any serious issues handled since 2015 (w/ one in 2016).  It's taken me years to understand the benefit of Github as a community, and truly respect the fact that Atom was created by the folks from Github.  It's helping to bring the interactive social community back to the old-school standards I remember before social media/marketing took a hold of it.  My goto editor was always Notepad++.  I still use it for notes, and snippets on occassion - but Atom is the editor of choice when it comes to my projects, personal or professional, with many more benefits (such as how it helps you handle merge conflicts.)

**Comment by Stefanbracke** [comment]
Thanks @stevenventimiglia , that helped me: i am now using platform-io's terminal. 

Hopefully, the next update of atom won't break another set of packages i was using: that is always my fear.

**Comment by msabramo** [comment]
I also get a blank terminal on Mac OS X 10.11.6 and Atom 1.13.0 and this shows up the console:

![screenshot 2017-01-24 11 24 12](https://cloud.githubusercontent.com/assets/305268/22262963/a76d3172-e227-11e6-95d1-a247af8db065.png)

**Comment by stevenventimiglia** [comment]
@msabramo - Previously, on Terminal-Plus...

> Had to go with a fork of this repo, called "platformio-ide-terminal" (https://github.com/platformio/platformio-atom-ide-terminal). Unfortunately, I may be switching permanently since it's minus 150+ issues, with less pull requests lingering.

> As @dkfiresky mentioned above, #235. As recommended, go with https://github.com/platformio/platformio-atom-ide-terminal.

**Comment by msabramo** [comment]
Thanks, @stevenventimiglia! platformio-atom-ide-terminal works well for me.

**Comment by dmitry-saritasa** [comment]
I'm on Fedora 25, latest ATOM - the same thing

**Comment by hanibash** [comment]
@dmitry-saritasa @stevenventimiglia @msabramo @stevenventimiglia @Stefanbracke @seeekr @seeekr @stevenventimiglia @dkfiresky @kaikun213 @adhisimon @EvisionPRO @ThroughLee @marabesi @incyi @dkfiresky @jlmoody @htmlcore Try out https://github.com/Fred-Barclay/Termination, worked perfectly for me and actively maintained.

**Comment by stevenventimiglia** [comment]
@hanibash - I'll keep my eyes on it, but it needs more users to see if it's going to last (aka being maintained.)  Too many players are "all forks and no action".  However... I was very happy to see your push request, "Terminal themes use ANSI colors".  Although Platformio Terminal had their last commit more recently, Termination is many commits ahead of them, and Fred seems to be a bit more proactive.  We shall see.  ;)

**Comment by NickWhiu** [comment]
@hanibash thank you so much! I all but gave up with an atom terminal, you just made my day! Thanks thanks terminal-plus team, thanks platformio-ide-terminal, I did like you both but you've both failed and not recovered for many months.

**Comment by stevenventimiglia** [comment]
What issues have you been having with "platformio-ide-terminal"?  They've been updating it quite often.  Fred Barclay's been doing a real good job with Termination (https://github.com/Fred-Barclay/Termination), too.  So I'm interested in finding out what's different between the two.

**Comment by NickWhiu** [comment]
Ok embarrasingly, now that I've uninstalled platformio-ide-terminal and re-installed it, it appears to work. For the past several months I've had no luck getting it to work at all.

**Comment by 0x6B386F** [comment]
Same problem here.
X64 Linux, Debian 9 (Stretch), Atom 1.23.3.

Replaced with [terminal-tab](https://atom.io/packages/terminal-tab) plugin.

```js

Cannot find module '../build/Release/pty.node'
(anonymous) @ <embedded>:74670
<embedded>:74673 The module '/home/onedal/.atom/packages/terminal-plus/node_modules/pty.js/bin/linux/x64.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 46. This version of Node.js requires
NODE_MODULE_VERSION 53. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or`npm install`). Error: The module '/home/onedal/.atom/packages/terminal-plus/node_modules/pty.js/bin/linux/x64.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 46. This version of Node.js requires
NODE_MODULE_VERSION 53. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or`npm install`).
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:173:20)
    at Object.Module._extensions..node (module.js:598:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:173:20)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/onedal/.atom/packages/terminal-plus/node_modules/pty.js/lib/pty.js:17:9)
    at Object.<anonymous> (/home/onedal/.atom/packages/terminal-plus/node_modules/pty.js/lib/pty.js:477:3)
    at Module._compile (module.js:571:32)
    at Object.value [as .js] (/usr/share/atom/resources/app.asar/src/compile-cache.js:234:23)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/onedal/.atom/packages/terminal-plus/node_modules/pty.js/index.js:2:18)
    at Object.<anonymous> (/home/onedal/.atom/packages/terminal-plus/node_modules/pty.js/index.js:4:3)
    at Module._compile (module.js:571:32)
    at Object.value [as .js] (/usr/share/atom/resources/app.asar/src/compile-cache.js:234:23)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/onedal/.atom/packages/terminal-plus/lib/process.coffee:1:7)
    at Object.<anonymous> (/home/onedal/.atom/packages/terminal-plus/lib/process.coffee:1:1)
    at Object.<anonymous> (/home/onedal/.atom/packages/terminal-plus/lib/process.coffee:1:1)
    at Module._compile (module.js:571:32)
(anonymous) @ <embedded>:74673
<embedded>:74673 handler is not defined ReferenceError: handler is not defined
    at process.<anonymous> (/usr/share/atom/resources/app.asar/src/task-bootstrap.js:51:20)
    at emitTwo (events.js:106:13)
    at process.emit (events.js:191:7)
    at process.nextTick (internal/child_process.js:752:12)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```
