### ISSUE TITLE
Uncaught Error: The workspace can only contain one instance of item [object Object]

### ISSUE THREAD

**Issue by tim-field** [jeremyramin/terminal-plus#438]
Minimising the terminal using the icon in the footer will often cause this error.  That terminal will then no longer open

**Atom Version**: 1.13.1
**Electron Version**: 1.3.13
**System**: Ubuntu 16.10
**Thrown From**: [terminal-plus](https://github.com/jeremyramin/terminal-plus) package, v0.14.5

### Stack Trace

Uncaught Error: The workspace can only contain one instance of item [object Object]

```
At /home/andrei/atom-1.11.1/out/app/src/item-registry.coffee:11

Error: The workspace can only contain one instance of item [object Object]
    at ItemRegistry.module.exports.ItemRegistry.addItem (/opt/atom/resources/app.asar/src/item-registry.js:11:15)
    at PaneContainer.module.exports.PaneContainer.addedPaneItem (/opt/atom/resources/app.asar/src/pane-container.js:389:25)
    at /opt/atom/resources/app.asar/src/pane-container.js:374:28
    at Function.module.exports.Emitter.simpleDispatch (/opt/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/opt/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at Pane.module.exports.Pane.addItem (/opt/atom/resources/app.asar/src/pane.js:491:20)
    at Pane.module.exports.Pane.activateItem (/opt/atom/resources/app.asar/src/pane.js:434:14)
    at PanelView.module.exports.TerminalView.hide (/home/tim/.atom/packages/terminal-plus/lib/terminal-view.coffee:70:14)
    at /home/tim/.atom/packages/terminal-plus/lib/panel-view.coffee:156:7
    at space-pen-div.<anonymous> (/home/tim/.atom/packages/terminal-plus/lib/panel-view.coffee:186:7)
    at space-pen-div.fn (/home/tim/.atom/packages/terminal-plus/node_modules/jquery/dist/jquery.js:4855:19)
    at space-pen-div.dispatch (/home/tim/.atom/packages/terminal-plus/node_modules/jquery/dist/jquery.js:4435:9)
    at space-pen-div.elemData.handle (/home/tim/.atom/packages/terminal-plus/node_modules/jquery/dist/jquery.js:4121:28)
```

### Commands

```
  3x -2:52.5.0 blur (input.hidden-input)
  3x -2:51.8.0 vim-mode:move-down (input.hidden-input)
 13x -2:47.3.0 blur (input.hidden-input)
     -2:17.9.0 vim-mode:replace (input.hidden-input)
  6x -2:17.9.0 blur (input.hidden-input)
     -2:17.6.0 vim-mode:reset-normal-mode (input.hidden-input)
     -2:17.3.0 ex-mode:open (input.hidden-input)
  3x -2:17.3.0 blur (input.hidden-input)
     -2:17 core:confirm (input.hidden-input)
  3x -2:17 blur (input.hidden-input)
     -2:16.4.0 vim-mode:move-down (input.hidden-input)
     -2:16 vim-mode:reset-normal-mode (input.hidden-input)
     -2:15.6.0 ex-mode:open (input.hidden-input)
  3x -2:15.5.0 blur (input.hidden-input)
     -2:15.3.0 core:confirm (input.hidden-input)
undefined -2:15.3.0 blur (input.hidden-input)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "wrap-guide",
      "whitespace",
      "php-debug"
    ],
    "projectHome": "/srv/www",
    "telemetryConsent": "limited",
    "themes": [
      "one-dark-ui",
      "solarized-dark-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.29.17 (inactive)
editorconfig, v2.2.0 (active)
ex-mode, v0.13.1 (active)
hyperclick, v0.0.40 (active)
language-babel, v2.51.0 (active)
language-cfml, v0.16.0 (active)
language-pgsql, v0.2.3 (active)
linter, v1.11.21 (active)
linter-eslint, v8.1.0 (active)
linter-php, v1.3.1 (active)
php-debug, v0.2.4 (inactive)
relative-numbers, v0.7.1 (active)
terminal-plus, v0.14.5 (active)
vim-mode, v0.66.0 (active)
wordpress-api, v1.2.2 (active)
atom-dark-syntax, v0.28.0 (inactive)
atom-dark-ui, v0.53.0 (inactive)
atom-light-syntax, v0.29.0 (inactive)
atom-light-ui, v0.46.0 (inactive)
base16-tomorrow-dark-theme, v1.4.0 (inactive)
base16-tomorrow-light-theme, v1.4.0 (inactive)
one-dark-ui, v1.8.2 (active)
one-light-ui, v1.8.2 (inactive)
one-dark-syntax, v1.6.0 (inactive)
one-light-syntax, v1.6.0 (inactive)
solarized-dark-syntax, v1.1.1 (active)
solarized-light-syntax, v1.1.1 (inactive)
about, v1.7.2 (active)
archive-view, v0.62.0 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.14.1 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.33.1 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.29.0 (inactive)
autosave, v0.23.2 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.43.2 (active)
bracket-matcher, v0.85.1 (active)
command-palette, v0.39.1 (inactive)
deprecation-cop, v0.55.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
find-and-replace, v0.204.5 (inactive)
fuzzy-finder, v1.4.0 (active)
git-diff, v1.2.0 (active)
go-to-line, v0.31.2 (inactive)
grammar-selector, v0.48.2 (active)
image-view, v0.60.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.1 (active)
link, v0.31.2 (inactive)
markdown-preview, v0.159.3 (active)
notifications, v0.65.1 (active)
open-on-github, v1.2.1 (inactive)
package-generator, v1.0.2 (inactive)
settings-view, v0.244.0 (active)
snippets, v1.0.4 (active)
spell-check, v0.68.5 (active)
status-bar, v1.6.0 (active)
styleguide, v0.48.0 (active)
symbols-view, v0.113.1 (inactive)
tabs, v0.103.1 (active)
timecop, v0.33.2 (active)
tree-view, v0.211.1 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.35.1 (active)
whitespace, v0.35.0 (inactive)
wrap-guide, v0.39.0 (inactive)
language-c, v0.54.0 (active)
language-clojure, v0.22.1 (active)
language-coffee-script, v0.48.1 (active)
language-csharp, v0.13.0 (active)
language-css, v0.40.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.43.0 (active)
language-html, v0.47.1 (active)
language-hyperlink, v0.16.1 (active)
language-java, v0.24.0 (active)
language-javascript, v0.122.0 (active)
language-json, v0.18.3 (active)
language-less, v0.29.6 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.37.0 (active)
language-php, v0.37.3 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.1 (active)
language-ruby, v0.70.2 (active)
language-ruby-on-rails, v0.25.1 (active)
language-sass, v0.57.0 (active)
language-shellscript, v0.23.0 (active)
language-source, v0.9.0 (active)
language-sql, v0.25.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.29.1 (active)
language-toml, v0.18.1 (active)
language-xml, v0.34.12 (active)
language-yaml, v0.27.1 (active)

# Dev
No dev packages
```

**Comment by talshorer** [comment]
[Enter steps to reproduce:]

Got this while minimizing the terminal using the keybinding.

**Atom**: 1.18.0 x64
**Electron**: 1.3.15
**OS**: Ubuntu 16.04.2
**Thrown From**: [terminal-plus](https://github.com/jeremyramin/terminal-plus) package 0.14.5


### Stack Trace

Uncaught Error: The workspace can only contain one instance of item [object Object]

```
At /usr/share/atom/resources/app/src/item-registry.js:11

Error: The workspace can only contain one instance of item [object Object]
    at ItemRegistry.module.exports.ItemRegistry.addItem (/usr/share/atom/resources/app/src/item-registry.js:11:21)
    at PaneContainer.didAddPaneItem (/usr/share/atom/resources/app/src/pane-container.js:265:29)
    at Pane.module.exports.Pane.addItem (/usr/share/atom/resources/app/src/pane.js:532:22)
    at Pane.module.exports.Pane.activateItem (/usr/share/atom/resources/app/src/pane.js:468:20)
    at PanelView.module.exports.TerminalView.hide (/packages/terminal-plus/lib/terminal-view.coffee:70:14)
    at /packages/terminal-plus/lib/panel-view.coffee:156:7
    at /packages/terminal-plus/lib/panel-view.coffee:186:7)
    at /packages/terminal-plus/node_modules/jquery/dist/jquery.js:4855:19)
    at /packages/terminal-plus/node_modules/jquery/dist/jquery.js:4435:9)
    at /packages/terminal-plus/node_modules/jquery/dist/jquery.js:4121:28)
```

### Commands

```
  2x -7:46.2.0 find-and-replace:show-previous (input.hidden-input)
  2x -7:45.3.0 core:confirm (input.hidden-input)
     -7:44.9.0 editor:consolidate-selections (input.hidden-input)
     -7:44.9.0 core:cancel (input.hidden-input)
     -7:39.7.0 terminal-plus:toggle (input.hidden-input)
     -0:32.2.0 find-and-replace:show (input.hidden-input)
  3x -0:31.7.0 core:confirm (input.hidden-input)
     -0:30.3.0 find-and-replace:show-previous (input.hidden-input)
     -0:30.1.0 core:confirm (input.hidden-input)
     -0:27.7.0 find-and-replace:show-previous (input.hidden-input)
     -0:26.9.0 core:confirm (input.hidden-input)
     -0:26.6.0 find-and-replace:show-previous (input.hidden-input)
     -0:18.3.0 core:copy (input.hidden-input)
     -0:17.8.0 find-and-replace:show (input.hidden-input)
     -0:17.3.0 editor:move-to-end-of-screen-line (input.hidden-input)
  2x -0:16.1.0 terminal-plus:toggle (input.hidden-input)
```

### Non-Core Packages

```
atom-cscope 1.0.1 
ctrl-dir-scroll 0.2.5 
git-blame 1.3.1 
goto-definition 1.3.4 
highlight-selected 0.13.1 
jumpy 3.1.3 
language-diff 0.7.0 
language-log 1.9.0 
multi-cursor 2.1.5 
multi-cursor-plus 1.2.0 
open-files 0.8.2 
revert-buffer 0.5.0 
split-diff 1.5.1 
tab-smart-sort 0.3.0 
terminal-plus 0.14.5 
tree-view-panes 0.3.7 
```
