### ISSUE TITLE
Module version mismatch "pty.node"

### ISSUE THREAD

**Issue by creekpld** [jeremyramin/terminal-plus#439]
`Cannot find module '../build/Release/pty.node'
Module version mismatch. Expected 49, got 46. Error: Module version mismatch. Expected 49, got 46.
    at Error (native)
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:168:20)
    at Object.Module._extensions..node (module.js:583:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:168:20)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/pld/.atom/packages/terminal-plus/node_modules/pty.js/lib/pty.js:17:9)
    at Module._compile (module.js:556:32)
    at Object.value [as .js] (/opt/atom/resources/app.asar/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/pld/.atom/packages/terminal-plus/node_modules/pty.js/index.js:2:18)
    at Module._compile (module.js:556:32)
    at Object.value [as .js] (/opt/atom/resources/app.asar/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/pld/.atom/packages/terminal-plus/lib/process.coffee:1:7)
    at Object.<anonymous> (/home/pld/.atom/packages/terminal-plus/lib/process.coffee:1:1)
    at Module._compile (module.js:556:32)
    at Object.value [as .coffee] (/opt/atom/resources/app.asar/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
Cannot read property 'bind' of null TypeError: Cannot read property 'bind' of null
    at process.<anonymous> (/opt/atom/resources/app.asar/src/task-bootstrap.js:82:23)
    at emitTwo (events.js:106:13)
    at process.emit (events.js:191:7)
    at process.nextTick (internal/child_process.js:744:12)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
`

**Comment by jamesmcintyre** [comment]
+1
same error
