### ISSUE TITLE
Uncaught TypeError: Cannot read property 'terminate' of null

### ISSUE THREAD

**Issue by atbe** [jeremyramin/terminal-plus#450]
1. Start new terminal with zsh shell.
2. Enter `exit` to kill the shell.
3. Press the red `x` button to kill the terminal tab.

**Atom**: 1.14.3 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.12.3
**Thrown From**: [terminal-plus](https://github.com/jeremyramin/terminal-plus) package 0.14.5

### Stack Trace

Uncaught TypeError: Cannot read property 'terminate' of null

```
At /Users/abe/.atom/packages/terminal-plus/lib/shell.coffee:47

TypeError: Cannot read property 'terminate' of null
    at Shell.module.exports.Shell.terminate (/packages/terminal-plus/lib/shell.coffee:47:10)
    at Shell.module.exports.Shell.destroy (/packages/terminal-plus/lib/shell.coffee:25:6)
    at Terminal.module.exports.Terminal.destroy (/packages/terminal-plus/lib/terminal.coffee:62:12)
    at PanelView.module.exports.TerminalView.destroy (/packages/terminal-plus/lib/terminal-view.coffee:32:15)
    at PanelView.module.exports.PanelView.destroy (/packages/terminal-plus/lib/panel-view.coffee:45:5)
    at /packages/terminal-plus/lib/panel-view.coffee:1:1)
    at HTMLButtonElement.dispatch (/packages/terminal-plus/node_modules/jquery/dist/jquery.js:4435:9)
    at HTMLButtonElement.elemData.handle (/packages/terminal-plus/node_modules/jquery/dist/jquery.js:4121:28)
```

### Commands

```
  2x -0:25.2.0 core:backspace (input.hidden-input)
     -0:22.3.0 core:save (input.hidden-input)
     -0:21.8.0 editor:consolidate-selections (input.hidden-input)
     -0:21.8.0 core:cancel (input.hidden-input)
     -0:08.2.0 core:close (textarea.)
```

### Non-Core Packages

```
advanced-open-file 0.16.5 
autocomplete-clang 0.10.0 
autocomplete-python 1.8.57 
base16-syntax 1.8.0 
kite 0.10.7 
linter 1.11.23 
linter-gcc 0.7.1 
markdown-writer 2.6.4 
pretty-json 1.6.1 
Remote-FTP 0.10.7 
terminal-plus 0.14.5 
vim-mode-plus 0.82.3 
```

**Comment by Fred-Barclay** [comment]
Hi @atbe 
terminal-plus doesn't seem to be maintained anymore. I've got a working fork if you'd like to try it:
https://atom.io/packages/termination
`apm install termination`

There's also another splendid terminal package available, platformio-ide-terminal:
https://atom.io/packages/platformio-ide-terminal

**Comment by atbe** [comment]
@Fred-Barclay I didn't notice that, thanks for the alternatives. I'll check them out.
