### ISSUE TITLE
Uncaught Error: Cannot find module 'atom-space-pen-views'

### ISSUE THREAD

**Issue by ghost** [jeremyramin/terminal-plus#463]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.15.0 x64
**Electron**: 1.3.13
**OS**: Microsoft Windows 10 ???
**Thrown From**: [terminal-plus](https://github.com/jeremyramin/terminal-plus) package 0.14.5

### Stack Trace

Uncaught Error: Cannot find module 'atom-space-pen-views'

```
At module.js:457

Error: Cannot find module 'atom-space-pen-views'
    at Module._resolveFilename (module.js:455:15)
    at Module._resolveFilename (~/AppData/Local/atom/app-1.15.0/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._resolveFilename (/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at /packages/terminal-plus/lib/panel-view.coffee:2:7)
    at /packages/terminal-plus/lib/panel-view.coffee:1:1)
    at Module._compile (/app.asar/src/native-compile-cache.js:109:30)
    at /app.asar/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at Core.newTerminalView (/packages/terminal-plus/lib/core.coffee:156:18)
    at Core.newTerminalView (/packages/terminal-plus/lib/core.coffee:1:1)
    at Core.toggle (/packages/terminal-plus/lib/core.coffee:177:26)
    at /packages/terminal-plus/lib/core.coffee:35:35)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/app.asar/src/command-registry.js:259:29)
    at CommandRegistry.handleCommandEvent (/app.asar/src/command-registry.js:3:59)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/app.asar/src/command-registry.js:160:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchApplicationMenuCommand (/app.asar/src/atom-environment.js:1162:28)
    at EventEmitter.outerCallback (/app.asar/src/application-delegate.js:312:25)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
```

### Commands

```
     -0:05.9.0 terminal-plus:toggle (input.hidden-input)
```

### Non-Core Packages

```
color-picker 2.2.5 
emmet 2.4.3 
file-type-icons 1.3.3 
file-types 0.5.5 
language-babel 2.57.1 
minimap 4.26.8 
simplified-chinese-menu 3.5.0 
terminal-plus 0.14.5 
```

**Comment by i2000s** [comment]
Same issue here on Windows 7. Any progress?
