### ISSUE TITLE
Terminal doesn't launch on Atom 10.16.0 x64 on MacOS 10.12

### ISSUE THREAD

**Issue by matteozambon89** [jeremyramin/terminal-plus#471]
Here's the log after I click on the plus `+` to launch the terminal:

```
Cannot find module '../build/Release/pty.node'
task.coffee:86 Module version mismatch. Expected 49, got 46. Error: Module version mismatch. Expected 49, got 46.
    at Error (native)
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:168:20)
    at Object.Module._extensions..node (module.js:583:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:168:20)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/Matteo/.atom/packages/terminal-plus/node_modules/pty.js/lib/pty.js:17:9)
    at Module._compile (module.js:556:32)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/Matteo/.atom/packages/terminal-plus/node_modules/pty.js/index.js:2:18)
    at Module._compile (module.js:556:32)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/Matteo/.atom/packages/terminal-plus/lib/process.coffee:1:7)
    at Object.<anonymous> (/Users/Matteo/.atom/packages/terminal-plus/lib/process.coffee:1:1)
    at Module._compile (module.js:556:32)
    at Object.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)(anonymous function) @ task.coffee:86(anonymous function) @ task.coffee:146module.exports.Emitter.simpleDispatch @ emitter.js:25module.exports.Emitter.emit @ emitter.js:129(anonymous function) @ task.coffee:98emitTwo @ events.js:106emit @ events.js:191process.nextTick @ internal/child_process.js:744_combinedTickCallback @ internal/process/next_tick.js:67_tickCallback @ internal/process/next_tick.js:98
task.coffee:86 Cannot read property 'bind' of null TypeError: Cannot read property 'bind' of null
    at process.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/task-bootstrap.js:82:23)
    at emitTwo (events.js:106:13)
    at process.emit (events.js:191:7)
    at process.nextTick (internal/child_process.js:744:12)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)(anonymous function) @ task.coffee:86(anonymous function) @ task.coffee:146module.exports.Emitter.simpleDispatch @ emitter.js:25module.exports.Emitter.emit @ emitter.js:129(anonymous function) @ task.coffee:98emitTwo @ events.js:106emit @ events.js:191process.nextTick @ internal/child_process.js:744_combinedTickCallback @ internal/process/next_tick.js:67_tickCallback @ internal/process/next_tick.js:98
```

**Comment by neeraj87** [comment]
I am having similar issue. I do not get any error message but when I open the terminal window and type anything, nothing gets written on the terminal.

**Comment by meowow** [comment]
I have the same problem as neeraj87.

**Comment by levblanc** [comment]
Similar issue here.

Atom: 10.16.0 x64
MacOS: 10.11.6

After installed, `shift-cmd-T` and other keystrokes didn't work, commands not available after pressing `cmd + shift + p`.  :(

**Comment by Fred-Barclay** [comment]
Hi mates,
terminal-plus isn't being developed anymore. There are two working forks, though: `termination` and `platformio-ide-atom-terminal`.

**Comment by kdekooter** [comment]
@Fred-Barclay Which one to pick?

**Comment by Fred-Barclay** [comment]
@kdekooter I maintain termination so I'm kind of partial to it. 😄 It's designed to look as close to terminal-plus as possible, so if you want that, then I'd go with termination.

Platformio-ide-atom-terminal is also good (it's actually the upstream for termination) but it looks a little different than terminal-plus and termination. For example, you don't get a standalone status bar.

**Comment by beeyen** [comment]
@Fred-Barclay, thanks!

**Comment by Fred-Barclay** [comment]
@beeyen you're welcome!
