### ISSUE TITLE
Cannot execute terminal

### ISSUE THREAD

**Issue by Triple-Z** [jeremyramin/terminal-plus#481]
Atom Version: 1.17.0 ia32 on Windows 7;
Error in console:
```
events.js:106 The specified procedure could not be found.
\\?\C:\Users\admin\.atom\packages\terminal-plus\node_modules\pty.js\bin\win32\ia32.node Error: The specified procedure could not be found.
\\?\C:\Users\admin\.atom\packages\terminal-plus\node_modules\pty.js\bin\win32\ia32.node
    at Error (native)
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:168:20)
    at Object.Module._extensions..node (module.js:583:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:168:20)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\admin\.atom\packages\terminal-plus\node_modules\pty.js\lib\pty.js:17:9)
    at Module._compile (module.js:556:32)
    at Object.value [as .js] (C:\Users\admin\AppData\Local\atom\app-1.17.0\resources\app\src\compile-cache.js:225:23)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\admin\.atom\packages\terminal-plus\node_modules\pty.js\lib\pty_win.js:10:36)
    at Module._compile (module.js:556:32)
    at Object.value [as .js] (C:\Users\admin\AppData\Local\atom\app-1.17.0\resources\app\src\compile-cache.js:225:23)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\admin\.atom\packages\terminal-plus\node_modules\pty.js\index.js:2:18)
    at Module._compile (module.js:556:32)
    at Object.value [as .js] (C:\Users\admin\AppData\Local\atom\app-1.17.0\resources\app\src\compile-cache.js:225:23)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)(anonymous function) @ <embedded>:69958(anonymous function) @ <embedded>:70032module.exports.Emitter.simpleDispatch @ <embedded>:62314module.exports.Emitter.emit @ <embedded>:62430(anonymous function) @ <embedded>:69984emitTwo @ events.js:106emit @ events.js:191process.nextTick @ internal/child_process.js:744_combinedTickCallback @ internal/process/next_tick.js:67_tickCallback @ internal/process/next_tick.js:98
events.js:106 Cannot read property 'bind' of null TypeError: Cannot read property 'bind' of null
    at process.<anonymous> (C:\Users\admin\AppData\Local\atom\app-1.17.0\resources\app\src\task-bootstrap.js:82:23)
    at emitTwo (events.js:106:13)
    at process.emit (events.js:191:7)
    at process.nextTick (internal/child_process.js:744:12)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)(anonymous function) @ <embedded>:69958(anonymous function) @ <embedded>:70032module.exports.Emitter.simpleDispatch @ <embedded>:62314module.exports.Emitter.emit @ <embedded>:62430(anonymous function) @ <embedded>:69984emitTwo @ events.js:106emit @ events.js:191process.nextTick @ internal/child_process.js:744_combinedTickCallback @ internal/process/next_tick.js:67_tickCallback @ internal/process/next_tick.js:98
```

```
events.js:106 Cannot read property 'bind' of null TypeError: Cannot read property 'bind' of null
    at process.<anonymous> (C:\Users\admin\AppData\Local\atom\app-1.17.0\resources\app\src\task-bootstrap.js:82:23)
    at emitTwo (events.js:106:13)
    at process.emit (events.js:191:7)
    at process.nextTick (internal/child_process.js:744:12)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)(anonymous function) @ <embedded>:69958(anonymous function) @ <embedded>:70032module.exports.Emitter.simpleDispatch @ <embedded>:62314module.exports.Emitter.emit @ <embedded>:62430(anonymous function) @ <embedded>:69984emitTwo @ events.js:106emit @ events.js:191process.nextTick @ internal/child_process.js:744_combinedTickCallback @ internal/process/next_tick.js:67_tickCallback @ internal/process/next_tick.js:98
```

**Comment by woosungchu** [comment]
same happened to me
