### ISSUE TITLE
Terminal not starting, stays on empty black screen

### ISSUE THREAD

**Issue by cpcho** [jeremyramin/terminal-plus#484]
Windows 10 Enterprise x64. Atom version 1.17.2.

Terminal-plus is not starting on Atom editor. White cursor is blinking. The terminal remains as an empty black screen. 

![capture](https://cloud.githubusercontent.com/assets/19799405/26509701/ee4462c2-4227-11e7-92cf-2d81dd90427b.PNG)

**Comment by Varkal** [comment]
Same problem here on macOS 10.12, Atom 1.17.2, and zsh as shell

EDIT: 

This messages appears in the console when i try to open a terminal

```

events.js:106 Module version mismatch. Expected 49, got 46. Error: Module version mismatch. Expected 49, got 46.
    at Error (native)
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:168:20)
    at Object.Module._extensions..node (module.js:583:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:168:20)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/Varkal/.atom/packages/terminal-plus/node_modules/pty.js/lib/pty.js:17:9)
    at Module._compile (module.js:556:32)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/src/compile-cache.js:225:23)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/Varkal/.atom/packages/terminal-plus/node_modules/pty.js/index.js:2:18)
    at Module._compile (module.js:556:32)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/src/compile-cache.js:225:23)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/Varkal/.atom/packages/terminal-plus/lib/process.coffee:1:7)
    at Object.<anonymous> (/Users/Varkal/.atom/packages/terminal-plus/lib/process.coffee:1:1)
    at Module._compile (module.js:556:32)
    at Object.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app/src/compile-cache.js:225:23)
    at Module.load (module.js:473:32)(anonymous function) @ <embedded>:70040(anonymous function) @ <embedded>:70114module.exports.Emitter.simpleDispatch @ <embedded>:62396module.exports.Emitter.emit @ <embedded>:62512(anonymous function) @ <embedded>:70066emitTwo @ events.js:106emit @ events.js:191process.nextTick @ internal/child_process.js:744_combinedTickCallback @ internal/process/next_tick.js:67_tickCallback @ internal/process/next_tick.js:98
```

```
events.js:106 Cannot read property 'bind' of null TypeError: Cannot read property 'bind' of null
    at process.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/task-bootstrap.js:82:23)
    at emitTwo (events.js:106:13)
    at process.emit (events.js:191:7)
    at process.nextTick (internal/child_process.js:744:12)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

**Comment by yukoss** [comment]
Same problem, Ubuntu 16.04 x64, Atom 1.17.2. When I start the terminal just a black screen.

**Comment by Varkal** [comment]
This repo seems not very active (last commit in October), so i move to this fork and works perfectly : [platformio/platformio-atom-ide-terminal](https://github.com/platformio/platformio-atom-ide-terminal)
