### ISSUE TITLE
Uncaught Error: Cannot find module 'term.js'

### ISSUE THREAD

**Issue by lxylance** [jeremyramin/terminal-plus#489]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.17.2 x64
**Electron**: 1.3.15
**OS**: Unknown Windows version
**Thrown From**: [terminal-plus](https://github.com/jeremyramin/terminal-plus) package 0.14.5

### Stack Trace

Uncaught Error: Cannot find module 'term.js'

```
At module.js:457

Error: Cannot find module 'term.js'
    at Module._resolveFilename (module.js:455:15)
    at Module._resolveFilename (~/AppData/Local/atom/app-1.17.2/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (~/AppData/Local/atom/app-1.17.2/resources/app/src/module-cache.js:354:1)
    at Module.require (~/AppData/Local/atom/app-1.17.2/resources/app/static/index.js:40:43)
    at require (~/AppData/Local/atom/app-1.17.2/resources/app/src/native-compile-cache.js:66:1)
    at Terminal.module.exports.Terminal.initialize (/packages/terminal-plus-master/lib/terminal.coffee:34:24)
    at /packages/terminal-plus-master/node_modules/space-pen/lib/space-pen.js:184:25)
    at /packages/terminal-plus-master/lib/terminal.coffee:13:7)
    at Object.content (/packages/terminal-plus-master/lib/terminal-view.coffee:20:36)
    at Builder.tag (/packages/terminal-plus-master/node_modules/space-pen/lib/space-pen.js:281:19)
    at /packages/terminal-plus-master/node_modules/space-pen/lib/space-pen.js:83:49)
    at Object.content (/packages/terminal-plus-master/lib/terminal-view.coffee:17:8)
    at Builder.tag (/packages/terminal-plus-master/node_modules/space-pen/lib/space-pen.js:281:19)
    at /packages/terminal-plus-master/node_modules/space-pen/lib/space-pen.js:83:49)
    at Function.module.exports.TerminalView.content (/packages/terminal-plus-master/lib/terminal-view.coffee:16:6)
    at /packages/terminal-plus-master/node_modules/space-pen/lib/space-pen.js:156:31)
    at Function.View.buildHtml (/packages/terminal-plus-master/node_modules/space-pen/lib/space-pen.js:123:10)
    at /packages/terminal-plus-master/node_modules/space-pen/lib/space-pen.js:155:33)
    at /packages/terminal-plus-master/lib/terminal-view.coffee:9:7)
    at /packages/terminal-plus-master/lib/panel-view.coffee:17:7)
    at Core.createTerminalView (/packages/terminal-plus-master/lib/core.coffee:287:16)
    at Core.newTerminalView (/packages/terminal-plus-master/lib/core.coffee:163:21)
    at Core.newTerminalView (/packages/terminal-plus-master/lib/core.coffee:1:1)
    at StatusBar.newTerminalView (/packages/terminal-plus-master/lib/status-bar.coffee:99:5)
    at /packages/terminal-plus-master/node_modules/space-pen/lib/space-pen.js:220:36)
    at HTMLElement.dispatch (/packages/terminal-plus-master/node_modules/jquery/dist/jquery.js:4435:9)
    at HTMLElement.elemData.handle (/packages/terminal-plus-master/node_modules/jquery/dist/jquery.js:4121:28)
```

### Commands

```
     -3:11.3.0 snippets:next-tab-stop (input.hidden-input)
     -3:11.3.0 snippets:expand (input.hidden-input)
     -3:11.3.0 editor:indent (input.hidden-input)
     -3:09.4.0 snippets:next-tab-stop (input.hidden-input)
     -3:09.4.0 snippets:expand (input.hidden-input)
     -3:09.4.0 editor:indent (input.hidden-input)
  3x -3:07.7.0 core:backspace (input.hidden-input)
  5x -2:54.6.0 core:save (input.hidden-input)
  3x -2:12.9.0 core:copy (input.hidden-input)
     -2:02.5.0 editor:newline (input.hidden-input)
     -2:01.7.0 core:paste (input.hidden-input)
     -2:00.6.0 editor:newline (input.hidden-input)
  3x -1:50.4.0 core:save (input.hidden-input)
  4x -1:05.3.0 core:copy (input.hidden-input)
     -1:02.8.0 core:paste (input.hidden-input)
 18x -1:02.4.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
terminal-plus 0.14.5 
```

**Comment by suli-g** [comment]
Not sure if this is a good thing to do, however,
When Atom reports missing packages, normally `npm install {package}` works...

For this issue, I used `npm install type.js` and it was resolved.
