### ISSUE TITLE
not working for me i got blank screen 

### ISSUE THREAD

**Issue by 2rohityadav** [jeremyramin/terminal-plus#509]
Windows 10,
updated Atom

<img width="824" alt="cli" src="https://user-images.githubusercontent.com/21152844/29548053-8f3d9f6c-871b-11e7-849b-c8d1d314bd3c.png">

**Comment by FelipeVS** [comment]
Me too.

Updated Atom, Ubuntu 14.04

**Comment by 01BTC10** [comment]
Same problem. I tried to run npm rebuild or apm rebuild from the package folder.

Fresh Atom 1.19.2 install on Debian sid.

> events.js:106 Cannot find module '../build/Release/pty.node'
(anonymous) @ <embedded>:71067
(anonymous) @ <embedded>:71144
module.exports.Emitter.simpleDispatch @ <embedded>:63374
module.exports.Emitter.emit @ <embedded>:63490
(anonymous) @ <embedded>:71096
emitTwo @ events.js:106
emit @ events.js:191
process.nextTick @ internal/child_process.js:752
_combinedTickCallback @ internal/process/next_tick.js:67
_tickDomainCallback @ internal/process/next_tick.js:122
events.js:106 The module '/home/r2d2/.atom/packages/terminal-plus/node_modules/pty.js/bin/linux/x64.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 46. This version of Node.js requires
NODE_MODULE_VERSION 53. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or`npm install`). Error: The module '/home/r2d2/.atom/packages/terminal-plus/node_modules/pty.js/bin/linux/x64.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 46. This version of Node.js requires
NODE_MODULE_VERSION 53. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or`npm install`).
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:173:20)
    at Object.Module._extensions..node (module.js:598:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:173:20)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/r2d2/.atom/packages/terminal-plus/node_modules/pty.js/lib/pty.js:17:9)
    at Object.<anonymous> (/home/r2d2/.atom/packages/terminal-plus/node_modules/pty.js/lib/pty.js:477:3)
    at Module._compile (module.js:571:32)
    at Object.value [as .js] (/usr/share/atom/resources/app/src/compile-cache.js:234:23)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/r2d2/.atom/packages/terminal-plus/node_modules/pty.js/index.js:2:18)
    at Object.<anonymous> (/home/r2d2/.atom/packages/terminal-plus/node_modules/pty.js/index.js:4:3)
    at Module._compile (module.js:571:32)
    at Object.value [as .js] (/usr/share/atom/resources/app/src/compile-cache.js:234:23)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/r2d2/.atom/packages/terminal-plus/lib/process.coffee:1:7)
    at Object.<anonymous> (/home/r2d2/.atom/packages/terminal-plus/lib/process.coffee:1:1)
    at Object.<anonymous> (/home/r2d2/.atom/packages/terminal-plus/lib/process.coffee:1:1)
    at Module._compile (module.js:571:32)
(anonymous) @ <embedded>:71070
(anonymous) @ <embedded>:71144
module.exports.Emitter.simpleDispatch @ <embedded>:63374
module.exports.Emitter.emit @ <embedded>:63490
(anonymous) @ <embedded>:71096
emitTwo @ events.js:106
emit @ events.js:191
process.nextTick @ internal/child_process.js:752
_combinedTickCallback @ internal/process/next_tick.js:67
_tickDomainCallback @ internal/process/next_tick.js:122
events.js:106 handler is not defined ReferenceError: handler is not defined
    at process.<anonymous> (/usr/share/atom/resources/app/src/task-bootstrap.js:51:20)
    at emitTwo (events.js:106:13)
    at process.emit (events.js:191:7)
    at process.nextTick (internal/child_process.js:752:12)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
(anonymous) @ <embedded>:71070
(anonymous) @ <embedded>:71144
module.exports.Emitter.simpleDispatch @ <embedded>:63374
module.exports.Emitter.emit @ <embedded>:63490
(anonymous) @ <embedded>:71096
emitTwo @ events.js:106
emit @ events.js:191
process.nextTick @ internal/child_process.js:752
_combinedTickCallback @ internal/process/next_tick.js:67
_tickDomainCallback @ internal/process/next_tick.js:122

**Comment by ryanvade** [comment]
same for me on Fedora
```
Atom    : 1.19.0
Electron: 1.6.9
Chrome  : 56.0.2924.87
Node    : 7.4.0
```
```
npm rebuild

> pty.js@0.3.0 install /home/ryan/.atom/packages/terminal-plus/node_modules/pty.js
> (node-gyp rebuild 2> builderror.log) || (exit 0)

make: Entering directory '/home/ryan/.atom/packages/terminal-plus/node_modules/pty.js/build'
  CXX(target) Release/obj.target/pty/src/unix/pty.o
make: Leaving directory '/home/ryan/.atom/packages/terminal-plus/node_modules/pty.js/build'

> pty.js@0.3.0 postinstall /home/ryan/.atom/packages/terminal-plus/node_modules/pty.js
> node scripts/post-install.js

atom-space-pen-views@2.2.0 /home/ryan/.atom/packages/terminal-plus/node_modules/atom-space-pen-views
fuzzaldrin@2.1.0 /home/ryan/.atom/packages/terminal-plus/node_modules/fuzzaldrin
space-pen@5.1.2 /home/ryan/.atom/packages/terminal-plus/node_modules/space-pen
grim@1.5.0 /home/ryan/.atom/packages/terminal-plus/node_modules/grim
emissary@1.3.3 /home/ryan/.atom/packages/terminal-plus/node_modules/emissary
es6-weak-map@0.1.4 /home/ryan/.atom/packages/terminal-plus/node_modules/es6-weak-map
d@0.1.1 /home/ryan/.atom/packages/terminal-plus/node_modules/d
es5-ext@0.10.27 /home/ryan/.atom/packages/terminal-plus/node_modules/es5-ext
es6-iterator@2.0.1 /home/ryan/.atom/packages/terminal-plus/node_modules/es5-ext/node_modules/es6-iterator
d@1.0.0 /home/ryan/.atom/packages/terminal-plus/node_modules/es5-ext/node_modules/d
es6-symbol@3.1.1 /home/ryan/.atom/packages/terminal-plus/node_modules/es5-ext/node_modules/es6-symbol
es6-iterator@0.1.3 /home/ryan/.atom/packages/terminal-plus/node_modules/es6-iterator
es6-symbol@2.0.1 /home/ryan/.atom/packages/terminal-plus/node_modules/es6-symbol
mixto@1.0.0 /home/ryan/.atom/packages/terminal-plus/node_modules/mixto
property-accessors@1.1.3 /home/ryan/.atom/packages/terminal-plus/node_modules/property-accessors
underscore-plus@1.6.6 /home/ryan/.atom/packages/terminal-plus/node_modules/underscore-plus
underscore@1.6.0 /home/ryan/.atom/packages/terminal-plus/node_modules/underscore-plus/node_modules/underscore
jquery@2.1.4 /home/ryan/.atom/packages/terminal-plus/node_modules/jquery
pty.js@0.3.0 /home/ryan/.atom/packages/terminal-plus/node_modules/pty.js
extend@1.2.1 /home/ryan/.atom/packages/terminal-plus/node_modules/extend
nan@2.0.5 /home/ryan/.atom/packages/terminal-plus/node_modules/nan
term.js@0.0.7 /home/ryan/.atom/packages/terminal-plus/node_modules/term.js
underscore@1.8.3 /home/ryan/.atom/packages/terminal-plus/node_modules/underscore

```
![screenshot from 2017-08-24 20-11-38](https://user-images.githubusercontent.com/1910293/29695416-74d91a22-8908-11e7-892a-08dfc9ff9b3a.png)

**Comment by 2rohityadav** [comment]
@jeremyramin  can you please look into this thread.

**Comment by luwanquan** [comment]
me too

**Comment by LiguidCool** [comment]
I think author abandoned the project ...

**Comment by tstevanovich** [comment]
Use https://atom.io/packages/platformio-ide-terminal
This seems to be working as intended

**Comment by LiguidCool** [comment]
@tstevanovich hmm, that plugin dont work too ...
