### ISSUE TITLE
Uncaught Error: channel closed

### ISSUE THREAD

**Issue by GrayOverride** [jeremyramin/terminal-plus#51]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.19
**System**: Microsoft Windows 10 Enterprise
**Thrown From**: [terminal-plus](https://github.com/jeremyramin/terminal-plus) package, v0.12.1

### Stack Trace

Uncaught Error: channel closed

```
At events.js:141

Error: channel closed
    at ChildProcess.target.send (internal/child_process.js:483:26)
    at Task.module.exports.Task.send (C:\Users\johand\AppData\Local\atom\app-1.0.19\resources\app.asar\src\task.js:118:27)
    at TerminalPlusView.module.exports.TerminalPlusView.input (C:\Users\johand\.atom\packages\terminal-plus\lib\view.coffee:241:17)
    at Terminal.<anonymous> (C:\Users\johand\.atom\packages\terminal-plus\lib\view.coffee:143:8)
    at Terminal.EventEmitter.emit (C:\Users\johand\.atom\packages\terminal-plus\node_modules\term.js\src\term.js:109:12)
    at Terminal.handler (C:\Users\johand\.atom\packages\terminal-plus\node_modules\term.js\src\term.js:3202:8)
    at Terminal.keyPress (C:\Users\johand\.atom\packages\terminal-plus\node_modules\term.js\src\term.js:2955:8)
    at HTMLDocument.<anonymous> (C:\Users\johand\.atom\packages\terminal-plus\node_modules\term.js\src\term.js:604:29)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "seti-ui-red",
      "one-dark-syntax"
    ],
    "autoHideMenuBar": true
  },
  "terminal-plus": {
    "core": {},
    "style": {}
  }
}
```

### Installed Packages

```coffee
# User
angularjs, v0.3.3
atom-jasmine, v0.6.0
autocomplete-angular-material, v0.4.0
emmet, v2.3.13
file-icons, v1.6.11
grunt-runner, v0.11.0
language-powershell, v2.1.0
language-SCSS, v0.4.0
minimap, v4.15.0
seti-ui-red, v0.13.0
terminal-plus, v0.12.1

# Dev
No dev packages
```

**Comment by GrayOverride** [comment]
Uninstalling -> installing the package fixed the issue

**Comment by kunday** [comment]
Ran into this problem couple of times today.

**Comment by jeremyramin** [comment]
@kunday You might want to take a look at issue #122 if you are on Windows.

**Comment by karuna24s** [comment]
Can anyone help me figure out how I can resolve this error:
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.9.8
**System**: Mac OS X 10.11.6
**Thrown From**: [terminal-plus](https://github.com/jeremyramin/terminal-plus) package, v0.14.5


### Stack Trace

Uncaught Error: channel closed

```
At events.js:154

Error: channel closed
    at ChildProcess.target.send (internal/child_process.js:523:16)
    at Task.module.exports.Task.send (/Users/karuna/Desktop/Karuna's Projects/Programming Related Downloads/Atom.app/Contents/Resources/app.asar/src/task.js:117:27)
    at TerminalPlusView.module.exports.TerminalPlusView.input (/Users/karunas24/.atom/packages/terminal-plus/lib/view.coffee:261:17)
    at InputDialog.module.exports.InputDialog.onConfirm (/Users/karunas24/.atom/packages/terminal-plus/lib/input-dialog.coffee:19:19)
    at space-pen-div.atom.commands.add.core:confirm (/Users/karunas24/.atom/packages/terminal-plus/lib/dialog.coffee:15:27)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Users/karuna/Desktop/Karuna's Projects/Programming Related Downloads/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /Users/karuna/Desktop/Karuna's Projects/Programming Related Downloads/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Users/karuna/Desktop/Karuna's Projects/Programming Related Downloads/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:580:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Users/karuna/Desktop/Karuna's Projects/Programming Related Downloads/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:388:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/Users/karuna/Desktop/Karuna's Projects/Programming Related Downloads/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:98:36)
    at HTMLDocument.<anonymous> (/Users/karuna/Desktop/Karuna's Projects/Programming Related Downloads/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)
```

### Commands

```
  2x -3:10.8.0 fuzzy-finder:toggle-file-finder (atom-pane.pane.active)
     -1:39.5.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -1:34.9.0 core:confirm (atom-text-editor.editor.mini.is-focused)
  7x -1:26 core:cancel (div.incompatible-packages.padded.native-key-bindings)
  8x -1:17.4.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -1:14.2.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -1:14.2.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -0:00.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "atom-dark-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-pair, v2.0.10 (active)
file-icons, v1.7.18 (active)
git-plus, v5.16.2 (inactive)
open-in-browser, v0.4.7 (inactive)
terminal-plus, v0.14.5 (active)
web-view, v3.0.0 (active)
atom-dark-syntax, v0.27.0 (active)
atom-dark-ui, v0.51.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.43.0 (inactive)
base16-tomorrow-dark-theme, v1.1.0 (inactive)
base16-tomorrow-light-theme, v1.1.1 (inactive)
one-dark-ui, v1.3.2 (active)
one-light-ui, v1.3.2 (inactive)
one-dark-syntax, v1.2.0 (inactive)
one-light-syntax, v1.2.0 (inactive)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.5.2 (active)
archive-view, v0.61.1 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.11.1 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.0 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.0 (active)
bookmarks, v0.41.0 (active)
bracket-matcher, v0.82.1 (active)
command-palette, v0.38.0 (inactive)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.39.0 (active)
fuzzy-finder, v1.3.0 (active)
git-diff, v1.1.0 (active)
find-and-replace, v0.198.0 (inactive)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.1 (active)
image-view, v0.58.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.1 (inactive)
markdown-preview, v0.158.0 (active)
metrics, v0.53.1 (active)
notifications, v0.64.1 (active)
open-on-github, v1.2.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.238.2 (active)
snippets, v1.0.2 (active)
spell-check, v0.67.1 (active)
status-bar, v1.4.1 (active)
styleguide, v0.46.0 (active)
symbols-view, v0.113.0 (inactive)
tabs, v0.98.1 (active)
timecop, v0.33.1 (active)
tree-view, v0.208.0 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.34.0 (active)
whitespace, v0.32.2 (active)
wrap-guide, v0.38.1 (active)
language-c, v0.52.1 (active)
language-clojure, v0.21.0 (active)
language-coffee-script, v0.47.0 (active)
language-csharp, v0.12.1 (active)
language-css, v0.36.2 (active)
language-gfm, v0.86.0 (active)
language-git, v0.13.0 (active)
language-go, v0.42.0 (active)
language-html, v0.44.1 (active)
language-hyperlink, v0.16.0 (active)
language-java, v0.22.0 (active)
language-javascript, v0.119.0 (active)
language-json, v0.18.0 (active)
language-less, v0.29.3 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.35.0 (active)
language-php, v0.37.0 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.0 (active)
language-ruby, v0.68.5 (active)
language-ruby-on-rails, v0.25.0 (active)
language-sass, v0.52.0 (active)
language-shellscript, v0.22.3 (active)
language-source, v0.9.0 (active)
language-sql, v0.21.1 (active)
language-text, v0.7.1 (active)
language-todo, v0.28.0 (active)
language-toml, v0.18.0 (active)
language-xml, v0.34.8 (active)
language-yaml, v0.26.0 (active)

# Dev
No dev packages
```

**Comment by marehr** [comment]
After updating terminal-plus to 0.14.5 and restarting, I got this issue (at least the issue popup-detector suggested this issue). I could resolve it by manually rebuilding via [apm](https://github.com/atom/apm) and restarting again.

```bash
# execute in a terminal/shell from any directory:
> apm rebuild
Rebuilding modules ✓
```
