### ISSUE TITLE
It doesn't work on mac!

### ISSUE THREAD

**Issue by danptesta** [jeremyramin/terminal-plus#514]
I can't open any terminals after installing.  I don't get the tool bar at the bottom of the window.  The menu items are there under "Packages", but they don't do anything!

**Comment by stalinb87** [comment]
The menu bar is showing at the button but the terminal never open, and cannot do anything

![screen shot 2017-10-03 at 11 55 07 am](https://user-images.githubusercontent.com/2779135/31135070-6df8ef1c-a810-11e7-9c8d-e9652d3be6c2.png)

Stay that way forever

**Comment by stalinb87** [comment]
I am getting this error

```
The module '/Users/sbonilla/.atom/packages/terminal-plus/node_modules/pty.js/bin/darwin/x64.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 46. This version of Node.js requires
NODE_MODULE_VERSION 53. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or`npm install`). Error: The module '/Users/sbonilla/.atom/packages/terminal-plus/node_modules/pty.js/bin/darwin/x64.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 46. This version of Node.js requires
NODE_MODULE_VERSION 53. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or`npm install`).
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:173:20)
    at Object.Module._extensions..node (module.js:598:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:173:20)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
```

i am using node v6.9.5 (npm v5.4.0), try to update to the latest v8.6.0 and make npm i after deleting node_modules and still getting the error

**Comment by jpswade** [comment]
I also had an issue with this package, couldn't get it to work at all...

**Comment by Fred-Barclay** [comment]
Hey guys,
Terminal plus isn't being maintained any more. There are two supported forks that I'm aware of: [Termination](https://github.com/Fred-Barclay/Termination) (my fork) and [platformio-atom-ide-terminal](https://github.com/platformio/platformio-atom-ide-terminal).
