### ISSUE TITLE
Terminal not launching. Seems related to Node version.

### ISSUE THREAD

**Issue by Rude-Monkey** [jeremyramin/terminal-plus#522]
I only get a black window with a cursor blinking in it after a "successful" installation. I just installed my new working machine with the latest Atom and Node packages.

By looking at the console in the developer tools, I noticed this: 
 ![capture d ecran de 2017-11-25 15-43-24](https://user-images.githubusercontent.com/16140019/33235857-852bd29c-d1f7-11e7-9506-4365d091fd7d.png)

**Comment by tonykay** [comment]
I see the same thing in the log and the same blinking cursor

- Atom 1.22.1
- Latest terminal-plus: 0.14.5
- OSX: 10.12.6

`The module '/Users/tok/.atom/packages/terminal-plus/node_modules/pty.js/bin/darwin/x64.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 46. This version of Node.js requires
NODE_MODULE_VERSION 53. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or`npm install`). Error: The module '/Users/tok/.atom/packages/terminal-plus/node_modules/pty.js/bin/darwin/x64.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 46. This version of Node.js requires
NODE_MODULE_VERSION 53. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or`npm install`).
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:173:20)
    at Object.Module._extensions..node (module.js:598:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:173:20)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/tok/.atom/packages/terminal-plus/node_modules/pty.js/lib/pty.js:17:9)
    at Object.<anonymous> (/Users/tok/.atom/packages/terminal-plus/node_modules/pty.js/lib/pty.js:477:3)
    at Module._compile (module.js:571:32)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:234:23)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/tok/.atom/packages/terminal-plus/node_modules/pty.js/index.js:2:18)
    at Object.<anonymous> (/Users/tok/.atom/packages/terminal-plus/node_modules/pty.js/index.js:4:3)
    at Module._compile (module.js:571:32)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:234:23)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/tok/.atom/packages/terminal-plus/lib/process.coffee:1:7)
    at Object.<anonymous> (/Users/tok/.atom/packages/terminal-plus/lib/process.coffee:1:1)
    at Object.<anonymous> (/Users/tok/.atom/packages/terminal-plus/lib/process.coffee:1:1)
    at Module._compile (module.js:571:32)`

**Comment by maxadamo** [comment]
same here. 
- Atom 1.22.1
- Linux: kernel 4.13.0-19
- terminal-plus: 0.14.5

**Comment by ghost** [comment]
Ditto.

Distro: Linux Mint 18.3
Kernel: 4.10.0-42
terminal-pllus: 0.14.5

atom --version output:

```
Atom    : 1.23.0
Electron: 1.6.15
Chrome  : 56.0.2924.87
Node    : 7.4.0
```

**Comment by jp-lno** [comment]
Same here on a freshly new install

- Distro: MacOs 10.13.2
- Atom: 1.23.0
- Node: 9.3.0
- Terminal-Plus : 0.14.5

**Comment by jp-lno** [comment]
I solve my issue by installing platform-ide-terminal 2.7.0 on Atom.
This package is just a fully functional fork of Terminal-Plus

**Comment by ghost** [comment]
@jplongo Thank you for this. Btw, it's `platformio-ide-terminal`.

**Comment by MichaelBelgium** [comment]
Same here, black window and only blinking cursor

OS: Windows 10 (64 bit)
Atom: 1.23.1

**Comment by steals** [comment]
Same issue for me on macOs 10.13.2
Atom    : 1.23.1
Electron: 1.6.15
Chrome  : 56.0.2924.87
Node    : 7.4.0

Rumors says terminal-plus is no longer maintained https://github.com/jeremyramin/terminal-plus/issues/514#issuecomment-334952042

**Comment by Rude-Monkey** [comment]
I'm closing this right now as I guess it may not be that relevant anymore.
