### ISSUE TITLE
Unable to open terminal on Windows

### ISSUE THREAD

**Issue by doberkofler** [jeremyramin/terminal-plus#523]
Unable to run terminal-plus. The pane opens and but no command prompt is shown.
OS: Windows 7 x64
Node: 8.9.1
Atom: 1.22.1

The node developer tolls show the following error:
```
The specified procedure could not be found.
\\?\C:\Users\doberkofler.LBITS\.atom\packages\terminal-plus\node_modules\pty.js\bin\win32\x64.node Error: The specified procedure could not be found.
\\?\C:\Users\doberkofler.LBITS\.atom\packages\terminal-plus\node_modules\pty.js\bin\win32\x64.node
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:173:20)
    at Object.Module._extensions..node (module.js:598:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:173:20)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\doberkofler.LBITS\.atom\packages\terminal-plus\node_modules\pty.js\lib\pty.js:17:9)
    at Object.<anonymous> (C:\Users\doberkofler.LBITS\.atom\packages\terminal-plus\node_modules\pty.js\lib\pty.js:477:3)
    at Module._compile (module.js:571:32)
    at Object.value [as .js] (C:\Users\doberkofler.LBITS\AppData\Local\atom\app-1.22.1\resources\app.asar\src\compile-cache.js:234:23)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\doberkofler.LBITS\.atom\packages\terminal-plus\node_modules\pty.js\lib\pty_win.js:10:20)
    at Object.<anonymous> (C:\Users\doberkofler.LBITS\.atom\packages\terminal-plus\node_modules\pty.js\lib\pty_win.js:366:3)
    at Module._compile (module.js:571:32)
    at Object.value [as .js] (C:\Users\doberkofler.LBITS\AppData\Local\atom\app-1.22.1\resources\app.asar\src\compile-cache.js:234:23)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\doberkofler.LBITS\.atom\packages\terminal-plus\node_modules\pty.js\index.js:2:18)
    at Object.<anonymous> (C:\Users\doberkofler.LBITS\.atom\packages\terminal-plus\node_modules\pty.js\index.js:4:3)
    at Module._compile (module.js:571:32)
    at Object.value [as .js] (C:\Users\doberkofler.LBITS\AppData\Local\atom\app-1.22.1\resources\app.asar\src\compile-cache.js:234:23)
(anonymous) @ <embedded>:72912
(anonymous) @ <embedded>:72986
module.exports.Emitter.simpleDispatch @ <embedded>:64210
module.exports.Emitter.emit @ <embedded>:64326
(anonymous) @ <embedded>:72938
emitTwo @ events.js:106
emit @ events.js:191
process.nextTick @ internal/child_process.js:752
_combinedTickCallback @ internal/process/next_tick.js:67
_tickCallback @ internal/process/next_tick.js:98
events.js:106 handler is not defined ReferenceError: handler is not defined
    at process.<anonymous> (C:\Users\doberkofler.LBITS\AppData\Local\atom\app-1.22.1\resources\app.asar\src\task-bootstrap.js:51:20)
    at emitTwo (events.js:106:13)
    at process.emit (events.js:191:7)
    at process.nextTick (internal/child_process.js:752:12)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
(anonymous) @ <embedded>:72912
(anonymous) @ <embedded>:72986
module.exports.Emitter.simpleDispatch @ <embedded>:64210
module.exports.Emitter.emit @ <embedded>:64326
(anonymous) @ <embedded>:72938
emitTwo @ events.js:106
emit @ events.js:191
process.nextTick @ internal/child_process.js:752
_combinedTickCallback @ internal/process/next_tick.js:67
_tickCallback @ internal/process/next_tick.js:98
```

**Comment by MichaelBelgium** [comment]
Same here. Just getting a black window but the cursor is blinking. 

OS: Windows 10 (64 bit)
Atom: 1.23.1

**Comment by doughtmw** [comment]
Try out this (https://atom.io/packages/platformio-ide-terminal) fork of terminal-plus! You can install it through the Atom package manager via **platformio-ide-terminal**. It worked for me on Windows 10 and Atom 1.23.1. I think development may have slowed down on this project.
