### ISSUE TITLE
Terminal opens but there is no prompt to enter commands

### ISSUE THREAD

**Issue by ghost** [jeremyramin/terminal-plus#540]
When I installed the terminal plus.  I ran it and all I see is a black screen without a prompt.  So it does give anywhere to put commands at.  
![screenshot from 2018-05-18 14-56-41](https://user-images.githubusercontent.com/10147569/40259636-dcd4fe00-5aab-11e8-8a0f-2bedf0f45d05.png)

**Comment by SoleneChiche** [comment]
Hi, 

I have the same issue :-/
Can someone help with that ?
I'm running on Mac OS X v10.13.4 with Atom v1.27.1
Thanks in advance

**Comment by TorstenVogt** [comment]
Salut,
i had same issue on Win10 with Atom 1.27.1 x64. 

I just have installed the terminal-plus package. The "buildIn" Terminal is working within atom.
But i missed the Need this for   **npm install -g node-gyp** at this time.
After following the instructions for node-gyp there is still no prompt ...
Greets

**Comment by RaymondMouthaan** [comment]
Same issue here on Atom v1.27.1 and Windows 10 x64 :(

**Comment by Reid-Luna** [comment]
I am having the same problem with Atom 1.27.1 on ubuntu 16.04

**Comment by yamahachou** [comment]
Facing the same issue here~~~ running on Max OSX v10.11.6

**Comment by ghost** [comment]
I just tried a different add on because I need to use the terminal within Atom.
________________________________

**Comment by rsokz** [comment]
+1

**Comment by tale07** [comment]
+1

**Comment by Asgoret** [comment]
+1

**Comment by samlarsen1** [comment]
+1

**Comment by DHBuild002** [comment]
+1 - Looks like an excellent integration btw!

**Comment by iangabrielsanchez** [comment]
this might help 
```
Cannot find module '../build/Release/pty.node'

events.js:106
The module '/Users/<user>/.atom/packages/terminal-plus/node_modules/pty.js/bin/darwin/x64.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 46. This version of Node.js requires
NODE_MODULE_VERSION 54. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or`npm install`). Error: The module '/Users/<user>/.atom/packages/terminal-plus/node_modules/pty.js/bin/darwin/x64.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 46. This version of Node.js requires
NODE_MODULE_VERSION 54. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or`npm install`).
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:173:20)
    at Object.Module._extensions..node (module.js:598:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:173:20)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/<user>/.atom/packages/terminal-plus/node_modules/pty.js/lib/pty.js:17:9)
    at Object.<anonymous> (/Users/<user>/.atom/packages/terminal-plus/node_modules/pty.js/lib/pty.js:477:3)
    at Module._compile (module.js:571:32)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:235:23)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/<user>/.atom/packages/terminal-plus/node_modules/pty.js/index.js:2:18)
    at Object.<anonymous> (/Users/<user>/.atom/packages/terminal-plus/node_modules/pty.js/index.js:4:3)
    at Module._compile (module.js:571:32)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:235:23)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/<user>/.atom/packages/terminal-plus/lib/process.coffee:1:7)
    at Object.<anonymous> (/Users/<user>/.atom/packages/terminal-plus/lib/process.coffee:1:1)
    at Object.<anonymous> (/Users/<user>/.atom/packages/terminal-plus/lib/process.coffee:1:1)
    at Module._compile (module.js:571:32)
(anonymous) @ <embedded>:76210
(anonymous) @ <embedded>:76284
module.exports.Emitter.simpleDispatch @ <embedded>:66749
module.exports.Emitter.emit @ <embedded>:66865
(anonymous) @ <embedded>:76236
emitTwo @ events.js:106
emit @ events.js:194
process.nextTick @ internal/child_process.js:766
_combinedTickCallback @ internal/process/next_tick.js:73
_tickCallback @ internal/process/next_tick.js:104
events.js:106 handler is not defined ReferenceError: handler is not defined
    at process.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/task-bootstrap.js:51:20)
    at emitTwo (events.js:106:13)
    at process.emit (events.js:194:7)
    at process.nextTick (internal/child_process.js:766:12)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)

**Comment by ghost** [comment]
No, I uninstalled it and when a different route...  Thanks

________________________________

**Comment by Fred-Barclay** [comment]
Hi everyone,
Terminal-plus isn't being maintained anymore. I maintain a fork if you'd like to try it: https://github.com/Fred-Barclay/Termination

Cheers!
Fred
