### ISSUE TITLE
Terminal-plus not working on Atom 1.36.1 due to a dependency issue

### ISSUE THREAD

**Issue by mlaunois** [jeremyramin/terminal-plus#562]
I installed recently [terminal-plus](https://atom.io/packages/terminal-plus) on my Ubuntu 18.10.
However, launching first time the addon gives me a black screen apart from a flashing cursor. And I can't type anything there.

Package error in DevTools:
```
The module '/home/maxime/.atom/packages/terminal-plus/node_modules/pty.js/bin/linux/x64.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 46. This version of Node.js requires
NODE_MODULE_VERSION 57. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`). Error: The module '/home/maxime/.atom/packages/terminal-plus/node_modules/pty.js/bin/linux/x64.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 46. This version of Node.js requires
NODE_MODULE_VERSION 57. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:166:20)
    at Object.Module._extensions..node (module.js:671:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:166:20)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (module.js:586:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/maxime/.atom/packages/terminal-plus/node_modules/pty.js/lib/pty.js:17:9)
    at Object.<anonymous> (/home/maxime/.atom/packages/terminal-plus/node_modules/pty.js/lib/pty.js:477:3)
    at Module._compile (module.js:642:30)
    at Object.value [as .js] (/usr/share/atom/resources/app.asar/src/compile-cache.js:235:23)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (module.js:586:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/maxime/.atom/packages/terminal-plus/node_modules/pty.js/index.js:2:18)
    at Object.<anonymous> (/home/maxime/.atom/packages/terminal-plus/node_modules/pty.js/index.js:4:3)
    at Module._compile (module.js:642:30)
    at Object.value [as .js] (/usr/share/atom/resources/app.asar/src/compile-cache.js:235:23)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (module.js:586:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/maxime/.atom/packages/terminal-plus/lib/process.coffee:1:7)
    at Object.<anonymous> (/home/maxime/.atom/packages/terminal-plus/lib/process.coffee:1:1)
    at Object.<anonymous> (/home/maxime/.atom/packages/terminal-plus/lib/process.coffee:1:1)
    at Module._compile (module.js:642:30)
```

I guess that error happened because of the `pty.js` module, but I'm not able to recompile the module with either `npm install` or `npm rebuild`: [builderror.log](https://github.com/jeremyramin/terminal-plus/files/3198574/builderror.log)

System information:
- Atom 1.36.1
- Ubuntu 18.10 64-bit
- Terminal-plus 0.14.5

**Comment by danhawkins** [comment]
Same issue for me, I am using ASDF

**Comment by vaibhavatul47** [comment]
I was also facing same issue, I ended up using [platformio-ide-terminal](https://atom.io/packages/platformio-ide-terminal)

**Comment by the-j0k3r** [comment]
This project has been dead for 3/4 years.
