### ISSUE TITLE
.

### ISSUE THREAD

**Issue by Isaac-327** [jeremyramin/terminal-plus#589]
Installing terminal -plus failed!
Here's the error I get:

0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\ProgramData\\ming3\\atom\\app-1.58.0\\resources\\app\\apm\\bin\\node.exe',
1 verbose cli   'C:\\ProgramData\\ming3\\atom\\app-1.58.0\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   '--globalconfig',
1 verbose cli   'C:\\Users\\ming3\\.atom\\.apm\\.apmrc',
1 verbose cli   '--userconfig',
1 verbose cli   'C:\\Users\\ming3\\.atom\\.apmrc',
1 verbose cli   'install',
1 verbose cli   'https://www.atom.io/api/packages/terminal-plus/versions/0.14.5/tarball',
1 verbose cli   '--target=9.4.4',
1 verbose cli   '--disturl=https://atom.io/download/electron',
1 verbose cli   '--arch=x64',
1 verbose cli   '--global-style'
1 verbose cli ]
2 info using npm@6.14.13
3 info using node@v12.14.1
4 verbose npm-session 362b2974fbe623ee
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 http fetch GET 304 https://codeload.github.com/jeremyramin/terminal-plus/legacy.tar.gz/refs/tags/v0.14.5 2882ms (from cache)
8 silly pacote remote manifest for undefined@https://www.atom.io/api/packages/terminal-plus/versions/0.14.5/tarball fetched in 2935ms
9 timing stage:loadCurrentTree Completed in 3005ms
10 silly install loadIdealTree
11 silly install cloneCurrentTreeToIdealTree
12 timing stage:loadIdealTree:cloneCurrentTree Completed in 1ms
13 silly install loadShrinkwrap
14 timing stage:loadIdealTree:loadShrinkwrap Completed in 4ms
15 silly install loadAllDepsIntoIdealTree
16 silly resolveWithNewModule terminal-plus@0.14.5 checking installable status
17 silly fetchPackageMetaData error for pty.js@git+https://github.com/jeremyramin/pty.js.git#28f2667 Error while executing:
17 silly fetchPackageMetaData undefined ls-remote -h -t https://github.com/jeremyramin/pty.js.git
17 silly fetchPackageMetaData
17 silly fetchPackageMetaData
17 silly fetchPackageMetaData spawn git ENOENT
18 silly fetchPackageMetaData error for term.js@git+https://github.com/jeremyramin/term.js.git Error while executing:
18 silly fetchPackageMetaData undefined ls-remote -h -t https://github.com/jeremyramin/term.js.git
18 silly fetchPackageMetaData
18 silly fetchPackageMetaData
18 silly fetchPackageMetaData spawn git ENOENT
19 http fetch GET 200 https://registry.npmjs.org/atom-space-pen-views 120ms (from cache)
20 silly pacote range manifest for atom-space-pen-views@^2.1.0 fetched in 128ms
21 silly resolveWithNewModule atom-space-pen-views@2.2.0 checking installable status
22 http fetch GET 304 https://registry.npmjs.org/underscore 568ms (from cache)
23 silly pacote range manifest for underscore@^1.8.3 fetched in 578ms
24 silly resolveWithNewModule underscore@1.13.1 checking installable status
25 timing stage:rollbackFailedOptional Completed in 1ms
26 timing stage:runTopLevelLifecycles Completed in 3684ms
27 silly saveTree apm-install-dir-2021630-1440-o5qp4y.n1ua
27 silly saveTree `-- terminal-plus@0.14.5
27 silly saveTree   +-- atom-space-pen-views@2.2.0
27 silly saveTree   `-- underscore@1.13.1
28 verbose stack Error: spawn git ENOENT
28 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:264:19)
28 verbose stack     at onErrorNT (internal/child_process.js:456:16)
28 verbose stack     at processTicksAndRejections (internal/process/task_queues.js:81:21)
29 verbose cwd C:\Users\ming3\AppData\Local\Temp\apm-install-dir-2021630-1440-o5qp4y.n1ua
30 verbose Windows_NT 10.0.18362
31 verbose argv "C:\\ProgramData\\ming3\\atom\\app-1.58.0\\resources\\app\\apm\\bin\\node.exe" "C:\\ProgramData\\ming3\\atom\\app-1.58.0\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "C:\\Users\\ming3\\.atom\\.apm\\.apmrc" "--userconfig" "C:\\Users\\ming3\\.atom\\.apmrc" "install" "https://www.atom.io/api/packages/terminal-plus/versions/0.14.5/tarball" "--target=9.4.4" "--disturl=https://atom.io/download/electron" "--arch=x64" "--global-style"
32 verbose node v12.14.1
33 verbose npm  v6.14.13
34 error code ENOENT
35 error syscall spawn git
36 error path git
37 error errno ENOENT
38 error enoent Error while executing:
38 error enoent undefined ls-remote -h -t https://github.com/jeremyramin/pty.js.git
38 error enoent
38 error enoent
38 error enoent spawn git ENOENT
39 error enoent This is related to npm not being able to find a file.
40 verbose exit [ 1, true ]

**Comment by UziTech** [comment]
This package is no longer maintained. Please uninstall terminal-plus and install either [terminus](https://atom.io/packages/terminus) or [x-terminal](https://atom.io/packages/x-terminal)
