### ISSUE TITLE
Install Error on Windows 10

### ISSUE THREAD

**Issue by JestonBlu** [jeremyramin/terminal-plus#59]
I seem to be having trouble getting this package to install on Windows 10.  I have it working on an Arch Linux setup and Windows 7 at work behind a proxy, but Windows 10 at home is giving me fits.  I do not seem to have issues installing other atom packages on Windows 10 which is why im confused.

I posted this on the NPM issues board as the error message suggests, but It hasn't gotten anywhere yet.  I also tried uninstalling atom and deleting all of the packages.  Not sure if anyone can help, but I thought I would give it a try.

```
Installing “terminal-plus@0.12.3” failed.Hide output…

npm WARN addRemoteGit Error: Command failed: 
npm WARN addRemoteGit     at ChildProcess.exithandler (child_process.js:658:15)
npm WARN addRemoteGit     at ChildProcess.emit (events.js:98:17)
npm WARN addRemoteGit     at maybeClose (child_process.js:766:16)
npm WARN addRemoteGit     at Process.ChildProcess._handle.onexit (child_process.js:833:5)
npm WARN addRemoteGit  git+https://github.com/jeremyramin/term.js.git resetting remote C:\Users\Joseph\.atom\.apm\_git-remotes\https-github-com-jeremyramin-term-js-git-7be5884d because of error: { [Error: Command failed: ] killed: false, code: 1, signal: null }
npm WARN addRemoteGit Error: Command failed: 
npm WARN addRemoteGit     at ChildProcess.exithandler (child_process.js:658:15)
npm WARN addRemoteGit     at ChildProcess.emit (events.js:98:17)
npm WARN addRemoteGit     at maybeClose (child_process.js:766:16)
npm WARN addRemoteGit     at Socket.<anonymous> (child_process.js:979:11)
npm WARN addRemoteGit     at Socket.emit (events.js:95:17)
npm WARN addRemoteGit     at Pipe.close (net.js:466:12)
npm WARN addRemoteGit  git+https://github.com/jeremyramin/pty.js.git#3e9c58 resetting remote C:\Users\Joseph\.atom\.apm\_git-remotes\https-github-com-jeremyramin-pty-js-git-27ad4d30 because of error: { [Error: Command failed: ] killed: false, code: 1, signal: null }
npm ERR! git clone --template=C:\Users\Joseph\.atom\.apm\_git-remotes\_templates --mirror https://github.com/jeremyramin/term.js.git C:\Users\Joseph\.atom\.apm\_git-remotes\https-github-com-jeremyramin-term-js-git-7be5884d: Cloning into bare repository 'C:\Users\Joseph\.atom\.apm\_git-remotes\https-github-com-jeremyramin-term-js-git-7be5884d'...
npm ERR! git clone --template=C:\Users\Joseph\.atom\.apm\_git-remotes\_templates --mirror https://github.com/jeremyramin/term.js.git C:\Users\Joseph\.atom\.apm\_git-remotes\https-github-com-jeremyramin-term-js-git-7be5884d: fatal: unable to access 'https://github.com/jeremyramin/term.js.git/': SSL certificate problem: unable to get local issuer certificate
npm ERR! git clone --template=C:\Users\Joseph\.atom\.apm\_git-remotes\_templates --mirror https://github.com/jeremyramin/pty.js.git C:\Users\Joseph\.atom\.apm\_git-remotes\https-github-com-jeremyramin-pty-js-git-27ad4d30: Cloning into bare repository 'C:\Users\Joseph\.atom\.apm\_git-remotes\https-github-com-jeremyramin-pty-js-git-27ad4d30'...
npm ERR! git clone --template=C:\Users\Joseph\.atom\.apm\_git-remotes\_templates --mirror https://github.com/jeremyramin/pty.js.git C:\Users\Joseph\.atom\.apm\_git-remotes\https-github-com-jeremyramin-pty-js-git-27ad4d30: fatal: unable to access 'https://github.com/jeremyramin/pty.js.git/': SSL certificate problem: unable to get local issuer certificate
npm ERR! Windows_NT 6.2.9200
npm ERR! argv "C:\\Users\\Joseph\\AppData\\Local\\atom\\app-1.0.19\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\Joseph\\AppData\\Local\\atom\\app-1.0.19\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "C:\\Users\\Joseph\\.atom\\.apm\\.apmrc" "--userconfig" "C:\\Users\\Joseph\\.atom\\.apmrc" "install" "C:\\Users\\Joseph\\AppData\\Local\\Temp\\d-115927-10584-1velsc4\\package.tgz" "--target=0.30.7" "--arch=ia32" "--msvs_version=2013"
npm ERR! node v0.10.40
npm ERR! npm  v2.13.3
npm ERR! code 128

npm ERR! Command failed: Cloning into bare repository 'C:\Users\Joseph\.atom\.apm\_git-remotes\https-github-com-jeremyramin-term-js-git-7be5884d'...
npm ERR! fatal: unable to access 'https://github.com/jeremyramin/term.js.git/': SSL certificate problem: unable to get local issuer certificate
npm ERR! 
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
```

**Comment by jeremyramin** [comment]
My understanding of the error message says that it is an issue with using https:// and SSL to fetch the repository where my dependency is located.
```
npm ERR! fatal: unable to access 'https://github.com/jeremyramin/term.js.git/': SSL certificate problem: unable to get local issuer certificate
```
I have installed this before on other Windows 10 machines so I do not think it is an issue with Windows 10. 

Please try making a new folder somewhere and use the command: `git clone https://github.com/jeremyramin/term.js.git`. This is assuming you have the git command line tools installed or you can use the `Git Bash` that comes with Github Desktop. Let me know if it clones successfully.

**Comment by JestonBlu** [comment]
It didn't work at first because I didn't have my public ssh key on my Github settings (not sure when i deleted that). I resolved that and was able to clone successfully, however the install through atom still did not work

**Comment by jeremyramin** [comment]
According to [this post on the Atom Discuss forum](https://discuss.atom.io/t/unable-to-install-packages/13812/6?u=jeremyramin), Atom uses the `git` command found in your `PATH` to install packages. The best way to confirm if that `git` works is to use the command from your system's default shell: `cmd.exe` or `Powershell`. If git clone works from there, then the issue lies somewhere else.

**Comment by JestonBlu** [comment]
Thanks, I think its a system issue of mine.

**Comment by JestonBlu** [comment]
Figured it out... i had upgraded to the new Git version that installs into Program Files\Git rather than Program Files (x86)\Git.  The PATH variable was out of date. Thanks for the help.

**Comment by jeremyramin** [comment]
No problem. Glad you were able to resolve your issue.
