### ISSUE TITLE
Atom 1.2.0 beta0 - Blank panel

### ISSUE THREAD

**Issue by JohnMurga** [jeremyramin/terminal-plus#62]
Package states it has to rebuild binary dependency and appears to do so successfully, but when opening a new panel the cursor just sits there in the upper left corner.

**Comment by jeremyramin** [comment]
@JohnMurga Please open the developer tools (`View > Developer > Toggle Developer Tools`) then click the *Console* tab. There should be some sort of error message there if the terminal is not opening properly.

**Comment by JohnMurga** [comment]
D:\pack\atom\App\Atom\resources\app.asar\src\task.js:52 The specified procedure could not be found.
D:\pack\atom\Data\AtomProfile\packages\terminal-plus\node_modules\pty.js\bin\win32\ia32.node Error: The specified procedure could not be found.
D:\pack\atom\Data\AtomProfile\packages\terminal-plus\node_modules\pty.js\bin\win32\ia32.node
    at Error (native)
    at Object.module.(anonymous function) (ATOM_SHELL_ASAR.js:137:20)
    at Object.module.(anonymous function) [as .node] (ATOM_SHELL_ASAR.js:137:20)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (D:\pack\atom\Data\AtomProfile\packages\terminal-plus\node_modules\pty.js\lib\pty.js:17:9)
    at Module._compile (module.js:434:26)
    at Object.defineProperty.value [as .js] (D:\pack\atom\App\Atom\resources\app.asar\src\compile-cache.js:190:21)(anonymous function) @ D:\pack\atom\App\Atom\resources\app.asar\src\task.js:52(anonymous function) @ D:\pack\atom\App\Atom\resources\app.asar\src\task.js:126module.exports.Emitter.emit @ D:\pack\atom\App\Atom\resources\app.asar\node_modules\event-kit\lib\emitter.js:86(anonymous function) @ D:\pack\atom\App\Atom\resources\app.asar\src\task.js:78emitTwo @ events.js:87emit @ events.js:172handleMessage @ internal/child_process.js:685channel.onread @ internal/child_process.js:440
3D:\pack\atom\App\Atom\resources\app.asar\src\task.js:52 Cannot read property 'bind' of null TypeError: Cannot read property 'bind' of null
    at process.<anonymous> (D:\pack\atom\App\Atom\resources\app.asar\src\task-bootstrap.js:82:23)
    at emitTwo (events.js:87:13)
    at process.emit (events.js:172:7)
    at handleMessage (internal/child_process.js:685:10)
    at Pipe.channel.onread (internal/child_process.js:440:11)

**Comment by JohnMurga** [comment]
As stated in the title error only occurs in Atom 1.2.0 beta0 ...
Which uses Electron 0.34.0.

**Comment by jeremyramin** [comment]
> As stated in the title error only occurs in Atom 1.2.0 beta0 ...
Which uses Electron 0.34.0.

That would do it. I provide precompiled binaries with Terminal-Plus so everyone can use it. The only downside is that if people don't have the tools to run `node-gyp` and Electron updates, then the package breaks. The only thing I can really do is wait for the 1.2 release to be official before I release an update that contains binaries compiled for Electron 0.34.0.
