### ISSUE TITLE
Error when using next/prev with only one terminal

### ISSUE THREAD

**Issue by nunocastromartins** [jeremyramin/terminal-plus#65]
### Steps To Reproduce

1. Terminal Plus: New
2. Terminal Plus: Next/Prev

**Atom Version**: 1.1.0
**System**: linux 4.2.4-1-ARCH
**Thrown From**: [terminal-plus](https://github.com/jeremyramin/terminal-plus) package, v0.12.3

### Stack Trace

Uncaught TypeError: Cannot read property 'open' of null

```
At /home/nunomartins/.atom/packages/terminal-plus/lib/status-bar.coffee:30

TypeError: Cannot read property 'open' of null
    at atom-workspace.subscriptions.add.atom.commands.add.terminal-plus:next (/home/nunomartins/.atom/packages/terminal-plus/lib/status-bar.coffee:30:24)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:243:29)
    at /usr/share/atom/resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:528:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:351:22)
    at HTMLDocument.module.exports.WindowEventHandler.handleDocumentKeydown (/usr/share/atom/resources/app.asar/src/window-event-handler.js:97:20)
```

**Comment by jeremyramin** [comment]
Fixed as of v0.12.4. Please give it a try. If you still think this is still an issue, let me know. Otherwise please close this issue if it has been resolved.
