### ISSUE TITLE
Uncaught TypeError: Cannot set property 'innerHTML' of undefined

### ISSUE THREAD

**Issue by elalaouifaris** [jeremyramin/terminal-plus#82]
[Enter steps to reproduce below:]

1. While testing this tutorial: 
http://angular-meteor.com/tutorials/angular2/3-way-data-binding.
Section: Inserting Parties from the Console
2. Using the meteor helper module for running the server directly in Atom
3. started a shell in Atom and accessed the mongo shell by "meteor mongo"
4. when I typed "db" for the next command in the tutorial the reported bug showed up
5 Note: The Atom editor was in a small window mode where the shell could only show a line.

**Atom Version**: 1.1.0
**System**: Ubuntu 14.04.3
**Thrown From**: [terminal-plus](https://github.com/jeremyramin/terminal-plus) package, v0.14.0

### Stack Trace

Uncaught TypeError: Cannot set property 'innerHTML' of undefined

```
At /home/farishouda/.atom/packages/terminal-plus/node_modules/term.js/src/term.js:1689

TypeError: Cannot set property 'innerHTML' of undefined
  at Terminal.refresh (/home/farishouda/.atom/packages/terminal-plus/node_modules/term.js/src/term.js:1689:32)
  at HTMLTextAreaElement.onInput (/home/farishouda/.atom/packages/terminal-plus/node_modules/term.js/src/term.js:713:12)

```

### Commands

```
     -4:42.2.0 blur (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -4:34.3.0 core:confirm (atom-text-editor.editor.mini.is-focused)
  7x -4:34.3.0 blur (atom-text-editor.editor.mini.is-focused)
     -4:33.8.0 linter:lint (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
  2x -4:29.8.0 blur (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
     -4:24.8.0 vim-mode:activate-insert-mode (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
  2x -4:23.4.0 core:backspace (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
  2x -4:10.2.0 blur (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
     -4:06.7.0 core:move-right (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
     -4:02.7.0 vim-mode:activate-normal-mode (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
     -4:01.9.0 ex-mode:open (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
     -4:01.7.0 blur (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
     -4:01.6.0 core:confirm (atom-text-editor.editor.mini.is-focused)
 29x -4:01.5.0 blur (atom-text-editor.editor.mini.is-focused)
     -2:50.9.0 core:move-up (textarea.)
 43x -2:48.9.0 blur (textarea.)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "r-exec",
      "language-r"
    ]
  },
  "terminal-plus": {
    "core": {},
    "style": {}
  }
}
```

### Installed Packages

```coffee
# User
.bin, vundefined
angularjs, v0.3.3
atom-django, v0.3.0
atom-typescript, v7.8.0
color-picker, v2.0.13
css-snippets, v0.9.0
ex-mode, v0.7.0
keyboard-localization, v1.4.10
linter, v1.10.0
meteor-api, v2.20.0
meteor-helper, v0.27.0
minimap, v4.16.0
project-manager, v2.6.5
script, v3.0.2
terminal-plus, v0.14.0
vim-mode, v0.63.0

# Dev
No dev packages
```

**Comment by jeremyramin** [comment]
>The Atom editor was in a small window mode where the shell could only show a line.

Thank you for the detailed report. I was able to reproduce the issue with this detail. Expect the next release to have this issue fixed. You will probably have to restart Atom after updating Terminal-Plus for the changes to take effect.

**Comment by jeremyramin** [comment]
Fixed as of v0.14.1

**Comment by elalaouifaris** [comment]
Thank you for the very fast update!!
Great job and I really appreciate this tool!

**Comment by jeremyramin** [comment]
No problem. Thank you for using Terminal-Plus.
