### ISSUE TITLE
Uncaught TypeError: Cannot read property 'normal' of undefined

### ISSUE THREAD

**Issue by asowers1** [jeremyramin/terminal-plus#99]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.169.0
**System**: Mac OS X 10.11.1
**Thrown From**: [terminal-plus](https://github.com/jeremyramin/terminal-plus) package, v0.14.3

### Stack Trace

Uncaught TypeError: Cannot read property 'normal' of undefined

```
At /Users/andrew/.atom/packages/terminal-plus/lib/view.coffee:272

TypeError: Cannot read property 'normal' of undefined
  at TerminalPlusView.module.exports.TerminalPlusView.applyStyle (/Users/andrew/.atom/packages/terminal-plus/lib/view.coffee:272:24)
  at Terminal.<anonymous> (/Users/andrew/.atom/packages/terminal-plus/lib/view.coffee:140:8)
  at Terminal.on (/Users/andrew/.atom/packages/terminal-plus/node_modules/term.js/src/term.js:94:21)
  at Terminal.EventEmitter.emit (/Users/andrew/.atom/packages/terminal-plus/node_modules/term.js/src/term.js:109:12)
  at Terminal.open (/Users/andrew/.atom/packages/terminal-plus/node_modules/term.js/src/term.js:1063:8)
  at TerminalPlusView.module.exports.TerminalPlusView.displayTerminal (/Users/andrew/.atom/packages/terminal-plus/lib/view.coffee:120:15)
  at /Users/andrew/.atom/packages/terminal-plus/lib/view.coffee:208:10
  at HTMLDivElement.<anonymous> (/Users/andrew/.atom/packages/terminal-plus/lib/view.coffee:445:7)
  at HTMLDivElement.fn (/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/node_modules/atom-space-pen-views/node_modules/space-pen/vendor/jquery.js:5073:19)
  at HTMLDivElement.jQuery.event.dispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/node_modules/atom-space-pen-views/node_modules/space-pen/vendor/jquery.js:4676:9)
  at HTMLDivElement.elemData.handle (/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/node_modules/atom-space-pen-views/node_modules/space-pen/vendor/jquery.js:4360:46)

```

### Commands

```
     -2:32.4 settings-view:open (atom-text-editor.editor)
     -2:20.0 window:update-available (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-atom-light-syntax.theme-atom-dark-ui)
  2x -1:42.9 core:backspace (atom-text-editor.editor.mini)
     -0:33.1 core:select-all (atom-text-editor.editor.mini)
 13x -0:32.5 core:backspace (atom-text-editor.editor.mini)
     -0:00.9 core:select-all (atom-text-editor.editor.mini)
  3x -0:00.0 core:backspace (atom-text-editor.editor.mini)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-light-syntax"
    ]
  },
  "terminal-plus": {
    "core": {},
    "style": {}
  }
}
```

### Installed Packages

```coffee
# User
go-config, v0.2.3
go-find-references, v1.2.3
language-rust, v0.4.5
racer, v0.17.2
run-in-terminal, v0.5.0
rust-api-docs-helper, v0.5.1
set-syntax, v0.3.0
terminal-plus, v0.14.3

# Dev
No dev packages
```

/cc @atom/core

**Comment by jeremyramin** [comment]
>Atom Version: 0.169.0

I'm not sure if this is right. If it is correct, then there will continue to be an error until you update to the latest version of Atom. Actually, I'm pretty sure version v0.14.3 of Terminal-Plus can only be installed on Atom v1.2.0 or greater.

**Comment by jeremyramin** [comment]
Did updating Atom fix your issue?

**Comment by jeremyramin** [comment]
Closing this issue as it is not something fixable on my end.
